### ISSUE TITLE
Improve parser compatibility

### ISSUE THREAD

**Issue by leoppro** [pingcap/tidb#11486]
As MySQL evolves constantly,  there are always new SQL syntaxes that TiDB doesn’t support.  To support a new SQL function in TiDB is a careful decision, and may take a long time. For better compatibility and user experience, it’s our intention that TiDB can parse and ignore the unsupported functions while only executing the supported part of SQL. Therefore, we need to parse as many SQL syntaxes as possible in the TiDB Parser to make it behave more closely to the parser in MySQL.

To find out the differences between MySQL and TiDB parser, we generate SQL cases randomly based on the yacc file of MySQL. These SQL cases are later executed respectively in TiDB parser and MySQL server to screen out the incompatible ones that cause different behaviors between TiDB parser and MySQL. 

The incompatible test cases will be grouped by behaviors - those with similar behavior form a subtask, with an issue created correspondingly. As contributors, you can learn about the subtask based on the comments below the issue and claim accordingly. After finishing one or more subtasks, submit them individually or collectively as pull requests (PRs).

 See: [中文教程](https://pingcap.com/blog-cn/30mins-become-contributor-of-tidb-20190808/)

### Sub tasks list:

- [ ] Remove `CONSTRAINT` for `KEY | INDEX | FULLTEXT` pingcap/parser#535 @wty4427300
- [x] `SET=DEFAULT` pingcap/parser#549 @hey-kong pingcap/parser#551
- [x] `SQL_TSI_YEAR` pingcap/parser#537 @hey-kong pingcap/parser#540
- [x] `FIXED` pingcap/parser#555 @hey-kong pingcap/parser#556
- [x] `*TEXT BYTE | ASCII | UNICODE` pingcap/parser#529 @hey-kong pingcap/parser#536
- [x] `CREATE FULLTEXT...WITH PARSER` pingcap/parser#507 @yunnian pingcap/parser#524
- [x] `CHARSET DEFAULT` pingcap/parser#498 @sim41 pingcap/parser#566
- [x] `STORAGE ENGINE` pingcap/parser#500 @yangwenmai pingcap/parser#542
- [x] `CREATE INDEX .. TYPE` pingcap/parser#479 @yufeiminds pingcap/parser#533
- [x] `ORDER BY` pingcap/parser#499 @zuoRambo pingcap/parser#526
- [x] `DISCARD/IMPORT TABLESPACE` pingcap/parser#501 @fzhedu pingcap/parser#512
- [x] `CONSTRAINT` pingcap/parser#413 @ichn-hu pingcap/parser#548
- [x] `SQL_TSI_*` pingcap/parser#480 @ichn-hu pingcap/parser#495
- [x] `COLUMN_FORMAT` pingcap/parser#476 @doggeral pingcap/parser#482
- [x] `LOCK` clause error message pingcap/parser#508 @lauhg pingcap/parser#516
- [x] `VARCHARACTER` pingcap/parser#509 @lauhg pingcap/parser#515
- [x] `VARYING` pingcap/parser#503 @lauhg pingcap/parser#515
- [x] `CHARACTER VARYING` pingcap/parser#410 @lauhg pingcap/parser#465
- [x] `STATS_AUTO_RECALC` pingcap/parser#472 @lauhg pingcap/parser#483
- [x] `LONG` pingcap/parser#470 @lauhg pingcap/parser#473
- [x] `ALTER TABLE ... ALTER INDEX` pingcap/parser#463 @tangwz pingcap/parser#519
- [x] `ALTER TABLE ... RENAME COLUMN` pingcap/parser#462 @tangwz pingcap/parser#504
- [x] `ALTER TABLE ... RENAME` pingcap/parser#461 @tangwz pingcap/parser#489
- [x] `MATCH` pingcap/parser#426 @qiukun pingcap/parser#466
- [x] `REPAIR PARTITION` pingcap/parser#439 @huaouo pingcap/parser#453
- [x] `OPTIMIZE PARTITION` pingcap/parser#437 @huaouo pingcap/parser#453
- [x] `IMPORT PARTITION/TABLESPACE` pingcap/parser#436 @huaouo pingcap/parser#453
- [x] `DISCARD PARTITION/TABLESPACE` pingcap/parser#434 @huaouo pingcap/parser#453
- [x] `TRUNCATE PARTITION ALL` pingcap/parser#432 @huaouo pingcap/parser#453
- [x] `INSERT_METHOD` pingcap/parser#415 @TennyZhuang pingcap/parser#452
- [x] `DROP INDEX ... ALGORITHM` pingcap/parser#460 @zhenghaoz pingcap/parser#484
- [x] `CREATE INDEX .. VISIBLE/INVISIBLE` pingcap/parser#478 @zhenghaoz pingcap/parser#518
- [x] `ALGORITHM` pingcap/parser#429 @zhenghaoz pingcap/parser#454
- [x] `CREATE SPATIAL INDEX` pingcap/parser#431 @zhenghaoz pingcap/parser#454
- [x] `DROP INDEX ... LOCK` pingcap/parser#459 @zhenghaoz pingcap/parser#484
- [x] `CREATE FULLTEXT INDEX` pingcap/parser#430 @zhenghaoz pingcap/parser#454
- [x] `CREATE DATABASE … ENCRYPTION` pingcap/parser#417 @zhenghaoz pingcap/parser#450
- [x] `UNION` pingcap/parser#502 @spongedu pingcap/parser#523
- [x] `ENCRYPTION` pingcap/parser#475 @spongedu pingcap/parser#520
- [x] `FLOAT4/FLOAT8` pingcap/parser#474 @spongedu pingcap/parser#490
- [x] `SECONDARY_LOAD/SECONDARY_UNLOAD` pingcap/parser#444 @spongedu pingcap/parser#496
- [x] `CHECK` pingcap/parser#497 @spongedu pingcap/parser#505
- [x] `REBUILD PARTITION` pingcap/parser#448 @spongedu pingcap/parser#469
- [x] `FIELDS` pingcap/parser#464 @spongedu pingcap/parser#471
- [x] `REORGANIZE PARTITION` pingcap/parser#419 @spongedu pingcap/parser#494
- [x] `SERIAL` pingcap/parser#467 @spongedu pingcap/parser#481
- [x] `CHECK PARTITION` pingcap/parser#435 @spongedu pingcap/parser#457
- [x] `NO_WRITE_TO_BINLOG` pingcap/parser#445 @spongedu pingcap/parser#456
- [x] `TABLE_CHECKSUM` pingcap/parser#468 @leiysky pingcap/parser#488
- [x] `EXCHANGE PARTITION` pingcap/parser#412 @leiysky pingcap/parser#449
- [x] `PASSWORD EXPIRE` pingcap/parser#409 @leiysky pingcap/parser#442
- [x] `TEMPORARY TABLE` pingcap/parser#408 @leiysky pingcap/parser#438
- [x] `RTREE` pingcap/parser#406 @leiysky pingcap/parser#433
- [x] `SECONDARY_ENGINE` pingcap/parser#405 @leiysky pingcap/parser#418
- [x] `STATS_SAMPLE_PAGES` pingcap/parser#404 @leiysky pingcap/parser#414
- [x] `STORAGE` pingcap/parser#403 @leiysky pingcap/parser#407
- [x] `WITH/WITHOUT VALIDATION` pingcap/parser#420 @imtsuki pingcap/parser#427
- [x] `REMOVE PARTITIONING` pingcap/parser#402 @tangenta pingcap/parser#396

**Comment by wjhuang2016** [comment]
How about statements like `insert into t1 set a=default;`?
```
value:
    {expr | DEFAULT}
```
https://dev.mysql.com/doc/refman/8.0/en/insert.html

**Comment by leoppro** [comment]
> How about statements like `insert into t1 set a=default;`?
> 
> ```
> value:
>     {expr | DEFAULT}
> ```
> 
> https://dev.mysql.com/doc/refman/8.0/en/insert.html

The priority of DDL stmts is higher than DML. Therefore we will focus on DDL first.

**Comment by spongedu** [comment]
Description in the doc: [The doc](https://pingcap.com/blog-cn/30mins-become-contributor-of-tidb-20190808/) is a little inaccurate.  some issues, such as #445, is not a `MySQL 8.0` compatible issue. MySQL 5.7 support this as well.
