### ISSUE TITLE
Tracking issue for Dynamic Configuration Change

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb#13795]
The PR https://github.com/pingcap/tidb/pull/13660 proposes a unified way to manage the configuration options of TiDB, TiKV, and PD by storing them in PD and support dynamically change the configuration options by using the same way among the different components which can greatly improve usability.

## Note

This issue is a TODO list catalog that is used to clarify the split details of the entire feature. If you are interested in a part, use the following workflow:

1. Select the module you are interested in.
2. Create a new issue to claim the relevant work and describe the rough implementation in the new issue.
3. File a new pull request.

## Issues:

- Protocol Definition
  - [ ] Define the `Configuration gRPC Service` and the related message type in [kvproto](https://github.com/pingcap/kvproto)  [#498](https://github.com/pingcap/kvproto/pull/498) @overvenus 

- Basic Framework
  - [ ] [PD](https://github.com/pingcap/pd) @rleungx 
    - [ ] Implement `Create` function @rleungx 
    - [ ] Implement `Get` function @rleungx
    - [ ] Implement `Update` function @rleungx
    - [ ] Implement `Delete` function
    - [ ] Support persist and reload configurations @rleungx 
  - [ ] [TiKV](https://github.com/tikv/tikv) @NingLin-P 
  - [ ] [TiDB](https://github.com/pingcap/tidb)
    - [ ] Add system table to manage the configuration

- Client implementation
  - [ ] Go 
  - [ ] Rust

- Improvement
  - [ ] [PD](https://github.com/pingcap/pd)
    - [ ] Support more transition of type for `toml`
    - [ ] Handle the error message more properly
    - [ ] Make error message more clear

- Optional
  - [ ] Add HTTP API for PD to manage the configuration

- Testing
  - [ ] Add upgrade tests

**Teachability, Documentation, Adoption, Migration Strategy:**

Proposal: https://github.com/pingcap/tidb/pull/13660
