### ISSUE TITLE
Call For Participation: SIG-Exec 2020/Q1 Plan

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#14541]
All issues are open and welcoming to contributors. You can join **#sig-exec** on [tidb community slack](https://pingcap.com/tidbslack/) to discuss and get help from someone.

## Objective 1: Improve the performance of the execution engine

Improve the performance of TiDB’s execution engine by optimizing some executors.

### KR 1: Improve the performance of the Window, Aggregate, Join, Sort executors
| issue                                                                                           | difficulty | assignee             | PRs    |
|-------------------------------------------------------------------------------------------------|------------|----------------------|--------|
| <ul><li> [ ] #12967 Optimize the Window executor by using sliding windows            </li></ul> | medium     | @mmyj, @SunRunAway   | N/A    |
| <ul><li> [x] #12966 Optimize the Window executor by using multi-thread hash grouping </li></ul> | medium     | @pingyu, @SunRunAway | #14238 |
| <ul><li> [x] #14216 Vectorized Merge Join                                            </li></ul> | medium     | @catror, @qw4990     | #14458 |
| <ul><li> [ ] #14217 Design vectorized aggregation functions                          </li></ul> | hard       | **help wanted**      | N/A    |
| <ul><li> [ ] #14441 Implement Parallel Sort-Merge Join                               </li></ul> | hard       | **help wanted**      | N/A    |
| <ul><li> [ ] #14466 Refine the implementation of `HashJoinExecution`                 </li></ul> | medium     | **help wanted**      | N/A    |
| <ul><li> [ ] #TODO  Investigate Parallel Hash Join                                   </li></ul> | medium       | **help wanted**      | N/A    |
| <ul><li> [ ] #14417 Implement Parallel Sort                                          </li></ul> | medium     | @wshwsh12       | N/A    |

### KR 2: Reduce the memory usage of Insert/Update executors

reduce 200% memory usage for 500,000 rows * 8 bigint columns.

| issue                                                                           | difficulty | assignee        | PRs    |
|---------------------------------------------------------------------------------|------------|-----------------|--------|
| <ul><li> [ ] #14355 Reduce the memory usage of the `Insert` executor </li></ul> | medium     | @b41sh          | #14568 |
| <ul><li> [ ] #14355 Reduce the memory usage of the `Update` executor </li></ul> | medium     | **help wanted** | N/A    |

### KR 3: Implement inline projection for executors

See https://github.com/pingcap/tidb/issues/14428

- Support inline projection in **_planner_** @SunRunAway  #14683 
- Implement inline projection for **_Sort_** and **_TopN_**
- Join
  - Implement inline projection for **_Hash Join_** @SunRunAway #14682
  - Implement inline projection for **_Merge Join_**
  - Implement inline projection for **_Index Merge Join_**
  - Implement inline projection for **_Index Hash Join_** 
- Implement inline projection for **_Apply_**
- Implement inline projection **_Selection_**
- Implement inline projection for **_Limit_**

### KR 1: Improve the JSON functionality

All issues are listed in #14486, here is a task list. In case you need help, please contact @qw4990

| issue                                                                                                                                   | difficulty | assignee        | PRs    |
|-----------------------------------------------------------------------------------------------------------------------------------------|------------|-----------------|--------|
| <ul><li> [ ] #7546   Implement the unsupported JSON function `JSON_MERGE_PATCH`                                              </li></ul> | medium     | **help wanted** | N/A    |
| <ul><li> [ ] #7546   Implement the unsupported JSON function `JSON_PRETTY`                                                   </li></ul> | medium     | **help wanted** | N/A    |
| <ul><li> [ ] #7623   Implement the unsupported JSON function `JSON_ARRAYAGG`                                                 </li></ul> | medium     | **help wanted** | N/A    |
| <ul><li> [ ] #7623   Implement the unsupported JSON function `JSON_OBJECTAGG`                                                </li></ul> | medium     | @hg2990656 | #11154 |
| <ul><li> [ ] #14488  Implement the unsupported JSON function `JSON_STORAGE_SIZE `                                            </li></ul> | medium     | **help wanted** | N/A    |
| <ul><li> [ ] #12178  `JSON_EXTRACT` gets wrong decimal when insert into table                                                </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #13722  Invalid JSON value for CAST to DATE/TIME/DATETIME/TIMESTAMP from column json_extract for virtual column </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #9995   `JSON_OBJECT` handle long strings wrongly                                                               </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #10460  Compare json objects wrongly                                                                            </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #10461  Compare json floats wrongly; difficulty                                                                 </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #11386  Loss accuracy when inserting json records                                                               </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #9988   Casting times to json cannot be compatible with MySQL                                                   </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #10390  Casting strings to json cannot be compatible with MySQL                                                 </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #12233  JSON_EXTRACT fails to cast as bool                                                                      </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #11489  Convert json to uint different from mysql                                                               </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #10467  Incorrect GROUP BY for JSON values                                                                      </li></ul> | easy       | **help wanted** | N/A    |
| <ul><li> [ ] #13710  Incorrect results when processing `JSON_EXTRACT(...) IN (...)`                                          </li></ul> | easy       | **help wanted** | N/A    |

### KR 2: #14332 Refine the implementation of `IndexMergeReader`

| issue                                                                                               | difficulty | assignee                      | PRs    |
|-----------------------------------------------------------------------------------------------------|------------|-------------------------------|--------|
| <ul><li> [ ] #14333 Refine the IPC between `partialWorker` and `indexMergeProcessWorker` </li></ul> | easy       | @sduzh                        | #14381 |
| <ul><li> [ ] #14334 make RuntimeStats and feedback correct for IndexMergeReaderExecutor  </li></ul> | easy       | **help wanted**               | N/A    |
| <ul><li> [ ] #14335 use `WithRecovery` in IndexMergeReaderExecutor instead of `recover`  </li></ul> | easy       | @SeaRise                      | #14550 |
| <ul><li> [ ] #14336 start workers in Next instead of Open for IndexMergeReaderExecutor   </li></ul> | easy       | **help wanted**               | N/A    |
| <ul><li> [ ] #14337 reuse the result chk in IndexMergeReaderExecutor                     </li></ul> | easy       | **help wanted**               | N/A    |
| <ul><li> [ ] #14338 send a batch of handles in indexMergeTableScanWorker                 </li></ul> | easy       | **help wanted**               | N/A    |
| <ul><li> [ ] #TODO Produce an article to introduce the `IndexMergeReader`                </li></ul> | easy       | @hailanwhu, @sduzh, @XuHuaiyu | N/A    |

### KR 3: Fix null in subquery problem
- [ ] [#13743](https://github.com/pingcap/tidb/issues/13743) push down conditions error
- [ ] [#13749](https://github.com/pingcap/tidb/issues/13749) correlated select items should return NULL if the outer table is empty
- [ ] [#13389](https://github.com/pingcap/tidb/issues/13389) in subquery does not distinguish NULL
- [ ] [#8844](https://github.com/pingcap/tidb/issues/8844) Semi Join should be NULL-Aware
- [ ] [#12065](https://github.com/pingcap/tidb/issues/12065) wrong result and panic when joining dual table
- [ ] [#12074](https://github.com/pingcap/tidb/issues/12074) anti semi join error
- [ ] https://github.com/pingcap/tidb/issues/13972 improve in subquery performance

### KR 4: #14392 Improve memory management for executors [project/31](https://github.com/pingcap/tidb/projects/31)

| issue                                                                                                                  | difficulty | assignee        | PRs            |
|------------------------------------------------------------------------------------------------------------------------|------------|-----------------|----------------|
| <ul><li> [ ] #14358 Proposal: a better way to track memory for chunks                                       </li></ul> | medium     | **help wanted** | N/A            |
| <ul><li> [ ] #TODO Use external storage for Index Merge Join                                                </li></ul> | hard       | **help wanted** | N/A            |
| <ul><li> [ ]  #14675 implement grace hash join for Hash Join to avoid OOM of hash table                                                      </li></ul> | hard       | **help wanted** | N/A            |
| <ul><li> [ ] #14705 make the memory tracing in `HashAggExec` more accurate                                               </li></ul> | medium       | **help wanted** | N/A            |
| <ul><li> [ ] #14413  Use external storage for Hash Aggregation                                               </li></ul> | hard       | **help wanted** | N/A            |
| <ul><li> [ ] #14395 Use external storage for Distinct                                               </li></ul> | hard       | **help wanted** | N/A            |
| <ul><li> [x] #12431 Use external storage for Sort                                                           </li></ul> | medium     | @wshwsh12       | #13718, #14279 |
| <ul><li> [ ] #TODO Use external storage for Window Function                                                 </li></ul> | medium     | **help wanted** | N/A            |
| <ul><li> [ ] #TODO Compare between row-based and vectorized external storage format for different executors </li></ul> | hard       | **help wanted** | N/A            |

### KR 5: Investigate and implement Adaptive Join

- [ ] [#14408](https://github.com/pingcap/tidb/issues/14408) Investigate and propose Adaptive Join, difficulty: hard, assignee: **help wanted**

### KR 6: Support the Partition memory table

- [x] [#13905](https://github.com/pingcap/tidb/issues/13905) Support the INFORMATHIN_SCHEMA. Partition memory table like MySQL. difficulty: medium, assignee: @tangwz, @qw4990, deadline: 2020/02/10; https://github.com/pingcap/tidb/pull/14347 

### KR 1: Support `SELECT INTO OUTFILE` syntax

- [ ] [#11112](https://github.com/pingcap/tidb/issues/11112) Support `SELECT INTO OUTFILE`. difficulty: medium, assignee: @tsthght, @qw4990, deadline: 2020/02/31
- [ ] [#722](https://github.com/pingcap/parser/issues/722) Let our parser support the `SELECT INTO OUTFILE` syntax. difficulty: medium, assignee: @tsthght, @qw4990, deadline: 2020/03/31

### KR 2: Support to load configs from PD and update dynamically
- [ ] [#13660](https://github.com/pingcap/tidb/pull/13660) Support to load configs from PD and update dynamically. difficulty: hard, assignee: @qw4990, deadline: 2020/01/31; https://github.com/pingcap/tidb/pull/14303, https://github.com/pingcap/tidb/pull/13660

**Comment by qw4990** [comment]
@SunRunAway Please add this https://github.com/pingcap/tidb/issues/14705 to the list at your convenience.

**Comment by zz-jason** [comment]
close due to stale.
