### ISSUE TITLE
Call For Participation: SIG-DDL 2020/Q1 Plan 

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#14800]
We have listed the 2020 development plans for DDL and parsers.
If you are interested in some features,  you can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with others.

Some of these issues are still in their early stages and any discussion is welcome.
We are waiting for you!

### DDL KRs：
 - [x] Auto_increment is not compatible with MySQL #13032 Difficulty: easy assignee: @Rustin-Liu
 - [x] Fix "drop table if exists" no warning info #7867 Difficulty: easy 
 - [ ] Support temporary table #1248
 - [ ] Support ascending or descending index #2519 
 - [x] Support invisible Indexes #9246
 - [ ] Increase the priority of DDL in bootstrap #7024
 - [ ] Dropping a column isn't reducing the disk size #8673
#### Support the operation of adding multi-schema change in one statement #14766
 - [ ] Support multiple table rename (swap table use case) #9384 
 - [x] Support the operation of adding multi-columns #5092
 - [ ] ropping column with index covered isn't fully compatible with mysql  #3364
 - [ ] Support the operation of dropping multi-indexes in one statement #14765
### Parser KRs：
 - [x] Support syntax: SELECT ... INTO OUTFILE pingcap/parser#722 Difficulty: easy 
 - [x] Support syntax: AND NO CHAIN NO RELEASE pingcap/parser#649 Difficulty: easy 
 - [x] Support syntax: ANALYZE TABLE .. UPDATE HISTOGRAM pingcap/parser#361 Difficulty: easy 
 - [ ] Support WHERE / GROUP BY clauses in a SELECT statement without a FROM table pingcap/parser#115 Difficulty: easy 
 - [ ] Support syntax: hex & bit literals follows UNDERSCORE_CHARSET pingcap/parser#451 Difficulty: easy 
 - [ ] Support syntax: CTEs pingcap/parser#289

### DDL KRs：
 - [ ] Partition name is not quoted in the output of "SHOW CREATE TABLE" command  assignee: @Rustin-Liu
 - [ ] The "varchar" type column flags are not compatible with MySQL #13992
 - [ ] After executing "modify column", its flag has changed #11850 Difficulty: easy
 - [x] Should not add an index of length 0 to columns of type Blob, text, etc #11049 Difficulty: easy

### DDL KRs：
 - [ ] Verify that the DDL leases of all TiDBs in the cluster are consistent #14760 Difficulty: easy
 - [ ] Improve the processing speed of general DDL jobs #14770
 - [ ] Improve the performance of `CREATE INDEX` statement #12963
 - [ ] Migrate the infoschema's retrieving data logic for sys table to executor #14828. There are some other func of retrieving data in infoschema/tables.go ：
               dataForTables()
               dataForIndexes()
               dataForColumns()
               dataForStatistics()
               ...
### Parser KRs：
 - [ ] Add incompatible syntax error or warning pingcap/parser#598 Difficulty: easy
 - [ ] Fix static check pingcap/parser#714 Difficulty: easy

**Comment by Rustin-Liu** [comment]
pick up #11049 .

**Comment by Rustin-Liu** [comment]
pick up #13992 and #11850

**Comment by Rustin-Liu** [comment]
puck up #7867
@zimulala Fixed, it seems CI broken because my code changes.  PTAL~

**Comment by zimulala** [comment]
@Rustin-Liu 
OK, I'll see it later.

**Comment by Deardrops** [comment]
pick up Support invisible Indexes #9246

**Comment by chanme** [comment]
pick up #14765

**Comment by wangggong** [comment]
I'll pickup pingcap/parser#925 & pingcap/parser#451. Thx.
