### ISSUE TITLE
UCP: improve UT coverage of package `bindinfo`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#15636]
## Description

As the title said, this task is aimed to improve the unit test coverage of package `bindinfo`. You can generate the coverage report and view it in browser with the following commands:

```sh
cd bindinfo
go test -coverprofile=coverage.out # runs the unit test, writes the coverage profile to coverage.out
go tool cover -html=coverage.out   # displays the coverage report in your browser
```

The following codes should be covered:

- [ ] [bindinfo/handle.go#L184](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L184)
- [ ] [bindinfo/handle.go#L202](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L202)
- [ ] [bindinfo/handle.go#L264](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L264)
- [ ] [bindinfo/handle.go#L319](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L319)
- [ ] [bindinfo/handle.go#L592](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L592)
- [ ] [bindinfo/handle.go#L598](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L598)
- [ ] [bindinfo/handle.go#L706](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L706)
- [ ] [bindinfo/handle.go#L756](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/bindinfo/handle.go#L756)

For those error handle branches, you can use [failpoint](https://github.com/pingcap/failpoint) to generate whatever error you want in the test case.

## Score

* 200

## Mentor(s)

* @winoros  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* TiDB SQL Plan Binding

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by vraj9845** [comment]
Hi, would like to try solving this

**Comment by tisonkun** [comment]
closed as UCP end and codebase changes a lot. We may later give a report on the nightly master and see how to improve UT coverage.
