### ISSUE TITLE
intuitively observe whether a SQL used session or global binding

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#16425]
## Description

https://github.com/pingcap/tidb/issues/16127 suggests adding additional information to indicate that a query hit the plan cache.

SQL Plan Binding may also need the same improvement: how to intuitively observe whether a SQL used the session or global level binding?

For now, users have to check whether the execution plan is matched with the hints in the binding. But this method requires the user to be very similar to the optimizer and SQL hint behaviors.

Considered that the binding creator and the binding user might not the same person. For example, a binding creator may be the database administrator while a user may be the application developer.

Like plan cache, it's better to display this information in:

- [x] Grafana monitor, we already have
- [ ] statement summary table
- [ ] slow log
- [ ] a session variable like `@@last_plan_from_baselines` to indicate whether the last executed statement used the plan specified by SPM plan baselines.

**Comment by zz-jason** [comment]
@eurekaka, @lzmhhh123 PTAL
