### ISSUE TITLE
Add more information in slow logs to help analyze slow queries

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#17557]
## Development Task
Now information in slow logs(or `slow-query-table`) is not enough to analyze slow queries.
After discussing, we should add these useful information into it:
- [x] 1. time-consuming in the parse phase
- [x] 2. time-consuming for compiling the query
- [x] 3. time-consuming for rewriting the query (#17569)
- [x] 4. time-consuming for optimizing the query (#17869)
- [x] 5. time-consuming to wait for TSO (#17869)
- [x] 6. detailed execution information (like results of `explain analyze`)(#15008)(#17573)
- [x] 7. if this query hits the plan cache(#16197)
- [x] 8. if there are subqueries processed in the compile phase (#17569)
- [ ] 9. support [`ScanDetailV2`](https://github.com/pingcap/kvproto/pull/600)
- [x] 10. if this query use disk(#16883)

**Comment by SunRunAway** [comment]
Should statement summary be invovled?

**Comment by qw4990** [comment]
Since https://github.com/pingcap/kvproto/pull/600 is not supported by TiKV, it is no use to support it on TiKV now, so we decide to close this issue now and support it after TiKV supporting it.

**Comment by breeswish** [comment]
> Since [pingcap/kvproto#600](https://github.com/pingcap/kvproto/pull/600) is not supported by TiKV, it is no use to support it on TiKV now, so we decide to close this issue now and support it after TiKV supporting it.

@qw4990  There is a PR for it https://github.com/tikv/tikv/pull/7563 Maybe we can drive this PR now.

**Comment by breeswish** [comment]
@qw4990 Hi, are these new slow log fields available in v4.0 branch?
