### ISSUE TITLE
Partition table improvement

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18016]
### Description
We want partition table have better performance than before. The current plan is pruning partition table in build physical plan phase rather than in optimize logical plan phase, and replace statistic in each partition into a whole table statistic information. This two step will reduce the CPU use in partition table. Partition pruning algorithm will also be improved, support pruning more condition, including `in` and `or` for hash partition.

This project containing following tasks:  

- [ ] P0: [#18546](https://github.com/pingcap/tidb/issues/18546) Implement `PartitionTableReader` to support pruning during execute stage
- [ ] P0: [#18548](https://github.com/pingcap/tidb/issues/18548) Improve partition pruning algorithm to support more operator
- [ ] P0: [#18551](https://github.com/pingcap/tidb/issues/18551) Implement table level statistic and index selection to support move pruning to execute stage and reduce performance degrade when cluster has many partitions
- [ ] Testing: compare the new partition table with old one using TPC-C and sysbench workload to verify performance improving.

**Progress Tracking**: https://github.com/pingcap/tidb/projects/52#card-41891412

### Category
Performance & Stability

### Value
Improve system performance & support more operation on the partition table

### Time

GanttProgress: 96%
GanttStart: 2020-07-15
GanttDue: 2020-10-20

**Comment by jackysp** [comment]
PTAL @nolouch

**Comment by qw4990** [comment]
Close it since it is duplicated with https://github.com/pingcap/tidb/issues/24150.
