### ISSUE TITLE
Reduce latency jitter caused by the balance

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18014]
### Description
Reduce latency jitter caused by the scheduling strategy and region distribution change.

### Category
Stability

### Task

- [ ]  reduce the unnecessary  balance region operator caused by the space used ratio
- [ ]  reduce the unnecessary balance caused by the empty region
- [ ]  reduce the unnecessary balance leader

### Value
Improve system stability.

### Time

GanttStart: 2020-10-30
GanttDue: 2020-11-28
GanttProgress: 15%

**Comment by nolouch** [comment]
duplicated with https://github.com/pingcap/tidb/issues/18012
