### ISSUE TITLE
Optimize transaction commits to avoid them failed caused by DDL execution

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18098]
### Description
Optimized the pessimistic transaction model when the DDL and DML were executed at the same time, the system error problem, improved the stability of the system

### Category
Usability

### Value
In the database pessimistic locking mode, the execution of DDL will affect the execution of DML, and the execution of DML transactions will fail. When it fails, it will output "mode has changed" or "table does not exist" error message, but DDL truncates the table/deletes. The impact of the table is minimal.

We expect that DDL execution will not affect the DML transaction execution and improve the ease of use of the system. The recommended solution is to automatically input the DML and DDL statements that are being executed when the error is found. At the same time, after waiting for a period of time, if the retry is still unsuccessful, then output the error message or Must block execution. Please pay attention to maintain compatibility with tools such as pt-online when implementing this solution.

### Task List

- [ ] ADD/DROP Columns doesn't affect transaction.
- [ ] ADD/DROP Indexes doesn't affect transaction.
- [ ] Change/Modify Columns doesn't affect transaction.

### Workload Estimation
30

### Time

GanttStart: 2020-07-01
GanttDue: 2020-09-04
GanttProgress: 100%

**Comment by cfzjywxk** [comment]
Project link https://github.com/pingcap/tidb/projects/50

**Comment by zz-jason** [comment]
close due to the project is finished.
