### ISSUE TITLE
Improved Cross-Region deployment features

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#18273]
### Description

Deploy a cluster across multiple geo regions. Schedule the data to the AZ/region near the workload, like Google Spanner.

We need to reduce query latency by reducing cross-region data access. The applications deployed in a certain region may only read/write the data related to that region. So for better performance, the basic idea is to put the related data near the application (data locality). [`Placement Rules`](https://docs.pingcap.com/tidb/stable/configure-placement-rules#placement-rules) is a powerful tool provided by PD. We can use it to place all(or at least the majority) replicas of a table/partition in a specific region. This could mitigate the cross-region network round-trip for both read and write operations.

Besides the data access, another thing we should consider is the transaction timestamp allocation (TSO). For now, it's allocated by the PD leader only. So for the transactions that occur not in the same region with the PD leader, there is still one cross-region round-trip to get the transaction timestamp. We need to figure out a way to allocate transaction timestamps from PD followers. In this way, we can mitigate the cross-region network round-trip for TSO allocation.

## Task List

**Note:** Each of the following big tasks is composed of lots of small tasks, please click on the task URL to get more detail of each big task.

- [x] P0: https://github.com/pingcap/tidb/issues/18030 Config Placement Rules of Data by SQL Statements (Partition Table)
- [x] P0: https://github.com/pingcap/tidb/issues/18253 Support Regional/Global Linearizability Consistency
	- [x] P0: https://github.com/tikv/pd/issues/2759 Support Regional and Global TSO Allocator in Cross-Region Deployment
	- [x] P0: https://github.com/pingcap/tidb/issues/20448 Support Regional and Global Transaction in Cross-Region Deployment
- [x] P1: https://github.com/pingcap/tidb/issues/18033 Read Local Replica to Reduce Latency in Cross-Region Deployment
	- [x] P0: https://github.com/pingcap/tidb/issues/21094 Support timestamp bounded read-only transactions on data replicas

## Technical Design Docs

- https://github.com/pingcap/tidb/pull/18199 Config the placement of data through SQL
- [Local/Global Transaction in Cross-Region Deployment (Chinese)](https://docs.google.com/document/d/1t4D2M5W0dqduNTey1aTute4umuEQrKazU-ipSwFAaLM/edit)
- Propoasl: [Follower to serve local(stale) read](https://docs.google.com/document/d/1ZORyeNAl-lWydU3mUIRMgRTcFKE5IpR2u0tOAyNq89k/edit?pli=1#heading=h.qn6s8mxylwbg) (In Chinese)

## Progress Tracking

- Define the placement of data by SQL statements("Geo Partition") https://github.com/pingcap/tidb/projects/49
- **Weekly Report**: [Cross-Region Deployment & GEO Partition](https://docs.google.com/document/d/1onmkXO_POhcPSq4X_UtCaLGZxuZFWkAIjft7nHTEhug/edit#), which contains the progress of the whole project:
	- Config Placement Rules by SQL
	- Support Regional and Global TSO Allocator in Cross-Region Deployment
	- Support Regional and Global Transaction in Cross-Region Deployment
	- Read Local Replica to Reduce Latency in Cross-Region Deployment

## Join Us

- **Slack**: [#sig-scheduling](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE) in the TiDB-Community Slack Workspace

**Comment by zz-jason** [comment]
Some questions about **Geo-Partition**:

- We planned to support geo-partition on the partition table. But at present, TiDB only supports hash and range partition. Is it enough for applications to map data into the different partitions and further map specific partitions to different Region/Availability Zone(AZ)?

- If the applications require to join two tables, one is the geo-partitioned table, another is a normal table. Or if the applications just need to query another non-partition table. In these scenarios, We may need to figure out a way to replicate the normal table and place each replication to each Region/AZ to save the query latency.

**Comment by zz-jason** [comment]
In order to improve the query performance on a Region or AZ, we'd better improve the partition pruning algorithm to prune un-related partition as many as possible. IMO https://github.com/pingcap/tidb/issues/17474 and https://github.com/pingcap/tidb/issues/18016 are also important in cross-region workloads.
