### ISSUE TITLE
Support Changing Column Type in the TiDB Side

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18283]
### Description

Support changing column types.

### Category

Feature

### Value

* Changing column type is a basic function of the database, many inconveniences are brought to our users and DBAs from TiDB without full support.
* The user experience of syncing data from MySQL to TiDB with DM is usually very poor, lot's of column type changing DDL statements needed to be specifically handled.

### Task List
- [x] P0: Add the proposal of changing column types
- [x] P0: #19116 Supports transitions between the same types, including unsigned transitions
- [x] P0: #19939 Support type conversion between different types
- [x] P0: #19923 Support display the process of some DDL operations
