### ISSUE TITLE
Support direct write into TiFlash without going through TiKV

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tidb#18300]
**Description**
Support direct write into TiFlash without TiKV replica.

**Category**
Feature

**Value**
Enable a lot more pure columnar format oriented scenarios without bothering storing as row format first.

**Comment by zanmato1984** [comment]
Related project: https://github.com/pingcap/tics/projects/15

**Comment by zanmato1984** [comment]
**Description**
Support direct write into TiFlash without TiKV replica.

**Category**
Feature

**Value**
Enable a lot more pure columnar format oriented scenarios without bothering storing as row format first.

**Task List**
* [ ] Study in what form the final product will be delivered: 
  * [ ] Upstream being TiDB or other db?
  * [ ] Any ecosystem tools to involve? I.e. DM? Lightning?
  * [ ] Is a minimal TiKV required? At what resource requirement? I.e. hardware? latency/throughput?
* [ ] Study the feasibility of TiFlash being Raft leader to accept direct write:
  * [*] Any PD replacement rule changes required? Yes.
  * [ ] Use TiFlash proxy VS. TiKV Raft layer + engine trait?
  * [ ] TiFlash needing to be follower or just learner?
* [ ] Performance in terms of transaction and consistency consideration due to properties of TiFlash columnar store:
  * [ ] Percolator VS. single row transaction (1PC)?
  * [ ] Strong consistency VS. eventual consistency?
  * [ ] Update/delete needed?
  * [ ] Latency & throughput requirements?
  * [ ] Batch write?
  * [ ] TiDB SQL statement customization?
* [ ] Minimal viable product (MVP).

**Progress Tracking**
[Project Link](https://github.com/pingcap/tics/projects/15)

**Time**

GanttStart: 2020-07-01
GanttDue: 2020-12-31

**Comment by scsldb** [comment]
Reason for reprioritization: there are more important development tasks at hand.
