### ISSUE TITLE
Support Auto-Scaling on DBaaS

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#18374]
### Description

Make Cloud TiDB elastic scalability.

### Category

Feature

### Task List

-  [PD](https://github.com/tikv/pd/projects/12)
    - [x] https://github.com/tikv/pd/issues/2621  Introduce the auto scaling API
    - [x] https://github.com/tikv/pd/issues/2624  Support get cluster metrics from Promethues 
    - [x] https://github.com/tikv/pd/issues/2744 Support getting scaled component group
    - [x] https://github.com/tikv/pd/issues/2744 Migrate the existed calculation framework from operator to PD

-  [TiDB Operator](https://github.com/pingcap/tidb-operator/projects/5)
    - [x] https://github.com/pingcap/tidb-operator/issues/2909 Support Storage Auto-scaling for TiKV
    - [x] https://github.com/pingcap/tidb-operator/issues/3181 Support TiDB labels configuration
    - [x] https://github.com/pingcap/tidb-operator/issues/3156 Update CRD for tidbautoscaler
    - [x] https://github.com/tikv/pd/issues/2744 Migrate the existed calculation framework from operator to PD
    - [ ] https://github.com/pingcap/tidb-operator/issues/3159 Sync tidbautoscaler with PD API

-  TiDB Cloud
    - [ ] The Design of autoscaling ability in TiDB Cloud

### Progress Tracking
    
- https://github.com/orgs/pingcap/projects/32

### Time

GanttStart: 2020-07-04
GanttDue: 2020-11-28
GanttProgress: 60%

### Weekly report
https://docs.google.com/document/d/11c2_qNUg38rCB-ykSS9TiTq2QhgfYiQyKXkW_tTG6s4/edit#

**Comment by nolouch** [comment]
closed it firstly. maybe we can reopen it in the future.
