### ISSUE TITLE
Easier discover performance issues and diagnose causes (Stage 1)

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#18867]
Simplify the process of discovering performance issues, as well as diagnosing their root causes.

As the first stage, we focus on these specific root causes:

1. hot spot
2. disk jitter
3. GC or tombstone data
4. unnecesaary large data scan (there was a better plan)
5. transaction conflict
6. small resource capacity (thread pool full)

We will do the following task items (the list is growing and the task item may not be TiDB only):

- [ ] [Visualize regions and replicas](https://github.com/pingcap-incubator/tidb-dashboard/issues/686), to reveal some schedule related unbalance.
- [ ] [Reveal statement directly in KeyViz](https://github.com/pingcap-incubator/tidb-dashboard/issues/574) so that when user sees hotspots they can go further to know which statement caused such hotspot.
- [ ] Introduce [Timeline tracing](https://github.com/pingcap/tidb/issues/17693) to TiDB and TiKV, to track the execution information of each step of a specific statement (instead of all statements via metrics).
- [ ] Report visible versions and all versions, as long as RocksDB PerfContext from TiKV to TiDB in https://github.com/tikv/tikv/pull/7563 to discover tomestone and block cache related slowness. 
- [ ] Turn on PerfContext for some IO related metrics after https://github.com/facebook/rocksdb/issues/7073 is implemented to know IO cost.
- [ ] Provide more details about the executor information by [improving runtime information collection](https://github.com/pingcap/tidb/issues/18663).
- [ ] Improve runtime information for transactions (especially conflicts).
- [ ] Implement diagnostics rules to automatically discover some kind of hotspot issues.
- [ ] Implement diagnostics rules to automatically discover some SQL statements' plan was de-optimized.
- [ ] Make it more easy to perform and understand diagnostics, including:
  - [x] A [visualization](https://github.com/pingcap/tidb/pull/18272) of relationships of diagnostics report fields
  - [ ] [Refine TiDB Dashboard diagnostics generating page](https://github.com/pingcap-incubator/tidb-dashboard/issues/694), separating diagnostics result and cluster report

Some previous attempts under this scope:
- [x] [Add more information in slow logs to help analyze slow queries](https://github.com/pingcap/tidb/issues/17557)
