### ISSUE TITLE
Supports transitions between the same types, including unsigned transitions

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#19116]
### Description

Partially supports changing the column type.

### Value

* Supports column type conversion that will modify column data.

### Task List
- [x] P0: #19118 Add a framework for column type transformation(no rollback operation is supported yet) and support column type conversion within integer types
    - [x] P0: #19119 Improve the framework for column type transformation mainly supported rollback operation
    - [x] P0: #19501 Improve the framework for column type transformation mainly handled some TODOs
    - [x] P0: #19502 Improve the framework for column type transformation mainly refactor backfillWorker
- [x] P0: #19121 Support conversion between other Numeric types
- [x] P0: #19571 Support conversion between String types
- [x] P0: #19122 Support the transition between Time types
- [x] P0: #19123 Support conversion between JSON types
