### ISSUE TITLE
Call For Participation: add memory trace for all the AggFuncs

### ISSUE THREAD

**Issue by b41sh** [pingcap/tidb#19369]
## Description

This issue is used to track the memory usage of `AggFunc` in `HashAggExec` as discussed in #14705 and #14103.
We need to implement the method of the `AggFunc` interface and return `memDelta` to identify memory usage of each function.

```
type AggFunc interface {
	AllocPartialResult() (pr PartialResult, memDelta int64)
	UpdatePartialResult(sctx sessionctx.Context, rowsInGroup []chunk.Row, pr PartialResult) (memDelta int64, err error)
	MergePartialResult(sctx sessionctx.Context, src, dst PartialResult) (memDelta int64, err error)
}
```

All aggregation functions are shown below, you can choose the ones you are interested in.
Feel free to join us in the [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance) to discuss.

- [x] avg agg functions @b41sh  [18901](https://github.com/pingcap/tidb/pull/18901)
- [x] [bit agg functions](https://github.com/pingcap/tidb/issues/19733) @Lvnszn [19808](https://github.com/pingcap/tidb/pull/19808)
- [x] [count agg functions](https://github.com/pingcap/tidb/issues/19734) @SailerNote [19770](https://github.com/pingcap/tidb/pull/19770)
- [x] count distinct agg functions @b41sh [18901](https://github.com/pingcap/tidb/pull/18901)
- [x] [cume distinct agg functions](https://github.com/pingcap/tidb/issues/19735) @YangKian [19832](https://github.com/pingcap/tidb/pull/19832)
- [x] [first row agg functions](https://github.com/pingcap/tidb/issues/19736) @Howie66 [19757](https://github.com/pingcap/tidb/pull/19757)
- [x] [group concat agg functions](https://github.com/pingcap/tidb/issues/19737) @William0423
- [x] [json object agg functions](https://github.com/pingcap/tidb/issues/19738) @TszKitLo40 https://github.com/pingcap/tidb/pull/19819
- [x] [lead lag agg functions](https://github.com/pingcap/tidb/issues/19739) @blueseason #19966 
- [x] [max min agg functions](https://github.com/pingcap/tidb/issues/19740) @xiaodong-ji [19783](https://github.com/pingcap/tidb/pull/19783)
- [x] [ntile agg functions](https://github.com/pingcap/tidb/issues/19741) @Howie66 [19756](https://github.com/pingcap/tidb/pull/19756)
- [x] [percent rank agg functions](https://github.com/pingcap/tidb/issues/19742) @Patrick0308 [19852](https://github.com/pingcap/tidb/pull/19852)
- [x] [rank agg functions](https://github.com/pingcap/tidb/issues/19743) @TszKitLo40 [19766](https://github.com/pingcap/tidb/pull/19766)
- [x] sum agg functions @mmyj https://github.com/pingcap/tidb/pull/19376
- [x] [value agg functions](https://github.com/pingcap/tidb/issues/19744) @Hunsmore  https://github.com/pingcap/tidb/pull/19811
- [x] [var pop agg functions](https://github.com/pingcap/tidb/issues/19745) @asiafrank [19755](https://github.com/pingcap/tidb/pull/19755)
- [x] [row number agg functions](https://github.com/pingcap/tidb/issues/19746) @asiafrank [19752](https://github.com/pingcap/tidb/pull/19752)

## SIG slack channel
  [sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance-tidb)

## Score 

- 600

## Mentor
* @b41sh

## Recommended Skills

* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by mmyj** [comment]
pick `value agg functions`

**Comment by SailerNote** [comment]
pick `count agg functions`

**Comment by xiaodong-ji** [comment]
pick `max min agg functions`

**Comment by SailerNote** [comment]
pick `count agg functions`

**Comment by xiaodong-ji** [comment]
pick `max min agg functions`

**Comment by SailerNote** [comment]
pick `count agg functions`

**Comment by Howie66** [comment]
pick ntile agg functions

**Comment by TszKitLo40** [comment]
pick up count agg functions

**Comment by XuHuaiyu** [comment]
@SailerNote @TszKitLo40 @Howie66 @asiafrank @xiaodong-ji

We'll create an individual issue for each item in the description, you may pick up the work later.

**Comment by XuHuaiyu** [comment]
@TszKitLo40 @Howie66 @asiafrank @xiaodong-ji
Hi, you can pick up the sub-tasks now.

**Comment by Hunsmore** [comment]
pick value agg functions

**Comment by b41sh** [comment]
@Hunsmore value agg functions have picked up success

**Comment by qw4990** [comment]
Can we close this issue since all tasks have been finished? @b41sh

**Comment by b41sh** [comment]
> Can we close this issue since all tasks have been finished? @b41sh 

yes, we can finish it.

**Comment by SunRunAway** [comment]
@b41sh Could you provide a test report showing that your job work?

We can set up a test environment and run some testing aggregation queries. And the job can be proven by the following two points
1. During the execution of a long-running SQL, we can monitor the heap usage in grafana and the SQL's memory usage in the `show processlist` at the same time. Give a comparison chart to show that the memory statistics shown in `processlist` are close to the memory used by the go language.
2. By setting an appropriate `mem-query-quota`, a query that consumes a lot of memory will eventually be killed.
