### ISSUE TITLE
Support type conversion between different types

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#19939]
### Description

Partially supports changing the column type;
Mainly focus the column type change between different type;

### Value

* Supports column type conversion between different types that will modify column data.

### Task List
- [ ] P0:  Support conversion from Integer types to others
- [ ] P0:  Support conversion from Numeric types to others
- [ ] P0:  Support conversion from String types to others
- [ ] P0:  Support conversion from Time types to others
- [ ] P0:  Support conversion from JSON types to others
- [ ] P0: Support the show the process of these DDL above
