### ISSUE TITLE
Move sysvar validation into SysVar struct

### ISSUE THREAD

**Issue by nullnotnil** [pingcap/tidb#20324]
## Development Task

See [comment here](https://github.com/pingcap/tidb/issues/9381#issuecomment-699029623):

> Refine the sysVar struct to hold min/max/type/validation (anonymous function), and move it out of ValidateSetSystemVar: https://github.com/pingcap/tidb/blob/master/sessionctx/variable/varsutil.go#L326-L327

This will help make sysvars more pluggable, as the validation can be defined in the sysVar definition. Some of the validation can also be simplified by relying on type information.

### Subtasks

* [x] Boolean, Int, Unsigned Types https://github.com/pingcap/tidb/pull/20346
* [x] Float, Enum types https://github.com/pingcap/tidb/pull/20394
* [ ] Custom validation (anonymous function) https://github.com/pingcap/tidb/pull/20521
