### ISSUE TITLE
Local/Global Transaction in Cross-DC Deployment Tasklist

### ISSUE THREAD

**Issue by JmPotato** [pingcap/tidb#20448]
## Development Task

Part of #18253, #20561, and tikv/pd#2759, in order to make TiDB support the Local/Global Transaction in Cross-DC Deployment, which further enables TiDB to support Cross-Region Deployment & Geo-Partition (https://github.com/pingcap/tidb/issues/18273).

* RFC: [Local/Global Transaction in Cross-DC Deployment](https://docs.google.com/document/d/1t4D2M5W0dqduNTey1aTute4umuEQrKazU-ipSwFAaLM/edit#heading=h.6z9fozegycvb) (In Chinese)
* Proposal: #20588 or [Proposal: Support the Local/Global Transaction in Cross-DC Deployment](https://docs.google.com/document/d/1EFulUkrGtva2Nsb-on3Hyji8635tmMZ0jCyMVzPCA9w/edit#)

### Basic Work

- [x] Update the PD Client wrapper to support the new Local/Global TSO generation. #20980 @JmPotato 
- [x]  ~~Introduce the new DC location configuration.~~ @Yisaer
- [x] Add a new `Session` variable `tidb_txn_scope` to dispatch the Local/Global Transactions.  #20721 @Yisaer 
- [x] Dispatch a transaction as local or global. #21353 @JmPotato 

### Data Constraint Check

- [x] Get the Placement Rule from DDL info. #20911 (~1 day) @Yisaer 
- [x] Check the data constraint of a local transaction.  #20827 (~4 days) @Yisaer
- [x] Check partition placement constraints when local transactions read data. #21426 (~4 days)
- [x] Add a middle state in altering placement policies. #21119 (~4 days) @Yisaer 
- [x] Check the scheme version changing. #20809   (~3 days) @Yisaer 
- [x] Check the internal SQL. #20853  (~4 days) @JmPotato 
- [x] Allocate local TSO for other modules. @JmPotato #21452 (~1 day)
- [ ] Resolve the Async Commit/1PC conflicts. （ ref: https://github.com/tikv/sig-transaction/issues/63 ）

### Optional Work

- [ ] Record transaction scopes in statements summary and slow logs. #20774  (~2 days)
- [ ] Provide a session variable to query the last transaction scope. #20775 （~1 day)

**Comment by Yisaer** [comment]
assign "Add a new Session variable tidb_txn_scope to dispatch the Local/Global Transactions."

**Comment by JmPotato** [comment]
assign "Update the PD Client wrapper to support the new Local/Global TSO generation." @JmPotato

**Comment by JmPotato** [comment]
As described in https://github.com/tikv/pd/issues/8802, Local TSO will no longer be generally available. This is because the current microservice TSO implementation can serve as a substitute, and the Local TSO codebase is no longer maintained. As a result, the Local Transaction feature, which depends on Local TSO, will also be discontinued and will not receive further maintenance. I am closing this issue to prevent any further information discrepancies.
