### ISSUE TITLE
Support list (columns) partition table

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#20678]
### feature development

- [x] [P1] Support create list partition table  #20279 
- [x] [P1]  Support DML(insert/update/delete) on list partition table #20279
    - [x] add more test #20635
- [x] [P1]  Support add/drop partition DDL on list partition table #20631 
- [x] [P1]  Support show create table on list partition table #2063
- [x] [P1] Disable list partition by default. #22045
- [ ] [P2]  Support default partition for list (columns) partition table (need discuss first) https://github.com/pingcap/tidb/issues/20679

### Performance optimization

- [x]  [P1]  Implement `partition pruner` for list partition, this is used to speed up query list partition table.  #20740
- [x] [P1]  optimize the `list columns partition pruner` #21383 #21577
- [x] [P1]  optimize the `list partition pruner` performance in huge partitions #21778 #21577
- [ ]  [P2] optimize the `list partition pruner` for range query, such the query condition is `a > 0 and a < 10`  #22144

### Test

- [x] [P1]  Port partition list test from mysql https://github.com/pingcap/tidb-test/pull/1095
- [x] [P1]  Add more unit/integration test and fix the found bug:
  - [x] [P1]  add more ddl test and fix tiny bugs #21398
  - [x] [P1]  add more dml(insert/delete/update/replace) test #21423 
  -  [x] [P1]  create columns partition table failed when contain SQL key word #21574 
  - [x] [P1]  add more test case from QA. #21693
  - [x] [P1]  add test for plan cache for query on list partition #21698
  - [x] [P1]  executor: add auto_random, auto_increment, generated column, global index test for list (columns) partition #21725
- [ ] [P1]  add more test with other component
  - [ ] TiCDC https://github.com/pingcap/ticdc/pull/1229

### Document

- [x] [P1]  english: https://docs.pingcap.com/tidb/stable/partitioned-table#partition-selection
- [x] [P1]  chinese: https://github.com/pingcap/docs-cn/pull/5132

**Comment by shiyuhang0** [comment]
Does list columns with multi-column supports partition pruning?

**Comment by bb7133** [comment]
@crazycs520 @mjonss Could we close this issue now?

**Comment by mjonss** [comment]
List Columns partitioning is GA since v6.5, so closing this.
