### ISSUE TITLE
Support timestamp bounded read-only transactions on data replicas Tasklist

### ISSUE THREAD

**Issue by NingLin-P** [pingcap/tidb#21094]
## Development Task
Timestamp bounded read-only transactions return stale data within a user-provided staleness bound, and can provide better performance than normal read-only transactions:
- Can perform at replicas that don't have the most up-to-date data, so the `ReadIndex` request can be avoided and reduce the network latency cost, especially in cross-region deployment.
- With the specified `staleness`, write-read conflict can be greatly reduced

Issue: https://github.com/pingcap/tidb/issues/19817
Propoasl: [Follower to serve local(stale) read](https://docs.google.com/document/d/1ZORyeNAl-lWydU3mUIRMgRTcFKE5IpR2u0tOAyNq89k/edit?pli=1#heading=h.qn6s8mxylwbg) (In Chinese)

### Basic work
- [x] Support timestamp bounded syntax https://github.com/pingcap/parser/pull/610
- [x] Get the historical timestamp [issues/21522](https://github.com/pingcap/tidb/issues/21522) @Andrewmatilde
- [x] Choose the closest replicas by labels [issues/21540](https://github.com/pingcap/tidb/issues/21540) @Yisaer 
- [x] Add timestamp bounded option to read requests at [kvproto](https://github.com/pingcap/kvproto)

### Timestamp bounded read-only transactions
- [x] Support exact staleness read-only transactions
    - [x] Begin a staleness read-only transaction #21821  @Yisaer 
    - [x] Allocate start timestamps for exact staleness read-only transactions #21717 @Yisaer 
    - [x] Validate statements for read-only transactions #21824 @Yisaer 
    - [x] Replace the WITH Staleness to AS OF clause https://github.com/pingcap/tidb/issues/24291 @JmPotato 

- [x] Support bounded staleness read-only transactions
    - [x] Maintain a zone-level resolved ts  @Yisaer 
    - [x] Get start ts from resolved ts and specified timestamp https://github.com/pingcap/tidb/pull/24328 @JmPotato  
    - [x] Choose replicas by distance @Yisaer 
- [ ] Compatibility with other features
    - [x] Keep compatible with DDL #22427   P1 @xhebox 
    - [x] Option: Keep compatible with prepare https://github.com/pingcap/tidb/issues/24932
    - [x] Keep compatible with plan cache #22470
    - [x] Keep compatible with coprocessor cache #22510
    - [x] Keep compatible with SQL binding and SPM
    - [x] Keep compatible with history read (can replace)
    - [x] Keep compatible with hot read region schedule @Yisaer 
- [x] Errors handling @JmPotato 
    - [x] retry the leader or next peer on error
    - [x] https://github.com/pingcap/tidb/issues/23271 Stale read request may send to a not initialized peer

### Supports `SET TRANSACTION READ ONLY  AS OF `  https://github.com/pingcap/tidb/issues/22765
- [x] Support syntax `SET TRANSACTION READ ONLY  AS OF `  @Yisaer 
- [x] Implement `SET TRANSACTION READ ONLY  AS OF `  https://github.com/pingcap/tidb/pull/24766 @Yisaer 

### Supports Select statement with ASOF https://github.com/pingcap/tidb/issues/24557
- [x] Support syntax `SELECT ... AS OF ..` https://github.com/pingcap/tidb/issues/22765   P1 @nolouch 
- [x] Implement Select .... AS OF syntax to support Stale Read  https://github.com/pingcap/tidb/pull/24613  @nolouch
- [x] Support resolving schema of different tables in different time  @xhebox 
- [x] Use the matching schema for the select statement @xhebox 
- [ ]  Make sure the special `PointGet optimize` with `usemaxts` do not work in stale read
- [ ] Option: Support the multiple staled TS in the one statements

### TiKV
- [ ] Maintain replica's Resolved TS @NingLin-P 
    - [x] Decouple Resolved TS from [component/cdc](https://github.com/tikv/tikv/tree/master/components/cdc) @5kbpers 
    - [x] Forward replica's Resolved TS when the region is inactive https://github.com/tikv/tikv/issues/9384
    - [ ] (optional) Forward Resolved TS when there are ongoing large transactions
    - [ ] (optional) Forward Resolved TS when there are aborted transactions
- [ ] (optional) Maintain replica's Applied TS
    - [ ] Forward replica's Applied TS by applying transactional raft logs
    - [ ] Forward replica's Applied TS when the region is inactive
    - [ ] Keep compatible with [Async Commit](https://github.com/tikv/sig-transaction/blob/master/design/async-commit/README.md)
- [ ] Support handling stale read request on replica
    - [x] Change the replica read process https://github.com/tikv/tikv/issues/9346
    - [ ] Refine the handling of `EpochNotMatch` error 
- [ ] (optional) "1PC" optimization

TODO:
- Add metric

**Comment by 5kbpers** [comment]
For decoupling Resolved TS, may include the following changes:
* Move the `CmdObserver` implementation of `CdcObserver` to `resolved ts` package
* Start a new thread for capturing changes from apply worker, tracking the lock, and redirecting changes to cdc thread
* Provide an interface (through an atomic variable) for getting the current resolved ts

**Comment by nolouch** [comment]
Hi, @sunxiaoguang , Is anyone interested in #21522 and #21540？

**Comment by Yisaer** [comment]
assign `Supports SET TRANSACTION READ ONLY AS OF `

**Comment by JmPotato** [comment]
assign `Errors handling`.

**Comment by tisonkun** [comment]
Hi @NingLin-P ! Is stale read included in v5.1.0?

**Comment by xhebox** [comment]
@tisonkun It is in release-5.1 branch, fixing bugs and testing. But you could try if you like.

**Comment by tisonkun** [comment]
@xhebox thanks!
