### ISSUE TITLE
Provide standalone Go client

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#22513]
@disksing @AndreMouche  @andylokandy 

## Roadmap

[TiKV Client Roadmap](https://docs.google.com/document/d/1Q1DiCVzbOaDaa2RAM83ny7p5Rh9h_ZaIFPhQBwtMe_M/edit)

## Development Task
- [x] Clean up dependencies of store/tikv package on other packages of tidb
- [x] Clean up the logic of tidb calls to store/tikv
- [x] Separate TiDB-specific code in store/tikv
- [x] Reorg `store/tikv` structure
- [x] Move `store/tikv` to `github.com/tikv/client-go`
- [x] Replace TiDB dependency

#### Strategy
- TiDB related: move them out of `store/tikv`
- TiKV related: move them into `store/tikv`
- Small utilities: copy code
- Refer to the structure of https://github.com/tikv/client-go

<details>

> following items are generated by

```bash
grep -r "github.com/pingcap/tidb" store/tikv | grep -v "github.com/pingcap/tidb/store/tikv" | grep -v "failpoint" | awk '{if(NF==3){print $3,$1}else{print $2,$1}}' | grep -v "store/tikv/tests" | sort -u
```

 - [x] "github.com/pingcap/tidb/config" store/tikv/2pc_test.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/2pc.go 
 - [x] "github.com/pingcap/tidb/config" store/tikv/client_batch.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/client_fail_test.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/client_test.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/client.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/coprocessor_cache_test.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/coprocessor_cache.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/kv.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/lock_resolver.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/oracle/oracle.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/prewrite.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/rawkv.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/region_cache.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/region_request_test.go
 - [x] "github.com/pingcap/tidb/config" store/tikv/test_util.go
 - [x] "github.com/pingcap/tidb/ddl/placement" store/tikv/gcworker/gc_worker_test.go
 - [x] "github.com/pingcap/tidb/ddl/placement" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/ddl/placement" store/tikv/region_cache.go
 - [x] "github.com/pingcap/tidb/ddl/util" store/tikv/gcworker/gc_worker_test.go
 - [x] "github.com/pingcap/tidb/ddl/util" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/domain" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/domain" store/tikv/gcworker/gc_worker_test.go
 - [x] "github.com/pingcap/tidb/domain" store/tikv/sql_fail_test.go
 - [x] "github.com/pingcap/tidb/domain/infosync" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/domain/infosync" store/tikv/gcworker/gc_worker_test.go
 - [x] "github.com/pingcap/tidb/domain/infosync" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/errno" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/errno" store/tikv/error.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/1pc_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/2pc_fail_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/2pc_slow_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/2pc_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/2pc.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/async_commit_fail_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/async_commit_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/backoff.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/kv" store/tikv/batch_coprocessor.go 
 - [x] "github.com/pingcap/tidb/kv" store/tikv/binlog.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/client_helper.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/client.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/commit.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/coprocessor_cache_test.go 
 - [x] "github.com/pingcap/tidb/kv" store/tikv/coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/kv" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/kv" store/tikv/delete_range.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/gcworker/gc_worker_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/gcworker/gc_worker.go 
 - [x] "github.com/pingcap/tidb/kv" store/tikv/interface.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/isolation_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/key_ranges_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/key_ranges.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/kv.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/lock_resolver.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/lock_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/mpp.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/pessimistic.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/range_task_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/range_task.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/region_cache_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/region_cache.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/region_request_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/region_request.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/safepoint_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/scan_mock_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/scan_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/scan.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/snapshot_fail_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/snapshot_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/snapshot.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/split_region.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/split_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/store_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/test_probe.go:
 - [x] "github.com/pingcap/tidb/kv" store/tikv/test_util.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/ticlient_slow_test.go:
 - [x] "github.com/pingcap/tidb/kv" store/tikv/ticlient_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/tikvrpc/tikvrpc.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/txn.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/batch_getter.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/memdb_arena.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/memdb_iterator.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/memdb_snapshot.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/memdb_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/memdb.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/mock.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/union_iter.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/union_store_test.go
 - [x] "github.com/pingcap/tidb/kv" store/tikv/unionstore/union_store.go
 - [x] "github.com/pingcap/tidb/meta" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/2pc.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/backoff.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/cleanup.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/client_batch.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/client.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/commit.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/gcworker/gc_worker.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/kv.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/lock_resolver.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/oracle/oracles/pd.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/pessimistic.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/prewrite.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/range_task.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/rawkv.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/region_cache.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/region_request.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/snapshot.go 
 - [x] "github.com/pingcap/tidb/metrics" store/tikv/txn.go 
 - [x] "github.com/pingcap/tidb/privilege" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/session" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/session" store/tikv/gcworker/gc_worker_test.go
 - [x] "github.com/pingcap/tidb/session" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/session" store/tikv/sql_fail_test.go
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/1pc_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/async_commit_fail_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/async_commit_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/region_request.go 
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/scan_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx" store/tikv/txn.go 
 - [x] "github.com/pingcap/tidb/sessionctx/binloginfo" store/tikv/binlog.go
 - [x] "github.com/pingcap/tidb/sessionctx/variable" store/tikv/2pc_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx/variable" store/tikv/gcworker/gc_worker_test.go 
 - [x] "github.com/pingcap/tidb/sessionctx/variable" store/tikv/gcworker/gc_worker.go 
 - [x] "github.com/pingcap/tidb/store/mockoracle" store/tikv/gcworker/gc_worker_test.go 
 - [x] "github.com/pingcap/tidb/store/mockoracle" store/tikv/store_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore" store/tikv/gcworker/gc_worker_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/2pc_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/async_commit_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/delete_range_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/gcworker/gc_worker_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/range_task_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/rawkv_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/cluster" store/tikv/split_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/2pc_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/delete_range_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/gcworker/gc_worker_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/range_task_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/region_cache_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/region_request_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/mocktikv" store/tikv/split_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/unistore" store/tikv/async_commit_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/unistore" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/unistore" store/tikv/prewrite_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/unistore" store/tikv/rawkv_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/unistore" store/tikv/snapshot_fail_test.go 
 - [x] "github.com/pingcap/tidb/store/mockstore/unistore" store/tikv/ticlient_test.go 
 - [x] "github.com/pingcap/tidb/table" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/table/tables" store/tikv/2pc.go
 - [x] "github.com/pingcap/tidb/tablecodec" store/tikv/2pc_test.go
 - [x] "github.com/pingcap/tidb/tablecodec" store/tikv/2pc.go
 - [x] "github.com/pingcap/tidb/tablecodec" store/tikv/scan_test.go
 - [x] "github.com/pingcap/tidb/tablecodec" store/tikv/snapshot.go
 - [x] "github.com/pingcap/tidb/types" store/tikv/2pc.go 
 - [x] "github.com/pingcap/tidb/util" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/util" store/tikv/region_cache.go
 - [x] "github.com/pingcap/tidb/util" store/tikv/split_region.go
 - [x] "github.com/pingcap/tidb/util/admin" store/tikv/gcworker/gc_worker.go
 - [x] "github.com/pingcap/tidb/util/codec" store/tikv/pd_codec.go
 - [x] "github.com/pingcap/tidb/util/codec" store/tikv/ticlient_test.go
 - [x] "github.com/pingcap/tidb/util/dbterror" store/tikv/error.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/2pc.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/backoff.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/client.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/kv.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/lock_resolver.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/region_request.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/snapshot.go
 - [x] "github.com/pingcap/tidb/util/execdetails" store/tikv/txn.go
 - [x] "github.com/pingcap/tidb/util/fastrand" store/tikv/backoff.go 
 - [x] "github.com/pingcap/tidb/util/fastrand" store/tikv/kv.go
 - [x] "github.com/pingcap/tidb/util/israce" store/tikv/2pc_fail_test.go
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/2pc.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/backoff.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/batch_coprocessor.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/cleanup.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/client_batch.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/client.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/commit.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/gcworker/gc_worker.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/kv.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/latch/latch.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/lock_resolver.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/mock_tikv_service_test.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/mpp.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/oracle/oracle.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/oracle/oracles/pd.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/pessimistic.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/prewrite.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/range_task.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/region_cache.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/region_request.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/safepoint.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/scan_test.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/scan.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/snapshot_test.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/snapshot.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/split_region.go 
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/txn.go
 - [x] "github.com/pingcap/tidb/util/logutil" store/tikv/unionstore/union_iter.go
 - [x] "github.com/pingcap/tidb/util/memory" store/tikv/batch_coprocessor.go 
 - [x] "github.com/pingcap/tidb/util/memory" store/tikv/coprocessor.go 
 - [x] "github.com/pingcap/tidb/util/mock" store/tikv/sql_fail_test.go 
 - [x] "github.com/pingcap/tidb/util/rowcodec" store/tikv/2pc.go
 - [x] "github.com/pingcap/tidb/util/rowcodec" store/tikv/scan_test.go
 - [x] "github.com/pingcap/tidb/util/storeutil" store/tikv/region_request_test.go
 - [x] "github.com/pingcap/tidb/util/storeutil" store/tikv/region_request.go
 - [x] "github.com/pingcap/tidb/util/stringutil" store/tikv/split_region.go
 - [x] "github.com/pingcap/tidb/util/testkit" store/tikv/batch_coprocessor_test.go 
 - [x] "github.com/pingcap/tidb/util/testkit" store/tikv/sql_fail_test.go
 - [x] "github.com/pingcap/tidb/util/testleak" store/tikv/unionstore/memdb_test.go
 - [x] "github.com/pingcap/tidb/util/testleak" store/tikv/unionstore/union_store_test.go

</details>

#### Expose failpoints
<details>

- [x] tidb/session/session_test.go:   c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/ErrMockRetryableOnly", `return(true)`), IsNil)
- [x] tidb/executor/executor_test.go: c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/MockScatterRegionTimeout", `return(true)`), IsNil)
- [x] tidb/executor/executor_test.go: c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/MockScatterRegionTimeout", `return(true)`), IsNil)
- [x] tidb/executor/executor_test.go: c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/MockSplitRegionTimeout", `return(true)`), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/PessimisticLockErrWriteConflict", "return"), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/SingleStmtDeadLockRetrySleep", "return"), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/beforeAsyncPessimisticRollback", "sleep(100)"), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/beforePrewrite", "1*sleep(1200)"), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/beforePrewrite", "1*sleep(1000)"), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/beforeSchemaCheck", "return"), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/getTxnStatusDelay", "return"), IsNil)
- [ ] tidb/executor/seqtest/seq_executor_test.go:     c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/handleTaskOnceError", `return(true)`), IsNil)
- [ ] tidb/session/session_fail_test.go:      c.Assert(failpoint.Enable("github.com/pingcap/tidb/session/mockCommitError8942", `return(true)`), IsNil)
- [ ] tidb/session/session_fail_test.go:      c.Assert(failpoint.Enable("github.com/pingcap/tidb/session/mockCommitError", `return(true)`), IsNil)
- [ ] tidb/session/session.go:        failpoint.Inject("mockCommitError", func(val failpoint.Value) {
- [ ] tidb/session/txn.go:    failpoint.Inject("mockCommitError8942", func(val failpoint.Value) {
- [ ] tidb/kv/txn.go:var mockCommitErrorEnable = int64(0)
- [ ] tidb/kv/txn.go: atomic.StoreInt64(&mockCommitErrorEnable, 1)
- [ ] tidb/kv/txn.go: atomic.StoreInt64(&mockCommitErrorEnable, 0)
- [ ] tidb/kv/txn.go: return atomic.LoadInt64(&mockCommitErrorEnable) == 1
- [ ] tidb/ddl/serial_test.go:                        c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/mockCommitError", `return(true)`), IsNil)
- [ ] tidb/ddl/serial_test.go:                        c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/mockCommitError", `return(true)`), IsNil)
- [ ] tidb/session/session_fail_test.go:      c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/mockGetTSErrorInRetry",
- [ ] tidb/executor/executor_test.go: var retry = "github.com/pingcap/tidb/store/tikv/mockRetrySendReqToRegion"
- [ ] tidb/sessionctx/binloginfo/binloginfo_test.go:  c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/mockSyncBinlogCommit", `return(true)`), IsNil)
- [ ] tidb/session/session_test.go:   c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/probeSetVars", `return(true)`), IsNil)
- [ ] tidb/session/session_test.go:   failpoint.Enable("github.com/pingcap/tidb/store/tikv/testRateLimitActionMockConsumeAndAssert", `return(true)`)
- [ ] tidb/session/session_test.go:   failpoint.Enable("github.com/pingcap/tidb/store/tikv/testRateLimitActionMockConsumeAndAssert", `return(true)`)
- [ ] tidb/session/session_test.go:   failpoint.Enable("github.com/pingcap/tidb/store/tikv/testRateLimitActionMockConsumeAndAssert", `return(true)`)
- [ ] tidb/session/session_test.go:   failpoint.Enable("github.com/pingcap/tidb/store/tikv/testRateLimitActionMockWaitMax", `return(true)`)
- [ ] tidb/executor/executor_test.go: failpoint.Enable("github.com/pingcap/tidb/store/tikv/ticase-4169", `return(true)`)
- [ ] tidb/executor/executor_test.go: failpoint.Enable("github.com/pingcap/tidb/store/tikv/ticase-4170", `return(true)`)
- [ ] tidb/executor/executor_test.go: failpoint.Enable("github.com/pingcap/tidb/store/tikv/ticase-4171", `return(true)`)
- [ ] tidb/executor/executor_test.go: c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/tikvStoreRespResult", `return(true)`), IsNil)
- [ ] tidb/session/session_fail_test.go:      c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/tikvStoreSendReqResult", `return("callBackofferHook")`), IsNil)
- [ ] tidb/session/session_fail_test.go:      c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/tikvStoreSendReqResult", `return("requestTiDBStoreError")`), IsNil)
- [ ] tidb/session/pessimistic_test.go:       c.Assert(failpoint.Enable("github.com/pingcap/tidb/store/tikv/txnExpireRetTTL", "return"), IsNil)
- [ ] tidb/session/pessimistic_test.go:               err = failpoint.Enable("github.com/pingcap/tidb/store/tikv/txnNotFoundRetTTL", "return")

</details>

### Clean up the logic of tidb calls to store/tikv
- [x] https://github.com/pingcap/tidb/issues/24302

**Comment by AndreMouche** [comment]
I would like to try to remove `github.com/pingcap/tidb/config` from `store/tikv`

**Comment by aierui** [comment]
Like error code,if unpack it need to write two places?
```
 "github.com/pingcap/tidb/errno" store/tikv/error.go
```

**Comment by disksing** [comment]
@aierui Don't do it like that. I think you can first define plain errors without error code. And then reset the errors in other parts of TiDB.

**Comment by disksing** [comment]
Looks it is intentional. I think for tests we can lower the standard. As for cmd, I'm not so sure.

**Comment by tisonkun** [comment]
I don't see any open issue / pr to this tracking issue. What is the current status of standalone Go Client?

**Comment by disksing** [comment]
Now that the migration is complete, subsequent refinements will be transferred to the client-go project. I will close this issue.
