### ISSUE TITLE
Support enum push down to coprocessor.

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#23619]
## Development Task

Now enum type data can only be calculated on the tidb side. So if a filter condition using enum type data, it can't push down.

We can support enum date calculation in TiKV, and push down the condition to filter data close to storage, to reduce network and computing pressure.

## Task

- [x] Support Enum expression calculation in TiKV https://github.com/tikv/tikv/issues/9066 
- [x] Support Enum aggregate calculation in TiKV https://github.com/tikv/tikv/issues/9066 
- [x] Support Enum type index calculation range and using IndexRangeScan.  https://github.com/pingcap/tidb/pull/22691
- [x] Add an option to control this feature. https://github.com/pingcap/tidb/pull/24685
- [x] Test
  - [x] Use randgen to test Enum aggregate. https://github.com/pingcap/tidb-test/pull/1191 
  - [x] Use randgen to test Enum expression. https://github.com/pingcap/tidb-test/pull/1191
  - [x] Regression existing tests https://github.com/pingcap/tidb-test/pull/1194
- [x] Fix all find bugs.
  - [x] https://github.com/pingcap/tidb/issues/24395  
  - [x] https://github.com/pingcap/tidb/issues/24419 
  - [x] https://github.com/pingcap/tidb/issues/23114
  - [x] https://github.com/pingcap/tidb/issues/24479
  - [x] https://github.com/pingcap/tidb/issues/24494 duplicated
  - [x] https://github.com/pingcap/tidb/issues/24530
  - [x] https://github.com/pingcap/tidb/issues/24543
  - [x] https://github.com/pingcap/tidb/issues/24561
  - [x] https://github.com/pingcap/tidb/issues/24562
  - [x] https://github.com/pingcap/tidb/issues/24576
  - [x] https://github.com/pingcap/tidb/issues/24587 duplicated
  - [x] https://github.com/pingcap/tidb/issues/24473
