### ISSUE TITLE
enhangcement statements_summary

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#24086]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This issue is an epic use to trace related issue:

- [ ] [Record evicted information of statements_summary](https://github.com/pingcap/tidb/issues/23920)
- [ ] [Record all statements information by sum](https://github.com/pingcap/tidb/issues/24083)
- [ ] [Use a better cache strategy for statements_summary](https://github.com/pingcap/tidb/issues/24085)

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
