### ISSUE TITLE
Milestone of Partition Table in Sprint3 (2021/4/19 ~ 2021/6/18)

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#24150]
## Development Task
Development plan:
![image](https://user-images.githubusercontent.com/7499936/118949739-1ee7cd80-b98c-11eb-896d-8f651a527f52.png)

Brief introduction: improve the quality of all experimental features of partition tables, including direct reading, global statistics, list, and column list partition.

All test cases are in [the GA matrix document](https://docs.google.com/document/d/1rjxYcKXT1mwTzVxuY32Tql3o8VaHYca0vUdeHFfHf8k/edit?usp=sharing).

Work items:
- Compatibility of global-stats and stats-ver1 @qw4990 
  - [x] Support FMSketch in TiKV
  - [x] Support FMSketch in MockStore
  - [x] Support using FMSketch to calculate NDV of indexes
  - [x] Add more test cases
- Compatibility of global-stats and fast-analyze @rebelice 
  - [x] Make global-stats support fast-analyze https://github.com/pingcap/tidb/pull/24183
  - [x] Add more unit test cases about global-stats and fast-analyze
- Accuracy test of global-stats @rebelice 
  - [x] Finish the accuracy test of global-stats and generate a report, [the report doc](https://docs.google.com/document/d/17PmRshZJb8XXKXO1XUEZUOuWWGuaFtMp_5sF0rGNuYQ/edit?usp=sharing)
  - [x] Adjust our global-stats merging algorithm according to the test result https://github.com/pingcap/tidb/pull/24370, https://github.com/pingcap/tidb/pull/24183, https://github.com/pingcap/tidb/pull/24453
- Direct reading @qw4990 
  - [x] Support reading partition table for index lookup reader https://github.com/pingcap/tidb/issues/24154, https://github.com/pingcap/tidb/pull/24197
  - [x] Support reading partition table for index merge reader https://github.com/pingcap/tidb/issues/24160, https://github.com/pingcap/tidb/pull/24239
  - [x] Make IndexReaders in the inner side of IndexJoins support direct reading https://github.com/pingcap/tidb/issues/24255, https://github.com/pingcap/tidb/pull/24260
  - [x] Make IndexLookUp in the inner side of IndexJoins support direct reading https://github.com/pingcap/tidb/issues/24256, https://github.com/pingcap/tidb/pull/24261
  - [x] Use `TableReader` directly when accessing TiFlash partition table instead of using `PartitionTableExec` https://github.com/pingcap/tidb/issues/24343 https://github.com/pingcap/tidb/pull/24344
  - [x] Make `UnionScan` support direct reading and remove all code about `PartitionTableExec` https://github.com/pingcap/tidb/issues/24393 https://github.com/pingcap/tidb/pull/24394
- Enhancement:
  - [x] Support PointGet for range/list partition https://github.com/pingcap/tidb/issues/24476 @zhuo-zhi
  - [x] Support BatchGet for range/list partition
- Correctness testing 1: test dynamic pruning and partition related expression calculation @mjonss 
  - [x] Design cases on hash partitions
  - [x] Design cases on range partitions
  - [x] Design cases on list partitions
  - [x] Design cases of operations on partition boundaries
  - [x] Implement cases on hash partitions
  - [x] Implement cases on range partitions
  - [x] Implement cases on list partitions
  - [x] Implement cases of operations on partition boundaries
- Correctness testing 2: test direct reading with other operators @zhuo-zhi 
  - [x] Design cases about `BatchGet` and `PointGet`
  - [x] Design cases about `Order` + `Limit`
  - [x] Design cases about all kinds of Joins, especially `IndexLookUpJoin`
  - [x] Design cases about all kinds of Aggregations 
  - [x] Implement cases about `BatchGet` and `PointGet` for hash partition
  - [x] Implement cases about `BatchGet` and `PointGet` for range partition
  - [x] Implement cases about `Order` + `Limit`
  - [x] Implement cases about all kinds of Joins, especially `IndexLookUpJoin`
  - [x] Implement cases about all kinds of Aggregations
- Correctness testing 3: test direct reading with other features @qw4990 
  - [x] Design cases about Plan Cache
  - [x] Design cases about Global Statistics 
  - [x] Design cases about Global Index
  - [x] Design cases about SQL Bind
  - [x] Design cases about View
  - [x] Design cases about New Collation (Unicode CI and General CI)
  - [x] Design cases about Clustered Index
  - [x] Design cases about DDL Statements, like alter table schema, drop partitions
  - [x] Implement cases about Plan Cache
  - [x] Implement cases about Global Statistics 
  - [x] Implement cases about Global Index
  - [x] Implement cases about SQL Binding
  - [x] Implement cases about View
  - [x] Implement cases about New Collation (Unicode CI and General CI)
  - [x] Implement cases about Clustered Index
  - [x] Implement cases about DDL Statements, like alter table schema, drop partitions
- Correctness testing 4: Randgen testing @rebelice 
  - [x] Modify [clustered-index-rand-gen](https://github.com/PingCAP-QE/clustered-index-rand-test#introduction) to make it support generating queries on partition tables, [the design doc](https://docs.google.com/document/d/1SeetDXFKeNRxAL_9_fqqc2Jx952pfthsz_67tTZnc8E/edit#heading=h.aahq02xdex5m)
  - [x] Add some cases into [clustered-index-rand-gen](https://github.com/PingCAP-QE/clustered-index-rand-test#introduction) to generate testing queries ([an example](https://github.com/pingcap/automated-tests/blob/master/ticases/clustered_index/rand/case.go))
  - [x] Integrate [clustered-index-rand-gen](https://github.com/PingCAP-QE/clustered-index-rand-test#introduction) into [UTF](https://docs.google.com/document/d/1PBc1syJSr88q4eax9wT4k2-haa8xhq4x2spD7zPxt3Y/edit) to run our test cases
- Performance testing: 
  - [x] [Design doc](https://docs.google.com/document/d/1KoPzcU6OIi37ZH0LPzB1DHoMpaeXoytL_1SeMrY_aZI/edit#), IN REVIEW
  - [ ] Finish our perf-test and generate a report
- Scenario testing:
  - [x] [Design doc](https://docs.google.com/document/d/1jVYJ_XtpJtwZ-vw1limaIT6yeMK_eiUdBYkGFidnpEY/edit#heading=h.i0jf30tdd0b0), IN REVIEW
  - [ ] Finish all scenario tests and generate a report
- Bugfix:
  - [x] https://github.com/pingcap/tidb/issues/20372
  - [x] https://github.com/pingcap/tidb/issues/24171
  - [x] https://github.com/pingcap/tidb/issues/24259
  - [x] https://github.com/pingcap/tidb/issues/24307

**Comment by zz-jason** [comment]
we also need to fix the existing bugs, like https://github.com/pingcap/tidb/issues/20372

**Comment by qw4990** [comment]
> we also need to fix the existing bugs, like #20372

OK, I'll go through all existed issues about the partition table add them here later.

**Comment by zz-jason** [comment]
1. for the milestones, another key milestone is to disable static pruning and enable dynamic pruning by default.
2. for tests, I wish to add more compatibility tests:
	- upgrade tidb cluster from 4.0 to the current release, check whether the dynamic pruning works
	- downgrade tidb cluster from the current release to 4.0, check whether the static pruning works

**Comment by rebelice** [comment]
There is bug #24171 here that prevents `fast analyze` from generating global stats. 
(I can't modify the description, so I just comment here

**Comment by zz-jason** [comment]
https://github.com/pingcap/tidb/issues/22408 mentioned that there might be performance and resource issues in backup scenario, please take a look

**Comment by zz-jason** [comment]
we need to add compatibility tests with other components in the cluster, for example: TiFlash MPP, BR, Dumpling, Lightning, Binlog, TiCDC

**Comment by tisonkun** [comment]
Hi @qw4990 ! Is the design of partition table persisted as [this file](https://github.com/pingcap/tidb/blob/dbecb9e74538393906ac844082e60d520d73bacb/docs/design/2018-10-19-table-partition.md)? Or anything should be updated?

**Comment by qw4990** [comment]
> Hi @qw4990 ! Is the design of partition table persisted as [this file](https://github.com/pingcap/tidb/blob/dbecb9e74538393906ac844082e60d520d73bacb/docs/design/2018-10-19-table-partition.md)? Or anything should be updated?

Actually there are many updates after the proposal you mentioned. Here is [a simple doc](https://pingcap.feishu.cn/docs/doccnYdx1puMoF8ne6rjDe9oo1c) that may help you track the current progress. I think we will sort out and update some documents about partition table after finishing this milestone.

**Comment by tisonkun** [comment]
> > Hi @qw4990 ! Is the design of partition table persisted as [this file](https://github.com/pingcap/tidb/blob/dbecb9e74538393906ac844082e60d520d73bacb/docs/design/2018-10-19-table-partition.md)? Or anything should be updated?
> 
> Actually there are many updates after the proposal you mentioned. Here is [a simple doc](https://pingcap.feishu.cn/docs/doccnYdx1puMoF8ne6rjDe9oo1c) that may help you track the current progress. I think we will sort out and update some documents about partition table after finishing this milestone.

Thanks! I'll try to take a look when I stage my current works.

FYI when I refer to this project in our developer discussion forum(https://internals.tidb.io/t/topic/97/2), I said

> It is to final comment period before we make the consensus, and thus we do not trace back to its design document. But both user document and dev document for partition table is required I think. @qw4990

Please confirm whether it is precise and I'll appreciate it if you can reply on the forum topic.
