### ISSUE TITLE
Support temporary table

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#24169]
## Development Task

A temporary table is a special table whose rows data are only temporarily available.

For a global temporary table, the table schema is visible to all the sessions, but the changes into the table are only available within the current transaction, when the transaction commits, all changes to the global temporary table are discarded.

For a local temporary table, it is visible only within the current session, and the table is dropped automatically when the session is closed.

[Tech Design](https://docs.google.com/document/d/1Ub7adXeaAmNhtVyMWQFGOfAVZDELEbfWX2yzdjBrRP4/edit#)

[Weekly Report](https://docs.google.com/document/d/1fUyXVkAJ06X3AIXc7TCu6DSaxS68KeqzH4pDURT1l-0/edit#)

[Proposal](https://github.com/pingcap/tidb/pull/24168)

### Stage 1

DDL @Howie59 

- [x] Grammar change for the global temporary table https://github.com/pingcap/parser/pull/1211
- [x] Ignore table options or report errors for `create table like` https://github.com/pingcap/tidb/pull/25082
- [x] Forbid some table options
  - [x] pre_split_regions https://github.com/pingcap/tidb/pull/24684
  - [x] on commit preserve rows / engine=innodb https://github.com/pingcap/tidb/pull/24723
  - [x] auto_random / shard_row_id_bits https://github.com/pingcap/tidb/pull/24940
  - [x] partition https://github.com/pingcap/tidb/pull/24406
  - [x] foreign key https://github.com/pingcap/tidb/pull/24961
  - [x] virtual column https://github.com/pingcap/tidb/pull/25065
- [x] Fix [show](https://github.com/pingcap/tidb/issues/24752) create [table](https://github.com/pingcap/tidb/issues/24788)  https://github.com/pingcap/tidb/pull/24857
- [x] Add a switch to disable global temporary tables by default https://github.com/pingcap/tidb/pull/25075

DML @tiancaiamao 
- [x] Support write/read to a global temporary table https://github.com/pingcap/tidb/pull/24196
- [x] Allocate autoID from memory https://github.com/pingcap/tidb/pull/24506
- [x] Do not write binlog https://github.com/pingcap/tidb/pull/24570
- [x] Memory size does not exceed `temp_table_size` https://github.com/pingcap/tidb/pull/24827

DQL
- [x] Queries on temporary tables do not fall on TiKV @tiancaiamao 
  - [x] no coprocessor request send to TiKV https://github.com/pingcap/tidb/pull/24769
  - [x] batch point get / point get https://github.com/pingcap/tidb/pull/24804
- [x] Cost estimation https://github.com/pingcap/tidb/pull/25046

Transaction
- [x] Handle schema change during transaction commit https://github.com/pingcap/tidb/pull/24534
- [x] Ignore locks on temporary tables @tiancaiamao 
  - [x] point get / batch point get https://github.com/pingcap/tidb/pull/24540
  - [x] Pessimistic lock https://github.com/pingcap/tidb/pull/24737
- [x] Retry DML on temporary tables https://github.com/pingcap/tidb/pull/24505

Feature compatibility

- [x] Admin check table https://github.com/pingcap/tidb/pull/24501
- [x] Admin checksum table https://github.com/pingcap/tidb/pull/24867
- [x] Show table regions / split table https://github.com/pingcap/tidb/pull/24684
- [x] Stale read https://github.com/pingcap/tidb/pull/25206
- [x] historical read https://github.com/pingcap/tidb/pull/25237
- [x] tablesample https://github.com/pingcap/tidb/pull/25288
- [x] Flashback / recover table https://github.com/pingcap/tidb/pull/24518
- [x] ~~`tidb_constraint_check_in_place` variable~~ (verified, add a test) @tiancaiamao  https://github.com/pingcap/tidb/pull/24784
- [x] Do not support SQL binding https://github.com/pingcap/tidb/pull/25058
- [x] Telemetry https://github.com/pingcap/tidb/pull/24866
- [x] Forbid setting tiflash replicas https://github.com/pingcap/tidb/pull/25036

Tools compatibility @djshow832 

- [x] ~~BR: update TiDB module~~ (already updated)
- [x] TiCDC: recognize temporary tables ~~https://github.com/pingcap/ticdc/pull/1923~~ (already updated)

### Stage 2

DDL

- [x] ~~grammar change for the local temporary table~~ (already done by global temporary table) 
- [x] local temporary table schema definition https://github.com/pingcap/tidb/pull/25518 
- [x] DDL changes for creating a local temporary table  https://github.com/pingcap/tidb/pull/25851
- [x] [`show create table` for a local temporary table](https://github.com/pingcap/tidb/issues/25884)
- [x] [Drop a local temporary table](https://github.com/pingcap/tidb/issues/25885) #26063 
- [x] #26278 
- [x] [Truncate a local temporary table](https://github.com/pingcap/tidb/issues/25886)
- [x] [Dropping a database does not drop local temporary tables](https://github.com/pingcap/tidb/issues/25887)
- [x] [Check other operations and make sure 'alter table' operations raise an error](https://github.com/pingcap/tidb/issues/25888)
- [x] [Check table options behavior same with global table](https://github.com/pingcap/tidb/issues/25889)
- [x] [Create table like](https://github.com/pingcap/tidb/issues/25890)
- [x] #25918 #25983
- [x] #25916 #26091
- [x] #25917 #26087

DML

- [x] #25957 #25958
- [x] #25919
- [x] #26048 #26053 
- [x] #26049
- [x] #26050
- [x] #26051
- [x] #26083
- [x] #25920
- [x] #25921
- [x] #25922
- [x] #25923
- [x] #25926
- [x] #25927
- [x] #25928

Transaction
- [x] Creating and dropping a local temporary table doesn’t cause an implicit  commit https://github.com/pingcap/tidb/pull/25851
- [x] #25931
- [x] #25932
- [x] #25933

Feature compatibility, most should have a same behavior with temporary table

- [x] #25934
- [x] #25935
- [x] #25936
- [x] #25937
- [x] #25938
- [x] #25939
- [x] #25940
- [x] #25941
- [x] #25943
- [x] #25951
- [x] #27422
- [x] #28818

Tests

- [x] #25950

GA

- [x] #28281
- [x] #28346

### Stage 3

- [x] #25942
- [ ] Support spilling to disk for the `MemDB`
- [ ] Support TiKV as a storage engine
- [ ] #25924
- [ ] #25925

**Comment by tisonkun** [comment]
@djshow832 we can possibly use format

- grammar change for the global temporary table https://github.com/pingcap/parser/pull/1211

instead of 

- [grammar change for the global temporary table](https://github.com/pingcap/parser/pull/1211)

and thus we get more info while keep link click magic.

**Comment by tisonkun** [comment]
@tiancaiamao @djshow832 @xhebox is this task finished?
