### ISSUE TITLE
Temporary table roadmap

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#24173]
## Backgroud

Issue https://github.com/pingcap/tidb/issues/24163 requests supporting temporary tables in TiDB.

[Tech Design](https://docs.google.com/document/d/1Ub7adXeaAmNhtVyMWQFGOfAVZDELEbfWX2yzdjBrRP4/edit#)

[Weekly Report](https://docs.google.com/document/d/1fUyXVkAJ06X3AIXc7TCu6DSaxS68KeqzH4pDURT1l-0/edit#)

RFC is WIP.

## Support global temporary tables

This part including supporting global temporary tables.

- [ ] Support creating global temporary tables
- [ ] Support DDL on global temporary tables
- [ ] Support DML on global temporary tables
- [ ] Support DQL on global temporary tables
- [ ] Maintain statistics on global temporary tables

## Support on-disk temporary tables

**Comment by djshow832** [comment]
Duplicate with #24169
