### ISSUE TITLE
Refactor statistics Milestones in 2021/4/18 ~ 2021/6/18

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#24182]
## Development Task

This task is aimed to improve the quality and speed of the current statistics.

Work items:

- Base statistics functionality:
	- [ ] A more stable sampling algorithm. @winoros 
	- [ ] Compatible with correlation calculation @time-and-fate 
	- [ ] Compatible with partition table @xuyifangreeneyes 
	- [ ] Compatible with prefix column index
	- [ ] Compatible with virtual column index
	- [ ] Compatible with fast analyze
- Modify count behavior and the estimation around it. @eurekaka 
	- [ ] Correct its collecting behavior.
	- [ ] A more usable out of range estimation
- Functionality Testing(If unit tests is not enough)
	- [ ] Tests on correlation calcualtion.
	- [ ] Tests on partition table
	- [ ] Tests on prefix column index
	- [ ] Tests on virtual column index
	- [ ] Tests on base type index
- Estimation performance Testing on large datasets
	- [ ] Error rate analysis
	- [ ] Speed/CPU/MEM testing
	- [ ] Impact on the front-end workload
- Clean code base
	- [ ] Multi-col index don't collect histogram
	- [ ] Remove old sampling way if possible.
	- [ ] Other cleaning
- Make sampling way as default once the above things are done.

Next step:
- Introduce extended statistics `The TopN on column groups`
- Maintain the statistics on plan operator.

**Comment by tisonkun** [comment]
Hi @winoros ! Is this issue the same as https://github.com/pingcap/tidb/issues/18065?

I can see you link to #18065 on the [weekly report](https://docs.google.com/document/d/1-U5s4JtP9vsaK0xgT5Exr8lNCztIcRhbNzpqMY_wgew/edit) but the working items linked to this issue.
