### ISSUE TITLE
Meta: Unify Log Library for Golang Projects

### ISSUE THREAD

**Issue by SabaPing** [pingcap/tidb#24190]
`This issues tracking the progress for "Unify Log Library for Golang Projects"
`

### What problem does this PR solve?

The primary goal is to clean up the logging component. TiDB (and other golang projects) depends on two different third part log components, which are logrus and zap. This creates unnecessary complexity. In addition, there are some other logging flaws in code.

### Task Check List

- [x] Write a proposal, https://github.com/pingcap/tidb/pull/24181
- [ ] Refactor TiDB log library, https://github.com/pingcap/tidb/pull/23534
- [ ] Refactor PD log library
- [ ] Refactor BR log library
- [ ] Refactor TiUP log library

### Release note

- No release note.

**Comment by tisonkun** [comment]
Hi @SabaPing , what is the next step you would like to go?

**Comment by JinLingChristopher** [comment]
I would like do this in TiCDC

**Comment by tisonkun** [comment]
@SabaPing BR is merged into TiDB, you can take a look whether we should change something in the plan.

**Comment by SabaPing** [comment]
https://github.com/pingcap/tidb/pull/23534 brought an issue of unwanted GRPC logs.
And it fixed by pr: https://github.com/pingcap/tidb/pull/25454.

**Comment by SabaPing** [comment]
#23534 caused an issue that some slow log file configs not working. This made unexpected disk usage.
https://github.com/pingcap/tidb/issues/25716.

Fixed by pr: https://github.com/pingcap/tidb/pull/27625

**Comment by SabaPing** [comment]
There is a pr that enables runtime logger configuration: [session: add session var to update global logger max days](https://github.com/pingcap/tidb/pull/27595)
