### ISSUE TITLE
Optimize CTE performance

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#25149]
## Description

what's the problem, how to solve it

CTE is just implemented and not fully optimized. We hope that you can help us to optimize the performance of CTE.

## Document Collection

- Proposal doc: TBD
- Weekly report: TBD

## Talent Challenge Program information

- Mentor of this issue: @wjhuang2016 
- Recommended skills: Golang, SQL.
- Estimated Workloads: (2XL, 2 man-months)

## Milestones and action items

Milestone 1: Preparation, Expected finish date: TBD

- [ ] Figure out what optimization can be applied to.
- [ ] Work on a TPC-DS test.

Milestone 2: Implement and test, Expected finish date: TBD

- [ ] Implement the optimization.
- [ ] Test on TPC-DS again, quantify the effect of the optimization.
