### ISSUE TITLE
GBK character set support in TiDB

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#25152]
## Description

For now, tidb only supports few character sets(see [docs](https://docs.pingcap.com/zh/tidb/stable/character-set-and-collation)), while MySQL supports a lot. It is hard for us to add a new character set in tidb so that we need a character framework in tidb.

## Document Collection

- Proposal doc: [character support in tidb](https://docs.google.com/document/d/1SC0spRoNScR8-GwUNJ9ZHAV8zmlkq99Q2PReu88FARs/edit)
- Weekly report: TBD

## Talent Challenge Program information

- Mentor of this issue: @xiongjiwei 
- Recommended skills: go, c++, SQL
- Estimated Workloads: (3 Man-Months)

## Milestones and action items

Milestone 1: get prepared, Expected finish date: TBD

- [ ] get some knowledge about character set in MySQL 
- [ ] review and improve the design doc

Milestone 2: feature available, Expected finish date: TBD

- [ ] finish the coding in tidb and tikv, make `gbk` character can be used

Milestone 3: all test passed, Expected finish date: TBD

- [ ] make random-test support test character set 

Milestone 4: all work done, Expected finish date: TBD

- [ ] finish the proposal and user doc

**Comment by zimulala** [comment]
It's duplicated issue: https://github.com/pingcap/tidb/issues/26812
