### ISSUE TITLE
Bring some tests back online before 2021-06-22

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#25223]
## The following unstable tests should bring online before 2021-06-22
- [ ] testResourceTagSuite.TestResourceGroupTag (#25189) @crazycs520 
- [ ] testSuiteJoin1.TestIndexLookupJoin (#25191) @guo-shaoge 
- [ ] testSuite1.TestAnalyzeIndex (#25188) @qw4990 
- [ ] testSuite1.TestAnalyzeIncremental (#25187) @qw4990   
- [ ] testVectorizeSuite2.TestVectorizedBuiltinTimeEvalOneVec (#25169) @guo-shaoge 

They are skipped in:
- https://github.com/pingcap/tidb/pull/25224
