### ISSUE TITLE
Record history hotspot information in `TIDB_HOT_REGIONS`

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#25281]
## Description

TiDB has a  memory table `TIDB_HOT_REGIONS` that provides information about hotspot Regions. But it only shows the current hotspot information. This leads to the fact that when DBAs want to query historical hotspot details, they have no way to find the corresponding hotspot information.

## Document Collection

- Proposal doc: [pingcap/tidb#27487](https://github.com/pingcap/tidb/pull/27487)

## Talent Challenge Program information

- Mentor of this issue: @nolouch 
- Recommended skills: 
          - GO
          - [Etcd Election](https://etcd.io/docs/v3.3/dev-guide/api_concurrency_reference_v3/)
          - [statstics upddate](https://pingcap.com/blog-cn/tidb-source-code-reading-14/#%E7%9B%B4%E6%96%B9%E5%9B%BE%E7%9A%84%E6%9B%B4%E6%96%B0)
- Estimated Workloads: (2XL)

## Milestones and action items

Milestone 1: design and implement, Expected finish date: 2m

- [x] Detail Design https://github.com/pingcap/tidb/pull/27487

- Implement 
  - [x] Store History Regions in PD https://github.com/tikv/pd/issues/4066
  - [x] Supports query history regions https://github.com/pingcap/tidb/issues/27772

Milestone 2: test and document, release it. Expected finish date: 1m

- [x] Test & Document

## Mentor(s)

*  @nolouch 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)
