### ISSUE TITLE
TinySQL: design and implement a learning-friendly distributed database

### ISSUE THREAD

**Issue by rebelice** [pingcap/tidb#25321]
## Description

Design and implement a learning-friendly distributed database

We have an open discussion [here ](https://internals.tidb.io/t/topic/154)

## Document Collection

- Proposal doc: ${proposal doc}
- Weekly report: ${weekly report link}

## Talent Challenge Program information

- Mentor of this issue: @rebelice 
- Recommended skills:
  - Go
  - Teaching/TA Experience
  - Basic understanding of the distributed database
- Estimated Workloads: 6XL

## Milestones and action items

Milestone 1: ${milestone description}, Expected finish date: ${date}

- [ ] Detail Design

Milestone 2: ${milestone description}, Expected finish date: ${date}

- [ ] Implement the TinySQL

Milestone 3: ${milestone description}, Expected finish date: ${date}

- [ ] Complete the study guide 
- [ ] Complete the correctness test

**Comment by winoros** [comment]
So if possible, maybe we can try rust?(

**Comment by rebelice** [comment]
> So if possible, maybe we can try rust?(

I think for such a learning-friendly project, the first version is best to use Go. Because it‘s simple enough.
Maybe we can try rust in the subsequent version.

**Comment by ekalinin** [comment]
JFYI: found recently very similar project:
  - https://github.com/auxten/go-sqldb

**Comment by tisonkun** [comment]
@rebelice I'd prefer you close this issue and create one on https://github.com/tidb-incubator/tinysql as an improvement proposal or redesign proposal. We cannot just transfer it because these two repositories are under different organizations. :/

**Comment by rebelice** [comment]
I create a new issue  https://github.com/tidb-incubator/tinysql/issues/83 to show my design and track. Welcome to comment and discuss. I'll close this issue.
