### ISSUE TITLE
tracking issue for SPM enhancement

### ISSUE THREAD

**Issue by eurekaka** [pingcap/tidb#25970]
## Enhancement

This issue is a summary for this round SPM improvements.

- [ ] https://github.com/pingcap/tidb/issues/25842
- [ ] https://github.com/pingcap/tidb/issues/25864
- [ ] https://github.com/pingcap/tidb/issues/15702
- [ ] https://github.com/pingcap/tidb/issues/15660
- [ ] https://github.com/pingcap/tidb/issues/15655

**Comment by tisonkun** [comment]
Hi @eurekaka do we have a design document for this effort? Or these are all concrete enhancements that do not deserve a design doc?
