### ISSUE TITLE
Fix privilege problems of accessing `information_schema`

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#26120]
## Background

There are some privilege problems of accessing the tables in `information_schema`.
Generally, there are 2 kinds of problems:
1. Users without `PROCESS` privilege should be unable to access the cluster data, such as `cluster_config`, but they can.
2. Users without the super privilege should able to access their own data, such as `user_privileges`, but they can access all.

## Risks

Many tools query tables in `information_schema`. Those tools may need special privileges to import / export / backup / restore data.

### Stage 1

Fix some issues and merge them into 5.1.1 before 2021-7-20.

- [x] #26062
  - https://github.com/pingcap/tidb/pull/26071
- [x] #26121  @mjonss  https://github.com/pingcap/tidb/pull/26220
- [x] #26122  @mjonss  https://github.com/pingcap/tidb/pull/26220
- [x] #26123  @mjonss  https://github.com/pingcap/tidb/pull/26220
- [x] #26124  @mjonss  https://github.com/pingcap/tidb/pull/26220
- [x] #26125  @AilinKid  https://github.com/pingcap/tidb/pull/26208
- [x] #26126  @AilinKid  https://github.com/pingcap/tidb/pull/26220
- [x] #26127  @AilinKid   https://github.com/pingcap/tidb/pull/26255
- [x] #26069
  - https://github.com/pingcap/tidb/pull/26070
- [x] #26128  @AilinKid  https://github.com/pingcap/tidb/pull/26298

### Stage 2

TBD

**Comment by bb7133** [comment]
@djshow832 Can we close this issue now?

**Comment by ti-srebot** [comment]
## Please edit this comment or add a new comment to complete the following information

### Not a bug

1. Remove the 'type/bug' label
2. Add notes to indicate why it is not a bug

### Duplicate bug

1. Add the 'type/duplicate' label
2. Add the link to the original bug

### Bug

Note: Make Sure that 'component', and 'severity' labels are added
Example for how to fill out the template: https://github.com/pingcap/tidb/issues/20100

#### 1. Root Cause Analysis (RCA) (optional) 


#### 2. Symptom (optional)



#### 3. All Trigger Conditions (optional)



#### 4. Workaround (optional)

#### 5. Affected versions



#### 6. Fixed versions

**Comment by djshow832** [comment]
Fine, I'll reopen it after I list the issues in stage 2. @bb7133
