### ISSUE TITLE
Improve memory management and limit global memory usage

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#26296]
## Enhancement
Now we can roughly perform SQL basic memory statistics and memory limit functions through memory.Tracker. But when there are many SQLs executed at the same time, TiDB still has OOM risk. We may need to take some measures to avoid this situation.

For TiDB's memory management, there are still several category of things left to do.

### Category A: Track and limit the resident memory
When TiDB is performing services, it will need to apply for resident memory, such as statistics and various caches. If this memory is not restricted, it may cause TiDB to directly OOM.

- [ ] Introducing cache function of stats information, to control the memory usage of statistical information.

- [ ] Control the cache size of prepare statement and prepare plan cache.

### Category B: When TiDB has the risk of OOM, take some measures to alleviate the memory pressure of TiDB
When TiDB has a large memory footprint, we may be able to take some measures to avoid TiDB OOM as much as possible.
- [ ] When tidb memory exceeds a threshold, perform front-end flow control, and temporarily do not process new requests, until the memory drops to a safe value.
- [ ] Perform some processing on SQL that takes up a lot of memory. For example, trigger spill action of the SQL with the largest memory usage or cancel.
