### ISSUE TITLE
Tracking test cases running more than 3s

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#26575]
We are plan to to limit the time of single unit test, we have to handle the current tests which run too long.

If we can't limit the time in the testing framework https://github.com/pingcap/tidb/issues/26289, at least we can write a simple and dirty script first, and add that script to the CI workflow, prevent a single test runs too long.

It can be divide into three steps:

1. Add the restriction, but use a whitelist to filter out the current test cases  
2. Fix all the cases that running too long
3. Remove the whitelist

This issue is used to track the bad cases, I'll list them and assign them to the original author.

server

- [ ] PASS: tidb_test.go:1509: tidbTestTopSQLSuite.TestTopSQLCPUProfile	4.657s  @crazycs520 
- [ ] PASS: conn_test.go:756: ConnTestSuite.TestTiFlashFallback	253.585s
- [ ] PASS: conn_test.go:587: ConnTestSuite.TestConnExecutionTimeout	12.412s
- [ ] PASS: tidb_test.go:1400: tidbTestSuite.TestGracefulShutdown	2.794s
- [ ] PASS: statistics_handler_test.go:88: testDumpStatsSuite.TestDumpStatsAPI	3.882s
- [ ] PASS: http_handler_test.go:1444: HTTPHandlerTestSuite.TestZipInfoForSQL	10.308s  @crazycs520 
- [ ] PASS: http_handler_test.go:686: HTTPHandlerTestSuite.TestTiFlashReplica	7.439s
- [ ] PASS: http_handler_test.go:229: HTTPHandlerTestSuite.TestRegionsAPI	5.283s
- [ ] PASS: http_handler_test.go:250: HTTPHandlerTestSuite.TestRegionsAPIForClusterIndex	5.276s
- [ ] PASS: http_handler_test.go:284: HTTPHandlerTestSuite.TestRangesAPI	5.285s
- [ ] PASS: http_handler_test.go:346: HTTPHandlerTestSuite.TestListTableRanges	5.276s
- [ ] PASS: http_handler_test.go:322: HTTPHandlerTestSuite.TestListTableRegions	5.283s
- [ ] PASS: http_handler_test.go:1019: HTTPHandlerTestSuite.TestGetSchema	5.284s
- [ ] PASS: http_handler_test.go:1121: HTTPHandlerTestSuite.TestGetSchemaStorage	5.295s
- [ ] PASS: http_handler_test.go:1000: HTTPHandlerTestSuite.TestGetSettings	5.281s
- [ ] PASS: http_handler_test.go:581: HTTPHandlerTestSuite.TestGetTableMVCC	5.283s
- [ ] PASS: http_handler_test.go:934: HTTPHandlerTestSuite.TestGetIndexMVCC	5.274s
- [ ] PASS: http_handler_test.go:671: HTTPHandlerTestSuite.TestGetMVCCNotFound	5.339s
- [ ] PASS: http_handler_test.go:870: HTTPHandlerTestSuite.TestDecodeColumnValue	5.271s
- [ ] PASS: http_handler_test.go:379: HTTPHandlerTestSuite.TestBinlogRecover	2.704s

session

- [ ] PASS: pessimistic_test.go:2677: testPessimisticSuite.TestAmendForIndexChange	4.394s @cfzjywxk 
- [ ] PASS: pessimistic_test.go:703: testPessimisticSuite.TestInnodbLockWaitTimeout	4.045s
- [ ] PASS: pessimistic_test.go:1145: testPessimisticSuite.TestPessimisticLockNonExistsKey	5.024s
- [ ] PASS: pessimistic_test.go:483: testPessimisticSuite.TestSelectForUpdateNoWait	8.038s
- [ ] PASS: session_test.go:4240: testSessionSerialSuite.TestProcessInfoIssue22068	5.007s

executor

- [ ] PASS: executor_pkg_test.go:464: pkgTestSuite.TestAggPartialResultMapperB	2.100s
- [ ] PASS: join_test.go:97: testSuiteJoin2.TestJoin	2.426s
- [ ] PASS: aggregate_test.go:56: testSuiteAgg.TestAggregation	2.048s
- [ ] PASS: parallel_apply_test.go:67: testSuite.TestApplyColumnType	2.265s
- [ ] PASS: stale_txn_test.go:1004: testStaleTxnSuite.TestStmtCtxStaleFlag	2.045s
- [ ] PASS: partition_table_test.go:749: partitionTableSuite.TestBatchGetforRangeandListPartitionTable	2.416s
- [ ] PASS: admin_test.go:967: testSuite8.TestAdminCheckTable	2.923s
- [ ] PASS: explain_test.go:335: testSuite2.TestExplainAnalyzeCTEMemoryAndDiskInfo	2.984s
- [ ] PASS: index_lookup_join_test.go:351: testSuite5.TestPartitionTableIndexJoinAndIndexReader	2.176s
- [ ] PASS: write_test.go:3383: testSuite4.TestWriteListColumnsPartitionTable1	2.322s
- [ ] PASS: executor_test.go:2744: testSuite2.TestLowResolutionTSORead	3.009s
- [ ] PASS: write_test.go:3133: testSuite4.TestWriteListPartitionTable1	2.797s
- [ ] PASS: write_test.go:3258: testSuite4.TestWriteListPartitionTable2	3.001s
- [ ] PASS: partition_table_test.go:2356: partitionTableSuite.TestDirectReadingWithAgg	14.772s
- [ ] PASS: partition_table_test.go:2132: partitionTableSuite.TestDirectReadingWithUnionScan	4.258s
- [ ] PASS: partition_table_test.go:306: partitionTableSuite.TestOrderByandLimit	3.107s
- [ ] PASS: partition_table_test.go:1992: partitionTableSuite.TestParallelApply	4.142s
- [ ] PASS: partition_table_test.go:1889: partitionTableSuite.TestSubqueries	5.442s
- [ ] PASS: partition_table_test.go:2232: partitionTableSuite.TestUnsignedPartitionColumn	2.392s
- [ ] PASS: executor_test.go:5861: testRecoverTable.TestFlashbackTable	7.213s
- [ ] PASS: executor_test.go:5765: testRecoverTable.TestRecoverTable	5.118s
- [ ] PASS: tiflash_test.go:534: tiflashTestSuite.TestCancelMppTasks	3.014s
- [ ] PASS: tiflash_test.go:668: tiflashTestSuite.TestMppApply	6.057s
- [ ] PASS: tiflash_test.go:146: tiflashTestSuite.TestMppExecution	35.121s
- [ ] PASS: tiflash_test.go:612: tiflashTestSuite.TestMppUnionAll	6.067s
- [ ] PASS: tiflash_test.go:401: tiflashTestSuite.TestPartitionTable	7.086s
- [ ] PASS: executor_test.go:2464: testSerialSuite.TestSplitRegionTimeout	3.028s
- [ ] PASS: stale_txn_test.go:92: testStaleTxnSerialSuite.TestSelectAsOf	4.023s

planner/core

- [ ] PASS: prepare_test.go:1206: testPlanSerialSuite.TestPartitionTable	5.067s  @qw4990 

ddl

- [ ] PASS: db_integration_test.go:1219: testIntegrationSuite5.TestBackwardCompatibility	3.471s
- [ ] PASS: partition_test.go:186: testPartitionSuite.TestAddPartitionReplicaBiggerThanTiFlashStores	10.109s
- [ ] PASS: column_type_change_test.go:1183: testColumnTypeChangeSuite.TestColumnTypeChangeFromJsonToOthers	4.540s
- [ ] PASS: column_type_change_test.go:700: testColumnTypeChangeSuite.TestColumnTypeChangeFromNumericToOthers	2.834s
- [ ] PASS: column_type_change_test.go:473: testColumnTypeChangeSuite.TestColumnTypeChangeFromStringToOthers	3.039s
- [ ] PASS: <autogenerated>:1: testCTCSerialSuiteWrapper.TestColumnTypeChangeFromNumericToOthers	2.834s
- [ ] PASS: <autogenerated>:1: testCTCSerialSuiteWrapper.TestColumnTypeChangeFromStringToOthers	3.059s
- [ ] PASS: db_test.go:6388: testSerialDBSuite.TestCommitTxnWithIndexChange	3.784s
- [ ] PASS: db_integration_test.go:2800: testSerialDBSuite.TestDuplicateErrorMessage	2.960s

ddl/failtest

- [ ] PASS: fail_db_test.go:218: testFailDBSuite.TestAddIndexFailed	69.802s
- [ ] PASS: fail_db_test.go:353: testFailDBSuite.TestAddIndexWorkerNum	57.401s

expression

- [ ] PASS: builtin_miscellaneous_vec_test.go:137: testEvaluatorSuite.TestSleepVectorized	3.503s
- [ ] PASS: builtin_time_vec_generated_test.go:6730: testVectorizeSuite1.TestVectorizedBuiltinTimeFuncGenerated	1.196s

owner

- [ ] PASS: fail_test.go:64: testSuite.TestFailNewSession	5.496s
- [ ] PASS: fail_test.go:64: testSuite.TestFailNewSession	5.448s

privilege/privileges

- [ ] PASS: privileges_test.go:1446: testPrivilegeSuite.TestSecurityEnhancedModeInfoschema	82.565s @morgo 

store

- [ ] PASS: batch_coprocessor_test.go:85: testBatchCopSuite.TestStoreErr	41.758s
- [ ] PASS: batch_coprocessor_test.go:121: testBatchCopSuite.TestStoreSwitchPeer	40.581s

store/gcworker

- [ ] PASS: gc_worker_test.go:268: testGCWorkerSuite.TestPrepareGC	2.539s
- [ ] PASS: gc_worker_test.go:783: testGCWorkerSuite.TestLeaderTick	2.026s

**Comment by xuyifangreeneyes** [comment]
I wrote ` ConnTestSuite.TestTiFlashFallback`. I will handle the test case.

**Comment by morgo** [comment]
@tiancaiamao I can't explain why `TestSecurityEnhancedModeInfoschema` was 82s for you. For me it's a quick test:
```
PASS: privileges_test.go:1446: testPrivilegeSuite.TestSecurityEnhancedModeInfoschema	0.017s
```

The test itself is also quite straight forward (no loops or anything complicated). The only thing I can think of is if reading from one of the tables such as `CLUSTER_STATEMENTS_SUMMARY` blocks while waiting for the resource to be ready.

**Comment by tiancaiamao** [comment]
I have a PR https://github.com/pingcap/tidb/pull/26578 to enforce the restriction, and after it's merged, no new slow unit test case can be added.
