### ISSUE TITLE
Tracking issue for analyze predicate/user-specified columns

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#27828]
## Proposal

related issue: #27358
design doc: https://github.com/pingcap/tidb/pull/28878

Currently `ANALYZ TABLE` collects the statistics for all columns. However, only some columns' statistics are used in making query plans while others are not used. If some column occurs in filter conditions such as where/join conditions, its statistics will be used for calculating selectivity. We call such column **predicate column**. If we only collect the statistics for the predicate columns, the cost of `ANALYZE TABLE` can be reduced. 

Hence we want to do the following things:
1. track which columns are predicate columns
2. support only analyze predicate columns
3. support only analyze user-specified columns.

## Development Task

- [x] https://github.com/pingcap/tidb/issues/28845
- [x] https://github.com/pingcap/tidb/issues/29376
- [x] https://github.com/pingcap/tidb/issues/29674
- [x] https://github.com/pingcap/tidb/issues/28909
- [x] https://github.com/pingcap/tidb/issues/29877
- [x] https://github.com/pingcap/tidb/issues/28916
- [x] https://github.com/pingcap/tidb/issues/29182
- [x] https://github.com/pingcap/tidb/issues/28978
- [x] https://github.com/pingcap/tidb/issues/29025
- [x] https://github.com/pingcap/tidb/issues/31102
- [x] https://github.com/pingcap/tidb/issues/31205
- [ ] https://github.com/pingcap/tidb/pull/28787
- [ ] use analyze config to set all columns/predicate columns/user-specified columns for both manually-analyze and auto-analyze.
- [ ] https://github.com/pingcap/tidb/issues/28986

**Comment by feitian124** [comment]
Did some research and find in MySQL, a predicate is a Boolean expression that evaluates to TRUE, FALSE, or UNKNOWN.
together with `predicate` definition,  `predicate column` is much clean now.

Is this an official  terminology and added to docs?

**Comment by xuyifangreeneyes** [comment]
> Did some research and find in MySQL, a predicate is a Boolean expression that evaluates to TRUE, FALSE, or UNKNOWN. together with `predicate` definition, `predicate column` is much clean now.
> 
> Is this an official terminology and added to docs?

The design doc in #28878 has description on `predicate column`. You can also take a look at redshift's doc/blog on predicate columns. Here are the links:
1. https://aws.amazon.com/blogs/big-data/collect-data-statistics-up-to-5x-faster-by-analyzing-only-predicate-columns-with-amazon-redshift/
2. https://docs.aws.amazon.com/redshift/latest/dg/t_Analyzing_tables.html
