### ISSUE TITLE
Tracking issue for moving parser back to TiDB

### ISSUE THREAD

**Issue by xhebox** [pingcap/tidb#28257]
## Intro

This issue tracks the work of rfc #28015, which will move parser back to TiDB for convenience. For more details, check the detailed design https://github.com/pingcap/tidb/blob/master/docs/design/2021-09-13-parser-as-submodule-of-tidb.md.

The work will not be assigned to members of the community, but the whole migration progress is public.

The migration can be roughly divided into two phases. The second phase will focus on migration for the community of parser.

## Phase 1

- [x] #28454
  - [x] deadline 10-9 
  - [x] #28685
- [x] Migrate tests for the new sub module.
  - [x] deadline 10-16
  - [x] #28699
- [x] Announce the migration plan officially to stop sending new PRs/issues.
- [ ] Transfer old issues.
  - [ ] after tests is moved 
- [ ] Clean up
  - [ ] after tests is moved 
  - [ ] #29322 
- [ ] Synchronize new changes in pingcap/parser to the sub-module in pingcap/tidb. This task will be executed regularly until phase 2 started.
  - [ ] after tests is moved
- [ ] proposal about the boloated parser.go file
- [ ] update https://github.com/pingcap/tidb/blob/master/parser/docs/update-parser-for-tidb.md
- [ ] update tidb-dev-guide
  - [x] pingcap/tidb-dev-guide#172
  - [x] pingcap/tidb-dev-guide#174

## Phase 2 (Not started)

- [ ] Announce the deprecation officially to the public.
- [ ] Create wrapper packages for pingcap/parser, which re-exports things from `pingcap/tidb/parser`.
- [ ] Remove the old CI.
- [ ] Check with the community that if we can archive pingcap/parser. Ideally, I hope this can be done after 3 or 4 months.

**Comment by tisonkun** [comment]
>  Announce the migration plan officially to stop sending new PRs/issues.

Is there a link for the announcement? I don't see an announcement on internals.tidb.io.

**Comment by tisonkun** [comment]
> Nope. I sent the mail, and I will create a new reply in the forum. Or do you prefer a new thread?

@xhebox a new thread is better, see also https://internals.tidb.io/t/topic/104 and other posts with "announcement" tag for example.
