### ISSUE TITLE
Support secure bootstrap method

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#28481]
## Enhancement

Currently TiDB creates a root user with no password, that is bound to `0.0.0.0/::`.

There should be a way to bootstrap securely.

### Subtasks

- [x] https://github.com/pingcap/tidb/pull/28482
- [x] https://github.com/pingcap/tidb/issues/28484
- [x] https://github.com/pingcap/tidb/issues/28485

**Comment by morgo** [comment]
This has been added for now. It is waiting on installers to upgrade before being considered for enabling by default.
