### ISSUE TITLE
Tracking issue for enabling more linters

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#28720]
## Enhancement

There are a lot of linters in https://golangci-lint.run/usage/linters. We can utilize them to enhance TiDB's code quality.

To enable one of the linters, the steps are as follows:
1. Add the target linter to `.golangci.yml` (comment out the others to speed up the linter's check).
2. Run `make check` and see what issues are detected.
3. Fix the code or add `// nolinter` comments.
4. Repeat step 2 and step 3 until all the issues are fixed.
5. File a PR and reference the subtask issue.

Here is an example: https://github.com/pingcap/tidb/pull/28756/files

- [x] #31737
- [ ] #31357
- [x] #28754
- [x] #28755
- [x] #28859
- [x] #28862
- [x] #28865
- [x] #28864
- [x] #29003
- [x] #28861
- [ ] #28863
- [x] #29642
- [x] #29004
- [ ] #29643
- [ ] #28860
- [ ] Enable golangci-lint `cyclop`
- [ ] Enable golangci-lint `dupl`
- [ ] Enable golangci-lint `errorlint`
- [x] #30733
- [ ] Enable golangci-lint `promlinter`
- [ ] Enable golangci-lint `exhaustivestruct`
- [ ] Enable golangci-lint `gocognit`
- [ ] Enable golangci-lint `goconst`
- [ ] Enable golangci-lint `gocritic`
- [ ] Enable golangci-lint `gocyclo`
- [ ] Enable golangci-lint `godot`
- [ ] Enable golangci-lint `goerr113`
- [ ] Enable golangci-lint `gomnd`
- [ ] Enable golangci-lint `unparam`
- [ ] Enable golangci-lint `wastedassign`

### Other linters that are thought to be unnecessary

<details>

- dogsled
- depguard
- forbidigo
- funlen
- gci
- gochecknoglobals
- gochecknoinits
- godox
- gofmt
- gofumpt
- goheader
- goimports
- gomoddirectives
- gomodguard
- goprintffuncname
- ifshort
- importas
- lll
- misspell
- nakedret
- nestif
- nilerr
- nlreturn
- noctx
- nolintlint
- paralleltest
- revive
- tagliatelle
- testpackage
- thelper
- tparallel
- whitespace
- wrapcheck
- wsl

</details>

### Misc

* [x] #28904
* [x] #28905

**Comment by tisonkun** [comment]
@tangenta what is the following plan for this issue? Shall we investigate and turn on linters one by one?

**Comment by tangenta** [comment]
These linters are roughly checked, but please feel free to make further investigations.

I think we can turn on them if the time cost is not significant.

**Comment by morgo** [comment]
@tangenta That was it. My version was:
```bash
$ tools/bin/golangci-lint version
golangci-lint has version 1.29.0 built from 6a68907 on 2020-07-20T14:54:31Z
```

I upgraded to v1.42.1 and I get different errors now. So it looks like this is something we should script around to make sure the version is in an acceptable range?

```
util/israce/norace.go:14: File is not `goimports`-ed (goimports)

util/testbridge/bridge.go:14: File is not `goimports`-ed (goimports)

util/sys/linux/sys_linux.go:13: File is not `goimports`-ed (goimports)
```

**Comment by tangenta** [comment]
We are planning to migrate the linter tool to "nogo" to utilize the incremental lint. This issue will be closed temporarily until the migrated linters are stabilized. For details, see https://github.com/pingcap/tidb/pull/35344.

Thanks for your contributions.
