### ISSUE TITLE
Tracking issue for supporting analyze with sample rate option

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#28960]
<details>
<summary>Details</summary>

</details>

Before we only support pass sample size as the analyze option, now we want to support to pass the sample rate as the analyze option.

This issue tracks the progress:

- [x] Add support for the parser.  Will done by https://github.com/pingcap/tidb/pull/28961
- [x] Add support to pass the new analyze option via request. https://github.com/pingcap/tipb/pull/236
- [x] Support it on TiKV side. https://github.com/tikv/tikv/pull/11101
- [x] Support it on TiDB side. #28999 
- [x] Testing and benchmark results compared with previous.

**Comment by winoros** [comment]
Done.
