### ISSUE TITLE
Tracking issue for Lock View Enhancement (Sprint 5)

### ISSUE THREAD

**Issue by longfangsong** [pingcap/tidb#28970]
Currently, when TiDB meets long lock waiting, deadlock, conflict during committing, etc, though it is possible for use to get transaction id (ie. start_ts) with different kinds of methods (current lock view, logs, etc.) After a transaction ends, we’ll never know its content SQL, so we cannot use this information to solve problems we met during oncalls.

This feature tries to record history transaction information (SQLs) and map a certain transaction id to that information, which can solve this problem.

This issue track the development progress of this feature.

- [ ] Add TRX_SUMMARY table. #28835
- [ ] Add TRX_ID_DIGEST table.
- [ ] Add config items.
