### ISSUE TITLE
Enhance-Split-Table-Stability

### ISSUE THREAD

**Issue by hzh0425** [pingcap/tidb#29034]
## Description

Currently, the split table(regions) in tidb is constructed by following 2 steps:

1. Notify tikv to split regions
2. Notify pd to scatter regions

But this will let the time cost for the whole splitting table become unstable and rather time-consuming.

So we want to split and scatter regions in pd directly, that means I should add new method : SplitAndScatterRegions()

Tidb can directly send a splitAndScatterRegions instruction to PD, and deliver PD to split and scatter without sending two requests (split first and then scatter)

## Tasks

- [x] Discussion PR: https://github.com/tikv/pd/issues/4095

- [x] Detail design : https://github.com/pingcap/tidb/pull/29036

- [x] kvproto : Add splitAndScatterRegions method in pdpb.proto https://github.com/pingcap/kvproto/pull/826

- [ ] PD : Implement splitAndScatterRegions in grpc_service, client/client.go  https://github.com/tikv/pd/pull/4333

- [ ] client-go:  Add SplitAndScatterRegions in tikv/split-regions.go https://github.com/tikv/client-go/pull/343

- [ ] tidb : Use SplitAndScatterRegions in executor/split.go https://github.com/pingcap/tidb/pull/28989

## Mentor

- @Yisaer 

## Recommended Skills
- go

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/issues/6426
