### ISSUE TITLE
Development Tasks for Log-based Increment Backup, directly on TiKV

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#29501]
## Description
We want to have a log-based streaming backup system which
* can scale up with the cluster
* native, does not require an external processor, to reduce the number of “moving parts”
* light-weight, continuous backup in should not affect latency
* low-level, keeping the details of the original cluster as much as possible, reducing backup and restore complexity
* support point-in-time recovery

This issue tracks our progress.
- [Detail Design](https://internals.tidb.io/t/topic/479)

## Milestone
* [x] Backup the DML data **only** to s3 with 10G data size and scheduler paused.  **due date 12/16/21**
* [x] Restore above DML data from s3.
* [x] Implement local(nfs) storage.  **due date 12/16/21**
* [x] #34621
* [x] Support backup **only** DML data with random scheduler enabled.
* [x] Support TB level workload (TBD: determine incremental flow in workload).
* [ ] Support 10k tables workload (TBD: determine incremental flow in workload).
* [x] Support TB level workload with random TiKV crash.
* [ ] Support 10k tables workload with random TiKV crash.

### Log File Structure
* [ ] #30099
* [x] #30591
* [ ] Support a brief summary from log file via BR command/TiDB SQL.
* [ ] Support truncate unnecessary files via CLI.

### Support Log-based Backup
* [x] #29970 @joccau 
* [x] #30097
* [x] #29969 @YuJuncen 
* [x] #30098
* [x] #30446 @3pointer
* [x] #32695
* [x] #29971 @kennytm 
* [x] Implement Log-based Backup Task management.
* [x] Handle region version change. (https://github.com/3pointer/tikv/pull/14)
* [x] Metrics on TiKV. (https://github.com/3pointer/tikv/pull/15)

### Support Log-based Restore
* [x] #31975
* [x] #31979
* [x] #31980
* [x] Handle index key properly.
* [x] #32696
* [x] Port the retry rule from full restore (`IngestSST`) for incremental restore (`Apply`)
* [x] #34098

### Support Checksum 
* [ ] Support generate checksum data during Backup.
* [ ] Support valid checksum data during Restore.

### Trivia
* [ ] Implement TiDB HTTP API to manage task.
* [x] #33410
* [x] #30544
* [x] #30543
* [ ] https://github.com/pingcap/tidb/issues/32167
* [x] #32253
* [x] #33087
* [x] #33795
* [x] https://github.com/pingcap/tidb/issues/33866
