### ISSUE TITLE
Tracking for Optimize Trace

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#29661]
## Enhancement

Recently we are working to implement `Optimize Trace` in our optimize layer in TiDB. This would help us easy to track the detail in  whole optimize processing. For the detail design, we currently have a [public design document](https://docs.google.com/document/d/19sdPOWexBuobN4DvOBfMXAdlyb4lvBSPRG-GqRM5USE/edit?usp=sharing) in chinese.

## time trace

 * [ ] support expanding trace statement to recv param.
 * [ ] support time tracing in optimize layer

### logical optimize

* [ ] support basic optimize trace in logical optimize
* [ ] fulfill optimize rule step in each rule logical optimize
* [ ] support dump trace file in json after statement finish.
* [ ] support display optimize trace in dashboard

### physical optimize

tbd

**Comment by jackwener** [comment]
The doc can't be opened.👀

**Comment by Yisaer** [comment]
> The doc can't be opened.👀

Thanks for pointing it out. The link has been updated.
