### ISSUE TITLE
Plan Cache Enhancement

### ISSUE THREAD

**Issue by Reminiscent** [pingcap/tidb#30826]
## Enhancement
The current Plan Cache feature supports very limited scenarios and has many restrictions. Therefore, we plan to enhance this feature in the future. The related development plan will be recorded under this ISSUE. This ISSUE will continue to be added.

## Milestones and action items
Milestone 1: Support Plan Cache refresh mechanism, including automatic refresh and manual refresh.
- [x] [add grammar support for admin flush [SESSION|INSTANCE] plan_cache in parser](https://github.com/pingcap/tidb/pull/30747)
- [x] [support admin flush plan_cache](https://github.com/pingcap/tidb/pull/30370)
- [x] [support plan cache aware of bindings](https://github.com/pingcap/tidb/pull/30169)
