### ISSUE TITLE
string function support 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#310]
- [x] ASCII() Return numeric value of left-most character
- [x] BIN()   Return a string containing binary representation of a number
- [x] BIT_LENGTH()    Return length of argument in bits
- [x] CHAR_LENGTH()   Return number of characters in argument
- [x] CHAR()  Return the character for each integer passed
- [x] CHARACTER_LENGTH()  Synonym for CHAR_LENGTH()
- [x] CONCAT_WS() Return concatenate with separator
- [x] CONCAT()    Return concatenated string
- [x] ELT()   Return string at index number
- [x] EXPORT_SET()    Return a string such that for every bit set in the value bits, you get an on string and for every unset bit, you get - [ ] an off string
- [x] FIELD() Return the index (position) of the first argument in the subsequent arguments
- [x] FIND_IN_SET()   Return the index position of the first argument within the second argument
- [x] FORMAT()    Return a number formatted to specified number of decimal places
- [x] HEX()   Return a hexadecimal representation of a decimal or string value
- [x] INSERT()    Insert a substring at the specified position up to the specified number of characters
- [x] INSTR() Return the index of the first occurrence of substring
- [x] LCASE() Synonym for LOWER()
- [x] LEFT()  Return the leftmost number of characters as specified
- [x] LENGTH()    Return the length of a string in bytes
- [x] LIKE    Simple pattern matching
- [ ] LOAD_FILE() Load the named file https://github.com/pingcap/tidb/issues/8436
- [x] LOCATE()    Return the position of the first occurrence of substring
- [x] LOWER() Return the argument in lowercase
- [x] LPAD()  Return the string argument, left-padded with the specified string
- [x] LTRIM() Remove leading spaces
- [x] MAKE_SET()  Return a set of comma-separated strings that have the corresponding bit in bits set
- [x] MATCH   Perform full-text search
- [x] MID()   Return a substring starting from the specified position
- [x] NOT LIKE    Negation of simple pattern matching
- [x] NOT REGEXP  Negation of REGEXP
- [x] OCT()   Return a string containing octal representation of a number
- [x] OCTET_LENGTH()  Synonym for LENGTH()
- [x] ORD()   Return character code for leftmost character of the argument
- [x] POSITION()  Synonym for LOCATE()
- [x] QUOTE() Escape the argument for use in an SQL statement
- [x] REGEXP  Pattern matching using regular expressions
- [x] REPEAT()    Repeat a string the specified number of times
- [x] REPLACE()   Replace occurrences of a specified string
- [x] REVERSE()   Reverse the characters in a string
- [x] RIGHT() Return the specified rightmost number of characters
- [x] RLIKE   Synonym for REGEXP
- [x] RPAD()  Append string the specified number of times
- [x] RTRIM() Remove trailing spaces
- [ ] SOUNDEX()   Return a soundex string https://github.com/pingcap/tidb/issues/3930
- [ ] SOUNDS LIKE Compare sounds https://github.com/pingcap/tidb/issues/3930
- [x] SPACE() Return a string of the specified number of spaces
- [x] STRCMP()    Compare two strings
- [x] SUBSTR()    Return the substring as specified
- [x] SUBSTRING_INDEX()   Return a substring from a string before the specified number of occurrences of the delimiter
- [x] SUBSTRING() Return the substring as specified
- [x] TRIM()  Remove leading and trailing spaces
- [x] UCASE() Synonym for UPPER()
- [x] UNHEX() Return a string containing hex representation of a number
- [x] UPPER() Convert to uppercase

**Comment by mrmiywj** [comment]
@ngaut I will pick some functions in this issue.

**Comment by ngaut** [comment]
Cool @mrmiywj
Please feel free to send PR.

**Comment by mrmiywj** [comment]
@ngaut Actually, the `expression` folder has been removed. So maybe this issue could be closed. 
Any start issue suggested?

**Comment by shenli** [comment]
@mrmiywj builtin functions are moved here: https://github.com/pingcap/tidb/blob/master/evaluator

**Comment by a6802739** [comment]
@siddontang , could I have a try for this?

**Comment by siddontang** [comment]
Hi @a6802739 

It is very appreciated that you can help us add more functions. 

If you add a function, you can first run `make test` local and then send us the PR after test passes.

**Comment by coocood** [comment]
@a6802739 
Do you have the error like `package not found` when you run `make test` on your forked repo?

**Comment by a6802739** [comment]
@coocood, not found yet. Do you mean I should cross the wall to download some dependency package?

**Comment by coocood** [comment]
@a6802739 
It seems like you haven't forked tidb yet.
Please describe what you have done and what error you have got, thank you.

**Comment by a6802739** [comment]
this is the error I met.
```
# github.com/pingcap/tidb/parser
parser/lexer.go:92: undefined: yySymType
parser/misc.go:494: undefined: yySymType
parser/yy_parser.go:60: undefined: yySymType
parser/yy_parser.go:61: undefined: yySymType
parser/yy_parser.go:62: undefined: yySymType
FAIL	github.com/pingcap/tidb [build failed]
# github.com/pingcap/tidb/parser
parser/lexer.go:92: undefined: yySymType
parser/misc.go:494: undefined: yySymType
parser/yy_parser.go:60: undefined: yySymType
parser/yy_parser.go:61: undefined: yySymType
parser/yy_parser.go:62: undefined: yySymType
FAIL	github.com/pingcap/tidb/ast [build failed]
# github.com/pingcap/tidb/parser
/var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/go-build175989233/github.com/pingcap/tidb/parser/_test/_obj_test/lexer.go:100: undefined: yySymType
/var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/go-build175989233/github.com/pingcap/tidb/parser/_test/_obj_test/misc.go:516: undefined: yySymType
/var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/go-build175989233/github.com/pingcap/tidb/parser/_test/_obj_test/yy_parser.go:61: undefined: yySymType
/var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/go-build175989233/github.com/pingcap/tidb/parser/_test/_obj_test/yy_parser.go:62: undefined: yySymType
/var/folders/72/byjy11cs0dj_z3rjtxnj_nn00000gn/T/go-build175989233/github.com/pingcap/tidb/parser/_test/_obj_test/yy_parser.go:63: undefined: yySymType
make: *** [gotest] Error 2
```

**Comment by coocood** [comment]
@a6802739 
Please try `make dev`

**Comment by a6802739** [comment]
@coocood , should I cross the wall?
```
package golang.org/x/tools/go/gcimporter15: unrecognized import path "golang.org/x/tools/go/gcimporter15" (https fetch: Get https://golang.org/x/tools/go/gcimporter15?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
```

**Comment by coocood** [comment]
@a6802739 
`golint` imports `golang.org/x/tools/go/gcimporter15`, `make check` use `golint`, so you need to use a proxy to get `golint`.
But I think you can run `make test` now.

**Comment by a6802739** [comment]
@coocood , got it. Thanks a lot.

**Comment by coocood** [comment]
@a6802739 
Feel free to ask anything, looking forward to your PR.

**Comment by morgo** [comment]
The only two remaining functions are `SOUNDEX` (plus its alias) and `LOAD_FILE`.  Since both of these are lower priority (and have dedicated sub-issues),  I am going to close this issue for now.

Please feel free to re-open if you have any followup questions.  Thanks!

**Comment by SunRunAway** [comment]
Hi, it seems that `OCTET_LENGTH` is not implemented in TiDB.

I tested on the master branch with commit id 8c20289c7.
```mysql
mysql> select OCTET_LENGTH(1);
ERROR 1305 (42000): FUNCTION octet_length does not exist
```

I've unchecked the `OCTET_LENGTH` box.
