### ISSUE TITLE
Optimize the usage of the bind cache

### ISSUE THREAD

**Issue by Reminiscent** [pingcap/tidb#32466]
## Enhancement
Now we use the map as the bind records' cache. But it's dangerous when there are so many bindRecords. It may cause OOM. So we try to optimize it. The specific work items are as follows:
* Support the LRU cache
- [ ] Use the LRU to manage the bind Records' cache
- [ ] Support `show binding_cache status' to show the information about the bindCache.
* Enable/ Disable the binding
- [ ] Support `set binding enable/ disable for <stmt> {using <stmt>}`
* Telemetry
- [ ] Support the telemetry for the ``auto capture
