### ISSUE TITLE
Add more memory tracking places to improve memory management

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#33876]
## Enhancement
There are a lot of known untracked memory at the moment. We plan to track them now!

1. Untracked memory in HashJoin
    - [ ] Track the memory usage of `entryStore` in hashMap
    - [ ] Track the memory usage of golang Map in hashMap
2. Untracked memory in Sort
    - [ ] Track the memory usage of `rowPtrs` in SortedRowContainer, which record the position of each row of data in the Chunk
3. Untracked memory in Spilling process, eg. ListInDisk struct
    - [ ] Track the memory usage of `offsets` in ListInDisk, which record the offsets of each row in the file
