### ISSUE TITLE
Add more memory tracking places to improve memory management

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#33877]
## Enhancement
There are a lot of known untracked memory at the moment. We plan to track them now!

1. Untracked memory in HashJoin
    - [x] [Track the memory usage of `entryStore` in hashMap](https://github.com/pingcap/tidb/issues/35627) https://github.com/pingcap/tidb/pull/33918
    - [x] [Track the memory usage of golang Map in hashMap](https://github.com/pingcap/tidb/issues/35628) https://github.com/pingcap/tidb/pull/33918
    - [x] [Iteratror and Row/RowPtrs slice reuse in HashJoin](https://github.com/pingcap/tidb/issues/35629). https://github.com/pingcap/tidb/pull/34878
    - [ ] [Track the memory usage of probe phase in HashJoin.](https://github.com/pingcap/tidb/issues/35630) e.g. the memory usage of the matched row. In extreme cases, the memory usage of this part may be the size of the entire hashmap.  https://github.com/pingcap/tidb/blob/e21b435d0c4d538677ede2fd11b4376e22d1615d/executor/hash_table.go#L115
    - [x] [Optimize the memory usage of the read path in hashRowContainer.](https://github.com/pingcap/tidb/issues/35631) `hashRowContainer.GetMatchedRowsAndPtrs --> RowContainer.GetRow --> ListInDisk.GetRow --> diskFormatRow.toMutRow`  https://github.com/pingcap/tidb/pull/34778
2. Untracked memory in Sort
    - [x] [Track the memory usage of `rowPtrs` in SortedRowContainer](https://github.com/pingcap/tidb/issues/35632), which record the position of each row of data in the Chunk https://github.com/pingcap/tidb/pull/34128
    - [x] #35636
3. ~Untracked memory in Spilling process, eg. ListInDisk struct~
    - [ ] ~Track the memory usage of `offsets` in ListInDisk, which record the offsets of each row in the file~
    - [x] [Use non-extra-memory spilling disk implementation to avoid `offsets` memory usages.](https://github.com/pingcap/tidb/issues/35634) For example, we can also spill `offsets` into disk. https://github.com/pingcap/tidb/pull/34212
    
4. Untracked memory in IndexJoin/IndexHashJoin
    - [x] #34417
5. Refactor rateLimit for TableReader
6. [Track aggregate memory usage more accurate](https://github.com/pingcap/tidb/issues/35635) https://github.com/pingcap/tidb/pull/34732
7. [Parallel HashAgg needs spill to disk](https://github.com/pingcap/tidb/issues/35637)
