### ISSUE TITLE
txn: Tracking issue for aggregating & persisting lock view for supporting diagnosing historical problems

### ISSUE THREAD

**Issue by longfangsong** [pingcap/tidb#34457]
## Enhancement

- [ ] Support calculating transaction digest for each transaction (#28835, needs rebase)
- [ ] Persist lock-waiting and conflict status among transactions. (long term persist blocked by ng-monitor progress, doing short term persist first)
- [ ] Dashboard support (needs design)
