### ISSUE TITLE
Support `Merge` Hint for CTE Inline

### ISSUE THREAD

**Issue by dayicklp** [pingcap/tidb#36122]
## Development Task
The current version of Common Table Expression (CTE) can not be well applied in MPP, especially can not automatically expand the calculation, which hinders the execution efficiency under TiFlash. 

We need to expand CTE to be more compatible with TiFlash and make CTE more widely used in OLAP.

[Tech Design](https://docs.google.com/document/d/19tbigA46naLNkY2-fwyGV796PGhW5cZZTilzqIF04uA/edit?n=CTE_Inline_tech_with_hint)

[Weekly Report](https://docs.google.com/document/d/143xXAmjitA6bUoBCB06PhFg_1qE6Vdq8cjCFdWRx-Yg/edit#heading=h.g4kc2ihxn8tq)

[Test doc](https://docs.google.com/document/d/1_O1wWAduC1hbP5oTzQqdC-WxrxBgLeRGPLCxQtLgSuI/edit#)

### Stage

- [x] Inline function, Hint design, Function test(no binding test inside) https://github.com/pingcap/tidb/pull/34574
- [x] add binding and recursive test for Merge hint https://github.com/pingcap/tidb/pull/36352
- [x] fixe Merge hint in nested CTE  https://github.com/pingcap/tidb/pull/36432

Doc

- [ ] Add Document for `Merge` hint https://github.com/pingcap/docs-cn/pull/10373

Future optimization

- [ ] Hints cannot be used after inline (`Inl_join` hint) https://github.com/pingcap/tidb/issues/35318
- [ ] Automatically inline CTE if it has only 1 consumer https://github.com/pingcap/tidb/issues/36295
- [x] In multi-loop nested CTE, subsequent queries cannot be executed https://github.com/pingcap/tidb/issues/36373
- [ ] Add a system variable to control https://github.com/pingcap/tidb/issues/36514

**Comment by dayicklp** [comment]
Following work will be a separate issue

**Comment by dayicklp** [comment]
Following work will be a separate issue
