### ISSUE TITLE
Support Foreign Key Dev Task

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#36982]
# Support Foreign Key Dev Task

Related Issue: https://github.com/pingcap/tidb/issues/18209
Design Doc: https://github.com/pingcap/tidb/pull/35982
Draft PR: https://github.com/pingcap/tidb/pull/36757

### DDL Dev Task

- [x] Create table with foreign key https://github.com/pingcap/tidb/issues/37147
  - [x] Add global variable: `tidb_enable_foreign_key` 
- [x] Alter table add foreign key
  - [x] Support add foreign key without auto create index. https://github.com/pingcap/tidb/issues/38168 
  - [x] Support add foreign key with auto create index. https://github.com/pingcap/tidb/issues/38762
- [x] Rename Column with foreign key https://github.com/pingcap/tidb/issues/37868
- [x] Rename Table with foreign key https://github.com/pingcap/tidb/issues/38080
- [x] Rename Tables with foreign key https://github.com/pingcap/tidb/issues/38133
- [x] Modify Column with foreign key  https://github.com/pingcap/tidb/issues/37821
- [x] Drop Database with foreign key https://github.com/pingcap/tidb/issues/38005
- [x] Drop/Truncate Table with foreign key https://github.com/pingcap/tidb/issues/37772
- [x] Drop Index is needed in foreign key https://github.com/pingcap/tidb/issues/37812
- [x] Drop Column with foreign key.  https://github.com/pingcap/tidb/issues/37842 

### DML Dev Task

- [x] Support foreign key `ON DELETE`
  - [x] Support `ON DELETE` `RESTRICT`, `NO ACTION`, `SET DEFAULT` action. https://github.com/pingcap/tidb/issues/38221
  - [x] Support `ON DELETE` `CASCADE` action. https://github.com/pingcap/tidb/issues/38376
  - [x] Support `ON DELETE` `SET NULL` action. https://github.com/pingcap/tidb/issues/38594
- [x] Support foreign key `ON UPDATE`
  - [x] Support `ON UPDATE` `RESTRICT`, `NO ACTION`, `SET DEFAULT` action. https://github.com/pingcap/tidb/issues/38155
  - [x] Support `ON UPDATE` `CASCADE` action. https://github.com/pingcap/tidb/issues/38651
  - [x] Support `ON UPDATE` `SET NULL` action. https://github.com/pingcap/tidb/issues/38651
  - [x] Support foreign key in `INSERT ON DUPLICATE KEY` statement. https://github.com/pingcap/tidb/issues/38792
- [x] Support foreign key `ON INSERT` https://github.com/pingcap/tidb/issues/37465
  - [x] support foreign key constrain check when execute insert statement  
  - [x] Add lock on reference table row when insert/update child table. 
  - [x] Support `INSERT IGNORE` when foreign key constraints failed.
- [x] Support foreign key check when `UPDATE` child table. https://github.com/pingcap/tidb/issues/38155
- [x] Support foreign key when execute `REPLACE INTO` statement https://github.com/pingcap/tidb/issues/40068

### Enhancement

- [x] Show create table with foreign key  https://github.com/pingcap/tidb/issues/38118
- [x] show create table should distinguish between old and new foreign key https://github.com/pingcap/tidb/issues/38717
- [x] Refine `EXPLAIN` plan about DML with foreign key.
  - [x] Refine `EXPLAIN ANALYZE` info for `INSERT IGNORE` statement.  https://github.com/pingcap/tidb/issues/38769
  - [x] add foreign key check/cascade information in explain result   https://github.com/pingcap/tidb/issues/39166 
  - [x] add foreign key check/cascade information in explain analyze result https://github.com/pingcap/tidb/issues/39202 

### Compatibility

- [x] enable foreign_key_checks variable by default, be consistent with MySQL. https://github.com/pingcap/tidb/issues/39694

### After  Foreign Key GA

- [ ] Remove global variable: `tidb_enable_foreign_key`  https://github.com/pingcap/tidb/issues/39670

### Test

- [x] Add `GORM` test about foreign key.  https://github.com/pingcap/tidb-test/pull/1917
- [x] Import MySQL Test. https://github.com/pingcap/tidb-test/pull/2006

### User Doc

- [x] [中文文档](https://github.com/pingcap/docs-cn/pull/11974)
- [x] [English Document](https://github.com/pingcap/docs/pull/12275)

**Comment by crazycs520** [comment]
Currently, The overall progress is about 60%, most of the basic functions of the foreign key have been implemented, and we plan to GA this feature in January 2023.

If you want to experience this feature, you need to set the following variables first:

```sql
set @@global.tidb_enable_foreign_key=1;
set @@foreign_key_checks=1;
```
