### ISSUE TITLE
Supports `FLASHBACK TO TIMESTAMP` in TiDB

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#37197]
# Background
Some users want to flash back the whole cluster to a determined timestamp when there is a problem with the database like delete some important values etc. In TiDB we use MVCC to store the key values in TiKV which means we could easy to flash back it before gc complete. This issue is the tracking issue for `flashback cluster` feature.

# Task
## Docs
 - [x] https://github.com/pingcap/docs-cn/pull/11443
 - [x] https://github.com/pingcap/tidb/pull/38367
## TiDB
- [x] #37229
- [x] #37262
 * privilege check, a user with `SUPER` permission can run this stmts
 * check TS
 * check ddl history, can't have ddl jobs during `flashback`
 * check tiflash node, can't do it with tiflash
- [x] #37376
 * forbid & restart processing new ddl job in queue
 * close & recover pd scheduling
 * close & recover gc
- [x] **Execution**
  - [x] #37540
  - [x] #37665
- [ ] **Support flashback table/databases**
  - [x] #38545
  - [ ] #38673
- [ ] **Others**
 * show/get `flashback cluster` progress state from TiKV
 * [x] Refetch statistics from TiKV
 * [x] forbiden cancel flashback job in some states.
 * Reset Auto ID (optional)
 * [x] #38896
- [ ] **add gc_savepoint (optional)**
 * add a system table `gc_savepoint`
 * support auto set savepoint by TiDB itself
 * add a map according to natural physical time (Unix timestamp) -> TSO to avoid TSO drifts
- [x] #40026

## Client-go
- [x] [**Support 'flashback' request**](https://github.com/tikv/client-go/issues/569)
 * TiDB provide `key range` and `tso` to client-go, then client-go sending requests to all Region leaders in the key range (Could reuse some mechanism in client-go now, like backoff/coprocessor etc.)
 * Forbid read/write request to specified region during `flashback cluster`
 * Need an interface to get progress of `flashback cluster`

## TiKV
- [x] **https://github.com/tikv/tikv/issues/13303**

## PD
- [ ] **Add an interface to add/delete gc_savepoint (optional)**

**Comment by Defined2014** [comment]
No further plan right now, close it firstly.
