### ISSUE TITLE
planner: Memory tracking for plan cache

### ISSUE THREAD

**Issue by fzzf678** [pingcap/tidb#37632]
## Enhancement
* Currently, there is no interface to get the memory usage of plan cache. We  can only estimate the memory each plan used and set a limit number to control the memory.It is imprecise and may cause OOM of TiDB.So we would like to add memory tracker for plan cache to count and manage the memory usage.

### PhysicalPlan memory trace
* [x] Expression(Column/Constant/CorrelatedColumn/ScalarFunction) memory trace https://github.com/pingcap/tidb/pull/37624
* [x] PhysicalPlan(sort operator) memory trace https://github.com/pingcap/tidb/pull/37655
* [x] PhysicalPlan(scan operator) memory trace https://github.com/pingcap/tidb/pull/37668
* [x] PhysicalPlan(agg/limit/select/projection operator) memory trace https://github.com/pingcap/tidb/pull/37731
* [x] PhysicalPlan(reader operator) memory trace https://github.com/pingcap/tidb/pull/37736
* [x] PhysicalPlan(join operator) memory trace https://github.com/pingcap/tidb/pull/37860
* [x] PhysicalPlan(pointGet/apply/topN operator) memory trace https://github.com/pingcap/tidb/pull/37841
* [x] PhysicalPlan(mock/CTE ) memory trace https://github.com/pingcap/tidb/pull/38030
* [x] PhysicalPlan(SimpleWrapper/MemTable/ExchangeReceiver/ExchangeSender/Lock ) memory trace  https://github.com/pingcap/tidb/pull/38162
* [x] PhysicalPlan (PhysicalMaxOneRow/TableDual/Window/Shuffle/ShuffleReceiverStub/Show/ShowDDLJobs) memory trace https://github.com/pingcap/tidb/pull/38220
### Count other memory usage in plan cache
* [x] LRUPlanCache、planCacheKey、PlanCacheValue memory trace https://github.com/pingcap/tidb/pull/38069 1
* [x] Plan(Insert/Update/Delete) memory trace https://github.com/pingcap/tidb/pull/38357
* [ ] ~PlanCacheStmt、ParamMarker memory trace~
* [x] LRU according to memory usage  3
* [x] task(copTask/mppTask/rootTask) memory trace https://github.com/pingcap/tidb/pull/38638

### Test and attach
* [ ] Test accuracy of plan cache memory trace and correct
* [ ] Access memTracker (daily-run test)
* [x] Conform the security of plan cache memory trace(No panic) 
  * [x] nil pointer https://github.com/pingcap/tidb/pull/38764
  * [x] add  switch control the memory monitor https://github.com/pingcap/tidb/pull/38824

### Others
* [x] Add monitor (mem usage) 2 https://github.com/pingcap/tidb/pull/38507
* [x] Add monitor (plan number and others...) 4 https://github.com/pingcap/tidb/pull/38507
* [x] Supply document 
  * [x] https://github.com/pingcap/docs-cn/pull/11799
  * [x] https://github.com/pingcap/docs-cn/pull/11861
