### ISSUE TITLE
Support global memory control

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#37816]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, TiDB has a query-level memory control strategy mem-quota-query, which triggers Cancel when the memory usage of a single SQL exceeds mem-quota-query. However, there is currently no global memory control strategy. When TiDB has a certain degree of inaccuracy due to multiple SQLs whose memory usage does not exceed mem-quota-query or memory tracking, it will lead to high memory usage or even OOM. Therefore, we need a means that can be observed from the outside to determine whether the memory usage of the current system is normal, and when there is a problem, try to control its memory not to continue to grow, so as to reduce the risk of process crashes.

[Design Docs](https://github.com/pingcap/tidb/pull/38121)

**Todo List**

- [x] Kill the SQL with the most memory usage: When the memory usage of the TiDB instance reaches `tidb_server_memory_limit`, kill the SQL with the largest memory usage in the current system. https://github.com/pingcap/tidb/pull/37794
    - [ ] Soft limit to trigger spill disk, hard limit to tirgger cancel. https://github.com/pingcap/tidb/issues/37104
    - [x] Support bytesize format and percentage format for system variable. https://github.com/pingcap/tidb/pull/38655
    - [x] Deprecate serverMemoryQuota and inherit the values from old cluster. https://github.com/pingcap/tidb/pull/38628
- [x] Take the initiative to trigger GC: When the memory usage of the TiDB instance reaches `tidb_server_memory_limit` * `tidb_server_memory_limit_gc_trigger`, try to trigger GC https://github.com/pingcap/tidb/pull/38179
- [x] Introduce some memory tables: Introduce some memory tables to observe the memory usage of the current system. https://github.com/pingcap/tidb/pull/38452

**Test**

- [x] Function test https://github.com/pingcap/endless/pull/1120
- [x] Performance test
- [x] Compatibility test
