### ISSUE TITLE
Support REORGANIZE PARTITION Key Dev Task

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#38535]
# Support Reorganize Partition Dev Task

Related Issues: #15000
Design PR:
- [x] https://github.com/pingcap/tidb/pull/38246

## Dev Tasks
- [x] Parser support
- [x] Copy records, #38460
- [x] Recreate the indexes in the new partitions, #38460
- [x] Double write data in foreground sessions (concurrent DML during DDL), #38508
- [x] Handle `reorganize partition` command in ddl_api.go and ddl.go, #40473
- [x] Error handling and DDL rollback, #40543
- [x] Delete range of old partitions, #40543
- [x] Update Table handling, #40714
- [ ] TiFlash handling, #40715
- [x] Add telemetry for reorganize partition, #40258
- [ ] Support in TiFlash https://github.com/pingcap/tiflash/issues/6444
- [ ] Support in TiCDC https://github.com/pingcap/tiflow/pull/8114
