### ISSUE TITLE
FD: Bi-Directional Replication for ticdc

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#38587]
[background](https://docs.google.com/document/d/1_FlcaY9jfSY17f0fs_58rtCzau0w7Fi_9UBneC5A31U/edit)

## Task
- [x] add a system variable in tidb and `txn_source` in kvcontext https://github.com/pingcap/tidb/pull/39159
- [x] add a new field `txn_source` in kvprotobuf https://github.com/pingcap/kvproto/pull/1010
- [x] a new field `txn_source` in `write_cf` https://github.com/tikv/tikv/issues/13779
