### ISSUE TITLE
memory-related improvement

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#42665]
## Enhancement
- [ ] query killed by global memory controller unexpectedly https://github.com/pingcap/tidb/issues/42662
- [ ] query with memory usage 0 be killed https://github.com/pingcap/tidb/issues/42664
- [ ] indexmerge exits slowly when Out Of Memory Quota panic is triggered https://github.com/pingcap/tidb/issues/42398
- [ ] Refine the error message of Out Of Memory Quota https://github.com/pingcap/tidb/issues/42044
- [ ] set the default value of tidb_mem_quota_query to min(5GB, 50%*MAX_MEM) https://github.com/pingcap/tidb/issues/42317
