### ISSUE TITLE
Support MySQL Partition management

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#42728]
## Enhancement
The following features exists in MySQL and should be supported in TiDB:
- [x] ADD PARTITION for HASH/KEY partitioned tables, #42476
- [x] COALESCE PARTITION for HASH/KEY partitioned tables, #42476
- [x] REMOVE PARTITIONING (turn a partitioned table to a non-partitioned table), #42907
- [x] ALTER TABLE t PARTITION BY, Add partitioning or completely re-partition a table, #42907

### Related tasks:
- [x] DEFAULT list partition (no longer needed for REMOVE PARTITIONING), #41537

**Comment by Defined2014** [comment]
I think this feature is finished, so close it.
