### ISSUE TITLE
feature: sql enhancement to TiDB backup/restore

### ISSUE THREAD

**Issue by BornChanger** [pingcap/tidb#42825]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB PiTR feature is not supported by SQL interface. And there is no interface to check the metadata for full backup or incremental backup.

**Describe the feature you'd like:**

1. SQL support to PiTR functions
2. SQL interface to retrieve backup metadata and task information

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Tasks**

***Interface***

- [x] SQL syntax support @BornChanger 
- [ ] Async Mode @YuJuncen 
- [ ] Logic complementation @YuJuncen @BornChanger
 
***New system tables***
- [ ] system table for BR
- [ ] system table for PiTR

***Metadata retrieval***
- [ ] #42913

***Compatibility and concurrency***
- [ ] SQL statement default parameter syncs with CLI
- [ ] No concurrent conflicting SQL statements TBD
- [ ] Checksum control @YuJuncen
