### ISSUE TITLE
Umbrella issue: Resource Control

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#43180]
### Basic Function development 
Expect in 6.6, 7.0.
   - [x] RFC: https://github.com/pingcap/tidb/blob/master/docs/design/2022-11-25-global-resource-control.md
   - [x] Trace Issue: https://github.com/pingcap/tidb/issues/38825 
   

### Optimize customer journeys
Expect in 7.1
   -  [x] Ease of use enhancement  
       - [x]  Estimate total RU in a cluster: CALIBRATE RESOURCE https://github.com/pingcap/tidb/issues/43212
       - [x] https://github.com/pingcap/tidb/issues/41972
       - [x] Metrics Optmize
   - [x] Performance Issue
       - [x] https://github.com/tikv/tikv/issues/14375
   - [ ] Dmclock Enhancement 
       - [ ] https://github.com/tikv/pd/issues/6335
   - [ ] Observability
       - [ ] Panel in Dashboard

### Manage maintenance tasks
 Manage maintenance tasks & bypass TiDB traffic  
#### Tools relative tasks
   - [ ] BR/Lightning
   - [ ] CDC/PITR
   - [ ] Checksum
#### Background task
   - [ ] DDL/Analyze
   
### Resource group privilege management

TBD
