### ISSUE TITLE
Tracking Issue of Background Resource Control

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#44517]
## Feature Description
In order to control the background tasks' resource usage, we plan to add an extra quota resource limit layer to the background jobs. That is, for foreground jobs, on the tikv side, the scheduler only controls the enqueue/deque order. Thus, running tasks is not under control, and tasks from different routine(thread pool) are not controlled either. But for the background jobs, the extra quota limiter layer can ensure the running tasks(in different pools) can be preempted early enough, so their resource usage can appeal to the setting:
- **Control the resource usage of all background tasks by the Resource  Limiter** : The rate limit is dynamically adjusted to the value via the formula TiKVTotalRUCapcity - sum(RUCostRateOfForgroundTasks), with a fine-grained adjusting duration, we can ensure the foreground tasks' RU is always enough(or near the system's maximum if the foreground requirement reaches the maximum quota), so the background tasks' impact on foregroup tasks should be very low; on the other hand,  when the foreground resource consumption is low, the controller should increase the limit threshold, so background jobs can take advantage of the remaining resources.
- **The local resource manager will statics RU consumption of background jobs via the Resource Limiter** : We will  do statistics and report the resource consumption to the global resource manager. In the first stage, we only do statistics globally but control it locally.
- **Feedback mechanism**: It's better to give feedback on how fast the limiter layer executes tasks on tikv to the upper layer like tidb, so that the upper layer task framework can adjust the number of tasks.

### Management
- [x]  Interface
    - [x] Add SQL syntax to config resource group background setting #45189
    - [x] Add session variable to set the task type of current session #44770
    - [x] All Background REF_GROUP set to `Default`, and relative API 
- [x] Label the task as a background task and the {group_name@lightning  @nolouch  @HuSharp 
     - [x] Lightning https://github.com/pingcap/tidb/issues/44769
           - [ ] TiDB @nolouch 
           - [ ] Local @HuSharp 
     - [x] BR
     - [x] DDL / ANALYZE?
     - [x] Verify seperate binary @HuSharp 
- [ ] Integrate into another component

### TiKV Resource Limiter https://github.com/tikv/tikv/issues/14900
- [x] Resource Group background-related metadata management  @glorv tikv/tikv#14921
- [x] Limiter Future Interface @glorv tikv/tikv#14931
- [x] Background resource limiter and quota auto adjustment.  tikv/tikv#14980
- [x] Background tasks' RU consumption report @nolouch
