### ISSUE TITLE
Global Index for partitioned tables

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#45133]
## Enhancement

Development tasks for:
Make GLOBAL INDEX General Available

Stage 1 - full implementation, but Experimental

- [x] #48825
- Add tests for all index access plans. Create issues for handling the index access plans currently not supporting Global indexes (first disable the specific plan, then add support).
  - [x] memIndexReader and IndexReader https://github.com/pingcap/tidb/pull/52660
  - [x] memIndexLookUp and IndexLookUp
  - [x] memIndexMerge and IndexMerge https://github.com/pingcap/tidb/pull/52971
  - [x] pointGet and batchPointGet
- Tests 
  - [ ] Add tests for all write transactions (select lock, commit, rollback, different transaction modes, different transaction levels) * (insert, update, delete, select for update, single/multi statement transaction).
- DDL
  - ~~[ ] Support in EXCHANGE PARTITION? #54056~~ Will not support EXCHANGE PARTITION for Global Index, will cause too long state where double writing is needed. Better to add support for CONVERT PARTITION/TABLE instead, possibly later.
  - [x] Support in REORGANIZE PARTITION #53277
  - [x] Support in TRUNCATE PARTITION #55831
  - [x] Support in DROP PARTITION ? + #56082
- Admin
  - [x] #53439
  - [x] #53019
- Miscs
  - [x] #53342
  - [x] #55452 #56028

Stage 2 - Stabilise / General Available
- [x] Add docs https://github.com/pingcap/docs/pull/18543
- [ ] Fix reported bugs
- [x] Adjust syntax if needed https://github.com/pingcap/tidb/pull/55259
- [ ] Add more tests if needed
  - [x] https://github.com/pingcap/tidb/pull/57493
  - [x] #57623
  - [ ] https://github.com/pingcap/tiflow/pull/11651
- [x] Enable by default and remove experimental flag #56169

Optional / future enhancements
- [x] Change syntax, to enable (default) LOCAL index, and (explicit) GLOBAL index, #52994 
- [x] Consider path is global index path or not in `skylinePruning` function, let user easier to select global index. #56196

**Comment by Defined2014** [comment]
Maybe support for `indexMerge` and `UnionScan` can be added, it seems we are not considering global indexes in those related codes.

**Comment by 311ybb** [comment]
please make  global index   General Available faster, we  need it !

![image](https://github.com/pingcap/tidb/assets/88499339/5e6a9d33-45dd-477f-9d56-aead166b6d22)

**Comment by vonwind** [comment]
This is an urgently needed feature.

**Comment by mjonss** [comment]
ADD PARTITION is already supported, it uses the same logic as for TRUNCATE PARTITION, i.e. reading from the Global Index will filter away dropped/added partitions, so it will only show index entries from partitions the transaction/schema version sees. Currently filtered [here](https://github.com/pingcap/tidb/blob/44c9096efbc5b3a401f775c29559b160a492ee8c/pkg/planner/core/find_best_task.go#L2182).

**Comment by mjonss** [comment]
@Defined2014, for the global index, should there be some way to specify placement rules? I don't think there are any for normal indexes?

**Comment by Defined2014** [comment]
> @Defined2014, for the global index, should there be some way to specify placement rules? I don't think there are any for normal indexes?

I think it will follow table's placement rules and it is in line with my expectations. What do you think @mjonss ? And we could add some test cases for this.

**Comment by mjonss** [comment]
> I think it will follow table's placement rules and it is in line with my expectations. What do you think @mjonss ? And we could add some test cases for this.
@Defined2014 I expect the same, i.e. it will follow the table level's placement rules, so we should probably document it and add a test for it.

**Comment by Defined2014** [comment]
> > I think it will follow table's placement rules and it is in line with my expectations. What do you think @mjonss ? And we could add some test cases for this.
> 
> @Defined2014 I expect the same, i.e. it will follow the table level's placement rules, so we should probably document it and add a test for it.

I think the exists test cases already covered this situation(by check the key ranges for `pd.Rule`). And push a [doc commit](https://github.com/pingcap/docs/pull/17979/commits/7757de5230fd158c2cf89ebe18b2a1eadf690341) for it.

**Comment by mjonss** [comment]
Closing as done, Stage 2 completed. GA in v8.4 and included in LTS release v8.5.
Any future enhancements or issues should be using new Github issues.
