### ISSUE TITLE
planner: allow the optimizer to cache query plans accessing generated columns

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#45798]
### Work Item Tracking

- [x] A fix-control switch (False by default) to control whether to allow the optimizer to cache plans using generated columns and MVIndexes https://github.com/pingcap/tidb/pull/48011
- [x] Extend existing random UTs about MVIndexes to test Plan Cache + generated columns + MVIndex https://github.com/pingcap/tidb/pull/51314 
- [x] Collect all users' existing queries and add them as UTs https://github.com/pingcap/tidb/pull/51323
- [x] Collect related cases from `index.test` to test Plan Cache + MVIndex https://github.com/pingcap/tidb/pull/51483
- [x] Collect related cases from `multi_valued_index.test`, `multi_valued_index.test` to test Plan Cache + MVIndex https://github.com/pingcap/tidb/pull/51510
- [x] When encountering cases that `json_contains/overlaps` lead to uncacheable plans, choose to generate optimal plans without caching rather than caching sub-optimal plans https://github.com/pingcap/tidb/pull/51546
- [ ] Enable the fix-control switch by default after finishing all the above tasks https://github.com/pingcap/tidb/pull/51654

### Description
Currently, queries below are not allowed to be cached since these queries are accessing generated columns:
```
create table t1 (
    a int,
    info json,
    city varchar(64) as (JSON_UNQUOTE(JSON_EXTRACT(info, '$.city')))
);
prepare s1 from 'select * from t1 where a=?';
show warnings;

create table t2 (
    a int,
    info json,
    city varchar(64) as (JSON_UNQUOTE(JSON_EXTRACT(info, '$.city'))) virtual
);
prepare s2 from 'select * from t2 where a=?';
show warnings;

create table t3 (
    a int,
    info json,
    city varchar(64) as (JSON_UNQUOTE(JSON_EXTRACT(info, '$.city'))) stored
);
prepare s3 from 'select * from t3 where a=?';
show warnings;

create table t4 (
    a int,
    info json,
    index zips( (CAST(info->'$.zipcode' AS UNSIGNED ARRAY)))
);
prepare s4 from 'select * from t4 where a=?';
show warnings;
```

```
mysql> show warnings;
+---------+------+----------------------------------------------------------------------------+
| Level   | Code | Message                                                                    |
+---------+------+----------------------------------------------------------------------------+
| Warning | 1105 | skip prepared plan-cache: query accesses generated columns is un-cacheable |
+---------+------+----------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
