### ISSUE TITLE
Enhance distributed task execution framework

### ISSUE THREAD

**Issue by ywqzzy** [pingcap/tidb#46258]
## Enhancement
We need to make Distributed task framework implementation more modular, reduce complexity of implement, decouple the implemented and future function. Moreover, the framework must be more robust and easy to use.
1. By implementing a goroutine pool to control the concurrency of running tasks in the distributed framework, we can effectively prevent background tasks from consuming excessive compute resources and improve management scalability.
2. Use one Dispatcher take care one task, simplify the complexity of Dispatcher management.
3. The task status should follow the state machine, the whole procedure should be simple and easy to reasoning.
4. When the Dispatcher is in error status and does not work,  the impact scope can only be limited only to the task it takes care of. That means the dispatcher and scheduler's execution are decoupled. It will make the task run in distributed more robust.
5. Consider error handling of the task, make the task can be more robust when encountering many abnormal scenes.
6. Support cleanUp routines to do garbage collection for tasks.
7. Support subtask history table to provide more management of the framework.
8. Support metrics to maintain observability.
9. Support role to make the node selection policy more flexible.
10. Provide plan interface to make the whole execution process follow the plan, the business logic will be much clearer to trace and implement.
11. Introduce operator abstraction to make it easier to compose functionalities and provide more sophisticated task runtime statistics collect logic. Further more, the cpu resource should be easy to manage.
#### HA

- [x] 1. #45935 
- [x] 2. #47300 
- [x] 3. #47313
- [x] 4. #47334
- [x] 5. #47886 
- [x] 6. #48033 
- [x] 7. #48095 
- [x] 8. #48660 

#### Pause And Resume

- [x] Support pause and resume. #47037
#### CleanUp routine
- [x] 1. #47084
- [x] 2. #47179 
- [x] 3. #47218

#### Refinement

- [x] 1. #45460
- [x] 2. #45828 
- [x] 3. #45932 
- [x] 4. #45566
- [x] 5. #46497 
- [x] 6. #46357 
- [x] 7. #46472 
- [x] 8. #46603 
- [x] 9. #46669 
- [x] 10. #46686 
- [x] 11. #46722
- [x] 12. #46922
- [x] 13. #46952 
- [x] 14. #46913 
- [x] 15. #46957
- [x] 16. Refine onNextSubtasksBatch #46957 
- [x] 17. #47257 
- [x] 18. #47406 
- [x] 19. #47334 
- [x] 20. #47611 
- [x] 21. #47575 

#### role

- [x] 1. #46453 
- [x] 2. #47536 

#### dynamic dispatch subtasks

- [x] #46593

#### Introduce operator

- [x] 1. #46279 
- [x] 2. workerpool refine: #46185 

#### Integration

- [x] 1. add index basic: #46414 
- [x] 2. add index integration: #46495 
- [x] 3. import into: #46532 
- [x] 4. global sort: #46734 

#### Introduce planner

- [x] 1. #46395 

#### Integration
1. add index
2. import into: 

- [x] #46395 
- [x] #47982 

3. global sort

### SubTask runtime

- [x] 1. #46361 

### metrics
1. Support metric. #47017

### misc
- [x] 1. #45821 
- [x] 2. #46392 
- [x] 3. #46562

### bug fix

- [x] 1. #45790 
- [x] 2. #46259
- [x] 3. #46075 
- [x] 4. #46106
- [x] 5. #46464  
- [x] 6. #46603
- [x] 7.#46671
- [x] 8. #46674 
- [x] 9. #46735
- [x] 10.#46951
- [x] 11. #46938 
- [x] 12. #47207 
- [x] 13. #47251
- [x] 14. #47450
- [x] 15. #47316
- [x] 16. #47525 
- [x] 17. #47668 
- [x] 18. #48005 
- [x] 19. #47804
- [x] 20. #47914 
- [x] 21. #47744 
- [x] 22. #48339 
- [x] 23. #48366 
- [x] 24. #48343
- [x] 25. #48348 
- [x] 26. #48135 
- [x] 27. #48660
