### ISSUE TITLE
Setup OWNERS files in top folders

### ISSUE THREAD

**Issue by wuhuizuo** [pingcap/tidb#46911]
## Proposal

- [TiDB code owners Proposal](https://internals.tidb.io/t/topic/877)

## Enhancement

Setup OWNERS files in top folders and add experts as module approvers, we will brings advantages:

- Make assigning be appropriate and  reviewing be efficient.

Ref: 
- Mechanism implementation almost same with #45183

## Tasks
- [x] add `OWNERS` file for `autoid_service` folder. (#46912)
- [x] #46969
- [x] #47130
- [x] #47301
- [ ] add `OWNERS` file for `build` folder
- [ ] add `OWNERS` file for `cmd` folder
- [ ] add `OWNERS` file for `config` folder
- [x] #47844
- [x] #47088
- [x] #47845
- [ ] add `OWNERS` file for `docs` folder
- [x] #47798
- [x] #47843
- [ ] add `OWNERS` file for `errno` folder
- [ ] #47089
   - [x] #47875
- [x] #47090
- [ ] add `OWNERS` file for `extension` folder
- [ ] add `OWNERS` file for `hooks` folder
- [x] #47847
- [ ] add `OWNERS` file for `keyspace` folder
- [ ] add `OWNERS` file for `kv` folder
- [x] #47848
- [x] #47849
- [ ] add `OWNERS` file for `metrics` folder
- [x] #47850
- [x] #48748
- [x] #46970
- [ ] add `OWNERS` file for `plugin` folder
- [ ] add `OWNERS` file for `privilege` folder
- [x] #47852
- [ ] add `OWNERS` file for `script` folder
- [ ] add `OWNERS` file for `server` folder
- [ ] add `OWNERS` file for `session` folder
- [ ] add `OWNERS` file for `sessionctx` folder
- [ ] add `OWNERS` file for `sessiontxn` folder
- [x] #46971
- [ ] add `OWNERS` file for `store` folder
- [ ] add `OWNERS` file for `structure` folder
- [x] #47854
- [x] #47855
- [ ] add `OWNERS` file for `telemetry` folder
- [ ] add `OWNERS` file for `testkit` folder
- [ ] add `OWNERS` file for `tests` folder
- [x] #47846
- [ ] add `OWNERS` file for `tidb-server` folder
- [ ] add `OWNERS` file for `timer` folder
- [ ] add `OWNERS` file for `tools` folder
- [ ] add `OWNERS` file for `ttl` folder
- [ ] add `OWNERS` file for `types` folder
- [ ] add `OWNERS` file for `util` folder

**Comment by hi-rustin** [comment]
I don't believe we really need this. For example, how to find an owner of `util`?
