### ISSUE TITLE
Tracking Issue for Partition Statistics

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tidb#48126]
## Enhancement

In the past, there were issues with statistics information related to partition operations. Here are some examples:

1. https://github.com/pingcap/tidb/issues/39681 When we truncate a partition table, the global statistics remain unchanged.
2. https://github.com/pingcap/tidb/issues/47354 After we exchange a partition table, the global statistics remain unchanged.

This will impact how we generate the correct query plan. Therefore, we need to test all partition operations and fix any potential issues.

You can see more at: https://pingcap.feishu.cn/docx/VIW7d4I7KoXpx5xOsqRczZ1hnUc

Task list:

- [x] https://github.com/pingcap/tidb/issues/39681
- [x] https://github.com/pingcap/tidb/issues/47354
- [x] https://github.com/pingcap/tidb/issues/48182
- [x] https://github.com/pingcap/tidb/issues/48226
- [x] https://github.com/pingcap/tidb/issues/48235
- [x] https://github.com/pingcap/tidb/issues/48233
- [x] https://github.com/pingcap/tidb/issues/48231
- [ ] https://github.com/pingcap/tidb/issues/49547

**Comment by hi-rustin** [comment]
Test report: https://pingcap.feishu.cn/docx/XSnOdZ51IoxtjZxP3DwcOjwinoh?from=from_copylink

**Comment by hi-rustin** [comment]
Design doc: https://pingcap.feishu.cn/docx/OLCrdxHj2ojb9KxlUvUch60LnBe

**Comment by hi-rustin** [comment]
We are going to use the solution 2.

**Comment by hi-rustin** [comment]
The test report after fixing: https://pingcap.feishu.cn/docx/XPYIdC4Ihoc7jNxuPficBbOgn8g
