### ISSUE TITLE
Reduced memory usage (optimizations for some OOM scenarios)

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#50217]
## Enhancement
- [x] TiDB Server OOM when the table is large(8C/16G, 113k tables, no partition) https://github.com/pingcap/tidb/issues/49370
- [x] TiDB Server OOM when the table# and paration# is large(8C/32G, 540k tables, 2850k partitions) https://github.com/pingcap/tidb/issues/50077
- [x] TiDB Server OOM when the table is large(8C/16G, 130k tables, 650k partitions) https://github.com/pingcap/tidb/issues/50214
