### ISSUE TITLE
Tracking issues of restore performance improvement.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#50701]
## Enhancement

Tracking issues of restore performance in different stage. basically we have 4 stages during restoartion. 
```
1. Load Data from Storage. 
2. Create DB/Tables. 
3. Region Split & Scatter.  
4. Download & Ingest SST Files.
```

- [ ] (Stage 3) https://github.com/pingcap/tidb/issues/33937
    - [x] https://github.com/pingcap/tidb/pull/48244
    - [x] https://github.com/pingcap/tidb/pull/50255
- [ ] (Stage 4)https://github.com/pingcap/tidb/issues/49886
    - [x] https://github.com/pingcap/tidb/pull/49887
    - [x] https://github.com/tikv/tikv/pull/16298

## Bugfixs
Functional issues
- [x] https://github.com/pingcap/tidb/issues/50471
    - [x] https://github.com/pingcap/tidb/pull/50518

Performance issues
- [ ] https://github.com/pingcap/tidb/issues/50593
- [ ] https://github.com/pingcap/tidb/issues/50566
- [ ] https://github.com/pingcap/tidb/issues/50617
