### ISSUE TITLE
[tracking issue] Global sort 8.0 requirements

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#50752]
- [x] #50753
- [x] #50755
- [x] #50832
- [ ] IMPORT INTO can run in 8c16g node and with lower `thread` arguments
- [x] #50657
- [x] #51272
- [x] #51439
- [x] test global sort on S3
- [x] https://github.com/pingcap/tidb/issues/51505
- [x] https://github.com/pingcap/tidb/issues/51734
