### ISSUE TITLE
support NextChunk for executors

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#5261]
- [x] executor/aggregate.go: HashAggExec @spongedu #5244 
- [x] executor/aggregate.go: StreamAggExec @zz-jason #5490 
- [x] executor/analyze.go: AnalyzeExec @zz-jason #5452 
- [x] executor/ddl.go: DDLExec @zz-jason #5417 
- [x] executor/distsql.go: TableReaderExecutor @coocood #5142 
- [x] executor/distsql.go: IndexReaderExecutor @coocood #5142 
- [x] executor/distsql.go: IndexLookUpExecutor @coocood #5142 
- [x] executor/executor.go: CancelDDLJobsExec @zz-jason #5416 
- [x] executor/executor.go: ShowDDLExec @zz-jason #5415 
- [x] executor/executor.go: ShowDDLJobsExec @zz-jason #5412 
- [x] executor/executor.go: CheckTableExec @zz-jason #5407 
- [x] executor/executor.go: SelectLockExec @zz-jason #5399 
- [x] executor/executor.go: LimitExec @zz-jason #5200 
- [x] executor/executor.go: ProjectionExec @zz-jason #5178 
- [x] executor/executor.go: TableDualExec @zz-jason #5395 
- [x] executor/executor.go: SelectionExec @zz-jason #5211 
- [x] executor/executor.go: TableScanExec @zz-jason #5443 
- [x] executor/executor.go: ExistsExec @zz-jason #5396 
- [x] executor/executor.go: MaxOneRowExec @zz-jason #5281 
- [x] executor/executor.go: UnionExec @zz-jason #5229 
- [x] executor/explain.go: ExplainExec @zz-jason #5398 
- [x] executor/grant.go: GrantExec @zz-jason #5459 
- [x] executor/index_lookup_join.go: IndexLookUpJoin @coocood #5382 
- [x] executor/join.go: HashJoinExec @XuHuaiyu #5439 
- [x] executor/join.go: NestedLoopApplyExec @coocood #5475
- [x] executor/merge_join.go: MergeJoinExec @zz-jason #5312 
- [x] executor/prepared.go: PrepareExec @zz-jason #5408 
- [x] executor/prepared.go: ExecuteExec @zz-jason #5410 
- [x] executor/prepared.go: DeallocateExec @zz-jason #5457 
- [x] executor/revoke.go: RevokeExec @zz-jason 
- [x] executor/set.go: SetExecutor @zz-jason #5397 
- [x] executor/show.go: ShowExec @zz-jason #5456 
- [x] executor/simple.go: SimpleExec @zz-jason #5453 
- [x] executor/sort.go: SortExec @coocood #5221 
- [x] executor/sort.go: TopNExec @coocood #5260 
- [x] executor/union_scan.go: UnionScanExec @zz-jason #5432 
- [x] executor/write.go: DeleteExec @winkyao #5368 
- [x] executor/write.go: LoadData @winkyao #5465
- [x] executor/write.go: InsertExec @winkyao #5352
- [x] executor/write.go: ReplaceExec @winkyao #5370 
- [x] executor/write.go: UpdateExec @winkyao #5372

**Comment by spongedu** [comment]
@zz-jason I'll support `StreamAggExec` in #5244 since the modification for aggregation functions are the same.

**Comment by zz-jason** [comment]
@spongedu OK.

**Comment by zz-jason** [comment]
All PRs are merged, task done!

**Comment by spongedu** [comment]
big con~

**Comment by shenli** [comment]
Good job!
