### ISSUE TITLE
improve the usability of DDL Job.Args

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#53930]
## Enhancement

Currently Job.Args is like a type-erasure field https://github.com/pingcap/tidb/blob/fedf3b7ba9a841e90de55cc3c4c1b037343f2339/pkg/parser/model/ddl.go#L514-L522
It's hard to find all usage of a DDL job type arguments and maintain them.

![image](https://github.com/pingcap/tidb/assets/1689766/ac9a756d-efa0-4949-bbf3-589ee14debaf)

idea 1: I think it's better to have a specialized `struct` for each DDL job type. So the developer can directly find all usage of a DDL job type among all types.

idea 2: don't change old format of the serialized Job.RawArgs, the new `struct`s should handle the serialization/deserialization in the old format. The advantage is we don't need to handle the compatibility of DDL jobs written by old version clusters.

# Tasks
- [x] https://github.com/pingcap/tidb/pull/55634
- [x] https://github.com/pingcap/tidb/pull/55754
- [x] https://github.com/pingcap/tidb/pull/55854
- [x] https://github.com/pingcap/tidb/pull/55919
- [x] https://github.com/pingcap/tidb/pull/55964
- [x] https://github.com/pingcap/tidb/pull/56153
- [x] https://github.com/pingcap/tidb/pull/56163
- [x] https://github.com/pingcap/tidb/pull/56219
- [x] https://github.com/pingcap/tidb/pull/56222
- [x] https://github.com/pingcap/tidb/pull/56242
- [x] https://github.com/pingcap/tidb/pull/56269
- [x] https://github.com/pingcap/tidb/pull/56400
- [x] https://github.com/pingcap/tidb/pull/56417
- [x] https://github.com/pingcap/tidb/pull/55946
- [x] https://github.com/pingcap/tidb/pull/56010
- [x] https://github.com/pingcap/tidb/pull/56130
- [x] https://github.com/pingcap/tidb/pull/56536
- [x] https://github.com/pingcap/tidb/pull/56186
- [x] https://github.com/pingcap/tidb/pull/56194
- [x] https://github.com/pingcap/tidb/pull/56290
- [x] https://github.com/pingcap/tidb/pull/55959
- [x] https://github.com/pingcap/tidb/pull/56021
- [x] https://github.com/pingcap/tidb/pull/56164
- [x] https://github.com/pingcap/tidb/pull/56206
- [x] https://github.com/pingcap/tidb/pull/56241
- [x] https://github.com/pingcap/tidb/pull/56337

**Comment by lance6716** [comment]
And for one type of DDL jobs, the `Args` may change so the marshal field `RawArgs` is hard to maintain

For example, DROP DATABASE will have a `bool` as `Args` at first

https://github.com/pingcap/tidb/blob/d19fc99ec6d39e4bc582bd4484f331ff4405df82/pkg/ddl/ddl_api.go#L685-L687

but somehow it becomes `[]int64`

https://github.com/pingcap/tidb/blob/d19fc99ec6d39e4bc582bd4484f331ff4405df82/pkg/ddl/delete_range.go#L284-L286
