### ISSUE TITLE
Tracking issue for speed up PiTR by pre-compacting logs

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#56522]
## Enhancement

For now PiTR is slow. Because we need:

- Download the logs to the leader.
- Leader duplicating the mutations to all peers by raft (Requires a sync of Disk). 
- Sort this run in the memtable.
- Flush and compact the mutations in the LSM tree.

This routine includes many overheads:

- Write amplification.
- Sorting the mutations.
- One extra write in the raft engine.

We may "pre-compact" the backup data to SSTs, and use the `download`/ `ingest` API to put them into the cluster.

#### Generate SSTs from Logs Offline  

- https://github.com/tikv/tikv/issues/17283

  - [x] https://github.com/tikv/tikv/pull/17284
  - [x] https://github.com/tikv/tikv/pull/17406
  - [x] https://github.com/tikv/tikv/issues/17631
  - [x] https://github.com/tikv/tikv/pull/17844

This Issue tracks the subcommand `compact-log-backup` of `tikv-ctl`.

#### Support local log encryption
- [ ] https://github.com/tikv/tikv/issues/18337

#### Manage the Metadata of Compactions

- [x]  https://github.com/pingcap/tidb/issues/55661
- [x]  https://github.com/pingcap/tidb/issues/56523
- [x]  https://github.com/pingcap/tidb/issues/56758
- [x]  https://github.com/pingcap/tidb/issues/56760
- [x] https://github.com/pingcap/tidb/issues/57540

We will introduce the migration system for log backup storages. Generally, we now modify the "stabilized" logs by putting an atomic "migration".

#### Point in Time Restore with SSTs

The whole changes is in https://github.com/pingcap/tidb/pull/54813
- [x] https://github.com/pingcap/tidb/pull/56917/
- [x] #57210
- [x] #57209
- [x] #57212
- [x] #57535
- [x] #58733

#### Implement a More Friendly User Interface.

- Implement the TiDB Operator interface for compacting 
- [x] logs https://github.com/pingcap/tidb-operator/pull/5822
- [x] https://github.com/pingcap/tidb-operator/pull/6033)
- [x] https://github.com/pingcap/tidb-operator/pull/6103
- [x] https://github.com/pingcap/tidb-operator/pull/6167

#### General Workload

This is an internal workload, with:
- **Cluster Size**: 23 TB
- **QPS**: 6k inserts/18k updates

_(Short Duration Compaction)_ Restore Performance:
- **Log Restore**: Completed in 2 hours(24 hours data Retention)
- **Log Restore with Log Compaction**: Completed in 40 minutes (There's still room for improvement：As the data in the log backup retention period grows, the effectiveness of compaction improves, demonstrating an optimization effect that exceeds linear growth, because of less write amplification and less Raft I/O)

_(Long Duration Compaction)_ Restore Performance:
- **Log Restore**: There is data skew during restoring hence the disk space isn't enough. We scaled out to 10 TiKV stores. The restore takes 10 hours to finish with several breaks(break due to disk almost full, because compact SST consumes too many space during log restore, so it will take much more space when restore with a longer interval(7 days)).
- **Log Restore with Log Compaction**: Without split, we finished the restoration in about 3hrs.
