### ISSUE TITLE
br: add table filter for Pitr restore

### ISSUE THREAD

**Issue by Tristan1900** [pingcap/tidb#57613]
## Feature Request

Right now only snapshot backup/restore supports filter, users are asking for Pitr to support it. We only need to add filter for log restore but not backup

Need to consider table rename corner cases
1. table renamed into the filter during log replay should be kept after restore
2. table renamed out of filter range during log replay should be dropped after restore
3. Should naturally works with insertGCRow, repairIndex and TiFlash

### Tasks:
  - [x] https://github.com/pingcap/tidb/pull/58112 
  - [x] https://github.com/pingcap/kvproto/pull/1294
  - [x] https://github.com/pingcap/tidb/pull/57394
  - [x] https://github.com/pingcap/tidb/pull/59683
  - [x] https://github.com/pingcap/tidb/pull/59678
  - [x] https://github.com/pingcap/tidb/pull/59359
  - [ ] https://github.com/pingcap/tidb/pull/59281 (depends on https://github.com/pingcap/tidb/pull/59009)
