### ISSUE TITLE
remove Next() function of all the Executors

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#5985]
We no longer need `Next()` for executors since we already have `NextChunk()`. Function `Next()` and all the functions and attributes called only by `Next()` should also be deleted.

After removing `Next()`, we can detect the unused functions by tool `unused`:
```go
go get honnef.co/go/tools/cmd/unused
unused github.com/pingcap/tidb/executor
```

NOTE: 
1. all the unused functions and attributes should be deleted.
2. some unit tests may fail and please fix them.

-----
- [x] executor/aggregate.go: HashAggExec @lwhile #5987 
- [x] executor/aggregate.go: StreamAggExec @hsqlu #6017 
- [x] executor/analyze.go: AnalyzeExec @colinback #6012 
- [x] executor/ddl.go: DDLExec @colinback #6013
- [x] executor/distsql.go: TableReaderExecutor @wsabc01 #6146 
- [x] executor/distsql.go: IndexReaderExecutor @CocaLi #6165 
- [x] executor/distsql.go: IndexLookUpExecutor  @lhyPingcap #6145 
- [x] executor/executor.go: CancelDDLJobsExec @qxhy123 #6060 
- [x] executor/executor.go: ShowDDLExec @qxhy123 #6059  
- [x] executor/executor.go: ShowDDLJobsExec @qxhy123 #6058 
- [x] executor/executor.go: CheckTableExec @qxhy123 #6057 
- [x] executor/executor.go: SelectLockExec @qxhy123 #6056 
- [x] executor/executor.go: LimitExec @qxhy123 #6055 
- [x] executor/executor.go: ProjectionExec @qxhy123 #6023 
- [x] executor/executor.go: TableDualExec @qxhy123 #6022 
- [x] executor/executor.go: SelectionExec @qxhy123 #6021 
- [x] executor/executor.go: TableScanExec @qxhy123 #6020 
- [x] executor/executor.go: ExistsExec @qxhy123 #6019 
- [x] executor/executor.go: MaxOneRowExec @qxhy123 #6018 
- [x] executor/executor.go: UnionExec @qxhy123 #6016 
- [x] executor/explain.go: ExplainExec @yangwenmai #6002 
- [x] executor/grant.go: GrantExec @colinback #5999 
- [x] executor/index_lookup_join.go: IndexLookUpJoin @XuHuaiyu #5994 
- [x] executor/join.go: HashJoinExec @XuHuaiyu #5991 
- [x] executor/join.go: NestedLoopApplyExec @yangwenmai #6027 
- [x] executor/merge_join.go: MergeJoinExec @XuHuaiyu #5993 
- [x] executor/prepared.go: PrepareExec @yangwenmai #6003 
- [x] executor/prepared.go: ExecuteExec @yangwenmai #6003 
- [x] executor/prepared.go: DeallocateExec @yangwenmai #6003 
- [x] executor/revoke.go: RevokeExec @yangwenmai #6004 
- [x] executor/set.go: SetExecutor @yangwenmai #6005 
- [x] executor/show.go: ShowExec @Anteoy #5998 
- [x] executor/simple.go: SimpleExec @yangwenmai #6001 
- [x] executor/sort.go: SortExec @hsqlu #6052 
- [x] executor/sort.go: TopNExec @hsqlu  #6029 
- [x] executor/union_scan.go: UnionScanExec @yangwenmai #5996 
- [x] executor/write.go: DeleteExec @yangwenmai #5995 
- [x] executor/write.go: LoadData @yangwenmai #5995 
- [x] executor/write.go: InsertExec @yangwenmai #5995 
- [x] executor/write.go: ReplaceExec @yangwenmai #5995 
- [x] executor/write.go: UpdateExec @yangwenmai #5995

**Comment by ngaut** [comment]
Feels really great to see the thread. 👍

**Comment by qxhy123** [comment]
I'm working on it

**Comment by XuHuaiyu** [comment]
We can remove the code of XXXExec.Next(),
and `return nil, nil` in it.
To avoid wide range code changes in one PR.

**Comment by dreamquster** [comment]
I'm working on it.  I will remove next() function in distsql.go.

 executor/distsql.go: TableReaderExecutor
 executor/distsql.go: IndexReaderExecutor
 executor/distsql.go: IndexLookUpExecutor

**Comment by zz-jason** [comment]
@qxhy123 @dreamquster Thanks for your help !

**Comment by qxhy123** [comment]
I'm working on it. I will remove next() function in executor.go.
 executor/executor.go: CancelDDLJobsExec
 executor/executor.go: ShowDDLExec
 executor/executor.go: ShowDDLJobsExec
 executor/executor.go: CheckTableExec
 executor/executor.go: SelectLockExec
 executor/executor.go: LimitExec
 executor/executor.go: ProjectionExec
 executor/executor.go: TableDualExec
 executor/executor.go: SelectionExec
 executor/executor.go: TableScanExec
 executor/executor.go: ExistsExec
 executor/executor.go: MaxOneRowExec
 executor/executor.go: UnionExec

**Comment by yangwenmai** [comment]
I'm working on it.  I will remove next() function in `executor/write.go`.

 executor/write.go: DeleteExec
 executor/write.go: LoadData
 executor/write.go: InsertExec
 executor/write.go: ReplaceExec
 executor/write.go: UpdateExec

**Comment by yangwenmai** [comment]
I'm working on it. I will remove next() function in `executor/union_scan.go`.

executor/union_scan.go: UnionScanExec

**Comment by colinback** [comment]
I'm working on it. I will remove next() function in
executor/analyze.go: AnalyzeExec 
 executor/ddl.go: DDLExec

**Comment by zz-jason** [comment]
@colinback Thanks for your participation, `AnalyzeExec` and `DDLExec` have been assigned to @XuHuaiyu , please chose other executors.

**Comment by Anteoy** [comment]
I'm working on it. I will remove next() function in `executor/show.go`.

executor/show.go: ShowExec

**Comment by colinback** [comment]
@zz-jason Oh sorry, I do not notice that.  Then I choose to do executor/grant.go: GrantExec first.
BTW, have dead line?

**Comment by XuHuaiyu** [comment]
@Anteoy Thanks for your help.

**Comment by XuHuaiyu** [comment]
@colinback It would be great if you can finish it before next Wednesday.

**Comment by dreamquster** [comment]
@XuHuaiyu ， All executors in distsql.go are referenced by RecordSet.Next. Should I change all RecordSet.Next into RecordSet.NextChunk in below picture?
![_ _20180310205746](https://user-images.githubusercontent.com/4962716/37242557-63fd300a-24a6-11e8-9913-7221ef241801.png)

**Comment by yangwenmai** [comment]
I'm working on it. I will remove next() function in `executor/simple.go`.
executor/simple.go: SimpleExec

**Comment by yangwenmai** [comment]
I'm working on it. I will remove next() function in `executor/explain.go`.
executor/explain.go: ExplainExec

**Comment by yangwenmai** [comment]
I'm working on it. I will remove next() function in `executor/prepared.go`.
executor/prepared.go: PrepareExec
executor/prepared.go: ExecuteExec
executor/prepared.go: DeallocateExec

**Comment by yangwenmai** [comment]
I'm working on it. I will remove next() function in `executor/revoke.go`.
executor/revoke.go: RevokeExec

**Comment by yangwenmai** [comment]
I'm working on it. I will remove next() function in `executor/set.go`.
executor/set.go: SetExecutor

**Comment by XuHuaiyu** [comment]
@dreamquster Thank you for your help, I'm working on this.

**Comment by XuHuaiyu** [comment]
@colinback Feel free if you wanna try `executor/analyze.go: AnalyzeExec` and 
`executor/ddl.go: DDLExec`, I haven't stared them yet.

**Comment by colinback** [comment]
@XuHuaiyu I'm OK with it. But I have two problems now.
1. I do not pass CLA, but I already sign 'Contributor License Agreement '
2. After migrating go version to 1.10, `go test` still fail for master branch. 
```
OOPS: 74 passed, 1 skipped, 1 FAILED
--- FAIL: TestT (104.67s)
FAIL
exit status 1
FAIL   	github.com/pingcap/tidb	104.698s
```

**Comment by XuHuaiyu** [comment]
For question 2:
Try `go version`, what's the output?
Upload the output result of `go test`, we'll take a look.

**Comment by XuHuaiyu** [comment]
For question 1:
You may check [here](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by colinback** [comment]
For question 2, here is my `go test` log:
[go_test_fail.log](https://github.com/pingcap/tidb/files/1800000/go_test_fail.log)
For question 1, I forget that I set company email for enterprise github on my macbook. Already fix.

**Comment by XuHuaiyu** [comment]
@colinback Thank you, we'll take a look.

**Comment by XuHuaiyu** [comment]
@colinback The test fail is caused by [the introduction of gofail](https://github.com/pingcap/tidb/blob/master/txn.go#L264-L267). You can run `go test -check.exclude TestFail` OR `make test` at the root directory of TiDB.

**Comment by colinback** [comment]
@XuHuaiyu thanks. It works

**Comment by hsqlu** [comment]
I am working on it. I will remove next() function in executor/aggregate.go.
executor/aggregate.go: StreamAggExec

**Comment by hsqlu** [comment]
I am working on it. I will remove next() function in executor/sort.go.
 executor/sort.go: SortExec
 executor/sort.go: TopNExec

**Comment by yangwenmai** [comment]
I am working on it. I will remove next() function in `executor/join.go`.
executor/join.go: NestedLoopApplyExec

**Comment by XuHuaiyu** [comment]
Hi, a friendly ping. @dreamquster 
Did you get any problems when removing the Next function for these three Executors?
executor/distsql.go: TableReaderExecutor 
executor/distsql.go: IndexReaderExecutor 
executor/distsql.go: IndexLookUpExecutor

**Comment by dreamquster** [comment]
@XuHuaiyu , I found that all executors in distsql.go are referenced in too many places on March 10.

**Comment by XuHuaiyu** [comment]
Hi, @dreamquster
This has been resolved in https://github.com/pingcap/tidb/pull/6040

**Comment by XuHuaiyu** [comment]
done
