### ISSUE TITLE
Support remaining JSON functions from MySQL 5.7

### ISSUE THREAD

**Issue by mccxj** [pingcap/tidb#7546]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

scalar function. See https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html
- [X] JSON_TYPE
- [X] JSON_EXTRACT
- [X] -> equivalent to JSON_EXTRACT()
- [X] ->> equivalent to JSON_UNQUOTE(JSON_EXTRACT())
- [X] JSON_UNQUOTE
- [X] JSON_ARRAY
- [x] JSON_ARRAY_APPEND @erjiaqing #9609
- [x] JSON_ARRAY_INSERT @foreyes #11076 
- [X] JSON_OBJECT
- [X] JSON_MERGE
- [ ] JSON_MERGE_PATCH
- [x] JSON_MERGE_PRESERVE @shinytang6 #8931
- [x] JSON_VALID @kuafou #7727 @Reminiscent #12596
- [X] JSON_SET
- [X] JSON_INSERT
- [X] JSON_REPLACE
- [X] JSON_REMOVE
- [X] JSON_CONTAINS  @mccxj https://github.com/pingcap/tidb/pull/7443
- [X] JSON_CONTAINS_PATH @xiangyuf https://github.com/pingcap/tidb/pull/7596
- [ ] JSON_PRETTY
- [x] JSON_QUOTE @overbool #7832
- [x] JSON_SEARCH @pingyu #8704
- [x] JSON_STORAGE_SIZE
- [x] JSON_DEPTH @pingyu https://github.com/pingcap/tidb/pull/8347
- [x] JSON_KEYS @Kingwl #7776
- [X] JSON_LENGTH @Kingwl #7739

aggregate function. See https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html

- [ ] JSON_ARRAYAGG @Kingwl #7824
- [x] JSON_OBJECTAGG @Kingwl #7824

**Comment by xiangyuf** [comment]
I will implement JSON_CONTAINS_PATH

**Comment by zz-jason** [comment]
@mccxj The aggregate functions list here are duplicated with https://github.com/pingcap/tidb/issues/7623

**Comment by morgo** [comment]
For `JSON_MERGE_PRESERVE`: `JSON_MERGE` should be renamed to this, and `JSON_MERGE` can become an alias to `JSON_MERGE_PRESERVE`.

**Comment by morgo** [comment]
I am working on updating the JSON documentation in https://github.com/pingcap/docs/pull/656

**Comment by morgo** [comment]
@erjiaqing thank you for working on `json_array_append`!  Are you interested on working on `json_array_insert` ? 😄 😄

**Comment by wwar** [comment]
JSON_STORAGE_SIZE can be checked off as complete. I have manually verified it works.

**Comment by nullnotnil** [comment]
I am going to close this issue in favor of https://github.com/pingcap/tidb/issues/14486

There is duplication between these issues, and 14486 is a better representation of what issues are outstanding.
