### ISSUE TITLE
Call For Participation: finish the unsupported aggregate functions

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#7623]
All issues are open and welcomed to contributors. You can join **#sig-exec** on [tidb community slack](https://pingcap.com/tidbslack/) to discuss and get help from someone.

## Description

At present, the aggregate functions that TiDB supports are:
- `AVG()`
- `BIT_AND()`
- `BIT_OR()`
- `BIT_XOR()`
- `COUNT()`
- `COUNT(DISTINCT)`
- `GROUP_CONCAT()`
- `MAX()`
- `MIN()`
- `SUM()`

In order to be compatible with MySQL and Improve the usability of TiDB, the following functions should also be supported in TiDB:

| Name               | Description                               |
|--------------------|-------------------------------------------|
| `STD()`            | Alias for `STDDEV_POP` function  |
| `STDDEV()`         | Alias for `STDDEV_POP` function  |
| `STDDEV_POP()`     | Return the population standard deviation  |
| `STDDEV_SAMP()`    | Return the sample standard deviation      |
| `VARIANCE()`       | Return the population standard variance   |
| `VAR_POP()`        | Return the population standard variance   |
| `VAR_SAMP()`       | Return the sample variance                |
| `JSON_ARRAYAGG()`  | Return result set as a single JSON array  |
| `JSON_OBJECTAGG()` | Return result set as a single JSON object |

An implementation checklist:

- [x] `STD()`/`STDDEV()`/`STDDEV_POP()` @Win-Man  #19195
- [x] `STDDEV_SAMP()`  @Win-Man #19810
- [x] `VARIANCE()`/`VAR_POP()` @githubFZX #14101 
- [x] `VAR_SAMP()` @Win-Man #19810
- [ ] `JSON_ARRAYAGG()`  https://github.com/pingcap/tidb/pull/19957
- [x] `JSON_OBJECTAGG()` @hg2990656 #11154 

## Difficulty

* Medium

## Score 

* 3000

## Mentor(s)

* @qw4990

## Recommended Skills

* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by Win-Man** [comment]
pick up
[] STD()/STDDEV()/STDDEV_POP()
[] STDDEV_SAMP()

**Comment by Blue-Sail** [comment]
/Pick up

JSON_ARRAYAGG()

**Comment by Blue-Sail** [comment]
pick up

**Comment by Blue-Sail** [comment]
/pick-up 
JSON_ARRAYAGG()

**Comment by LebronAl** [comment]
/pick-up
STDDEV_SAMP()
VAR_SAMP()

**Comment by LebronAl** [comment]
/pick-up 
VARIANCE()

**Comment by LebronAl** [comment]
> This issue already picked by Blue-Sail.

It seems that this function has not been implemented or picked?And he seems only pick JSON_ARRAYAGG()?
