### ISSUE TITLE
Add remaining Information Functions

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#8438]
From the [MySQL manual](https://dev.mysql.com/doc/refman/5.7/en/information-functions.html):

- [x] BENCHMARK()	Repeatedly execute an expression https://github.com/pingcap/tidb/pull/9252
- [ ] CHARSET()	Return the character set of the argument https://github.com/pingcap/tidb/issues/3931
- [x] COERCIBILITY()	Return the collation coercibility value of the string argument https://github.com/pingcap/tidb/issues/4056
- [x] COLLATION()	Return the collation of the string argument
- [x] CONNECTION_ID()	Return the connection ID (thread ID) for the connection
- [x] CURRENT_USER(), CURRENT_USER	The authenticated user name and host name
- [x] DATABASE()	Return the default (current) database name
- [ ] FOUND_ROWS()	For a SELECT with a LIMIT clause, the number of rows that would be returned were there no LIMIT clause (**Exists, but not correctly implemented**) https://github.com/pingcap/tidb/issues/8235
- [x] LAST_INSERT_ID()	Value of the AUTOINCREMENT column for the last INSERT
- [x] ROW_COUNT()	The number of rows updated (**Limited; hard to impliment in optimistic system**)
- [x] SCHEMA()	Synonym for DATABASE()
- [x] SESSION_USER()	Synonym for USER()
- [x] SYSTEM_USER()	Synonym for USER()
- [x] USER()	The user name and host name provided by the client
- [x] VERSION()	Return a string that indicates the MySQL server version

**Comment by wwar** [comment]
`COLLATION()` and `COERCIBILITY()` can be checked as complete.

`CHARSET()` is still not done, and `FOUND_ROWS()` is still broken.

**Comment by nullnotnil** [comment]
I am going to close this issue now. There are only two remaining functions, and both have dedicated issues to track them. Thanks!
