### ISSUE TITLE
Tracking view feature implement

### ISSUE THREAD

**Issue by AndrewDi** [pingcap/tidb#8520]
This issue is to track view feature implement. proposal is from #8416 .

 ### CREATE VIEW

- [x] ast, parser: extract create view parameters to CreateViewStmt  https://github.com/pingcap/parser/pull/55
- [x] model, parser: add viewinfo struct to `TableInfo` https://github.com/pingcap/parser/pull/55
- [x] model, parser: add ActionCreateView to ddl actionMap https://github.com/pingcap/parser/pull/55
- [x] ddl, tidb: implement create view with basic column check #8571 
- [x] ddl, tidb: add OrReplace support when create view #8856 
- [x] test, tidb: add some test cases for CreateView
- [ ] ddl, tidb: view algorithm support derived_merge flag of the optimizer_switch system variable
- [x] dml, tidb: implement `CREATE_VIEW_PRIV` privileges check https://github.com/pingcap/parser/pull/138 #9153 
- [x] ddl, tidb: expand select's wildcard #11818 

### DROP VIEW
- [x] ast, parser: implement drop view parse https://github.com/pingcap/parser/pull/67 https://github.com/pingcap/parser/pull/131
- [x] ddl, tidb: implement drop view func #8758 

### SHOW TABLE STATUS
- [ ] add func to support show view status

### SELECT FROM VIEW
- [x] modify func `BuildDataSource` to rewrite view #8757 
- [x] support view `SQL SECURITY` privilege check #9194 
### SHOW FULL TABLS
- [x] executor: alter func to support show view #8860

### DESCRIBE TABLE
- [x] executor: alter func to support desc view #8863 

### SHOW CREATE TABLE
- [x] executor: alter func to support show create view definition #8865 

### Information Schema
- [x] infoschema: support for views https://github.com/pingcap/tidb/issues/8889

### ALTER TABLE
- [x] ddl: ALTER TABLE should not permit on VIEW #8890

**Comment by morgo** [comment]
Can I help you with the infoschema implementation?  I can see two issues:
1. omit views from `information_schema.tables`.
2. add views to `information_schema.views`.

**Comment by AndrewDi** [comment]
> Can I help you with the infoschema implementation? I can see two issues:
> 
> 1. make `information_schema.tables` show `table_type`, `comment` as view.   All remaining columns as NULL.
> 2. add views to `information_schema.views`.

@morgo Sure, Do you check validity of view during select from `information_schema.views` and `information_schema.tables`?

**Comment by morgo** [comment]
@AndrewDi I don't think so.  Two things to mention though:
* The mysql server itself did not have view dependency tracking until MySQL 8.0.  So we are 100% compatible to have views that will not work when queried.
* I know of [this issue](https://github.com/pingcap/tidb/issues/8130) where metadata could have been created that is broken.  But I think these should only be corrected/handled on read if there was a persistent data bug in a GA version.

I will create an issue to support `informaiton_schema`.

**Comment by AndrewDi** [comment]
@morgo I have do some test on MySQL 5.7, and it seems like already have view dependency tracking?
```sql
mysql> create table t1(a int,b int);
Query OK, 0 rows affected (0.45 sec)

mysql> create view v as select * from t1;
Query OK, 0 rows affected (0.06 sec)

mysql> drop table t1;
Query OK, 0 rows affected (0.20 sec)

mysql> select * from information_schema.views where table_schema='test';
+---------------+--------------+------------+-----------------------------------------------------------------------+--------------+--------------+----------------+---------------+----------------------+----------------------+
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | VIEW_DEFINITION                                                       | CHECK_OPTION | IS_UPDATABLE | DEFINER        | SECURITY_TYPE | CHARACTER_SET_CLIENT | COLLATION_CONNECTION |
+---------------+--------------+------------+-----------------------------------------------------------------------+--------------+--------------+----------------+---------------+----------------------+----------------------+
| def           | test         | v          | select `test`.`t1`.`a` AS `a`,`test`.`t1`.`b` AS `b` from `test`.`t1` | NONE         |              | root@localhost | DEFINER       | latin1               | latin1_swedish_ci    |
+---------------+--------------+------------+-----------------------------------------------------------------------+--------------+--------------+----------------+---------------+----------------------+----------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+--------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                  |
+---------+------+--------------------------------------------------------------------------------------------------------------------------+
| Warning | 1356 | View 'test.v' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them |
+---------+------+--------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
MySQL Version:
```
root@2835f3d7b299:/# mysql -V
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper
```

**Comment by morgo** [comment]
@AndrewDi interesting behavior!  I think this is the equivalent of running `CHECK TABLE` on each view.  Since TiDB does not support `CHECK TABLE`, I think we should leave this to do later.

The 8.0 feature I was referring to is `I_S.VIEW_TABLE_USAGE`.  You can find more info by searching for "information schema" within [this page](https://mysqlserverteam.com/the-mysql-8-0-13-maintenance-release-is-generally-available/).

**Comment by AndrewDi** [comment]
@morgo I'm agree with your idea, we could leave view check unimplement here. @XuHuaiyu
