### ISSUE TITLE
Incompatible issues about date and time functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#9717]
## Historical

- [x] #9666 @qw4990 #9693 cherry-picked
- [x] #9667 @qw4990 #9702 cherry-picked
- [x] #9669 @zyycj #9685 cherry-picked
- [x] #9710 @qw4990 #9884 cherry-picked
- [x] #9711 @qw4990 #9884 cherry-picked
- [x] #9713 @qw4990 #9975 cherry-picked
- [x] #9715 @b41sh #9874 cherry-picked
- [x] #9727 @erjiaqing #10329 cherry-picked
- [x] #9728 @WangXiangUSTC #10116 cherry-picked
- [x] #9729 @wjhuang2016 #9751 **WON'T FIX**
- [x] #9730 @qw4990 #10314 cherry-picked 
- [x] #9731 @wjhuang2016 #9746 #9750
- [x] #9732 @qw4990 #10109 cherry-picked
- [x] #9734 @WangXiangUSTC #9933  cherry-picked
- [x] #9735 @AndrewDi #10074  cherry-picked
- [x] #9736 @qw4990 #10380 cherry-picked
- [x] #9764 @erjiaqing #10313  cherry-picked
- [x] #9767 @b41sh #9856 cherry-picked
- [x] #9769 @qw4990 #10368 cherry-picked
- [x] #9770 @Debiancc #9899 cherry-picked
- [x] #9773 @b41sh #9819 cherry-picked
- [x] #9774 @lzmhhh123 #9841  cherry-picked
- [x] #9775 @WangXiangUSTC #9822 cherry-picked
- [x] #10051 **WON'T FIX** 
- [x] #9776 **INVALID**
- [x] #10346 @erjiaqing #10347 cherry-picked
- [x] #10361 @qw4990 #10368 cherry-picked
- [x] #9813 @winoros #9830 cherry-picked
- [x] #10382 @mantuliu #10383 cherry-picked
- [x] #9763 @qw4990 #10753

**Comment by together-wang** [comment]
https://github.com/pingcap/tidb/issues/10504

**Comment by ti-srebot** [comment]
## Please edit this comment or add a new comment to complete the following information

### Not a bug

1. Remove the 'type/bug' label
2. Add notes to indicate why it is not a bug

### Duplicate bug

1. Add the 'type/duplicate' label
2. Add the link to the original bug

### Bug

Note: Make Sure that 'component', and 'severity' labels are added
Example for how to fill out the template: https://github.com/pingcap/tidb/issues/20100

#### 1. Root Cause Analysis (RCA) (optional) 


#### 2. Symptom (optional)



#### 3. All Trigger Conditions (optional)



#### 4. Workaround (optional)

#### 5. Affected versions



#### 6. Fixed versions
